heketi/heketi

- main.go
- plugins/glusterfs/bricks.go
- plugins/glusterfs/glusterfs.go
- plugins/glusterfs/glusterfsdb.go
- plugins/glusterfs/glusterfsdb_test.go
- plugins/glusterfs/handler_node.go
- plugins/glusterfs/handler_volume.go
- plugins/glusterfs/node.go
- plugins/glusterfs/ring.go
- plugins/glusterfs/volume.go
> Ring creation

- handlers/asynchttp.go
- handlers/asynchttp_test.go
Provides support for asynchronous HTTP requests.
Fixes #38 
> AsyncManager

- handlers/asynchttp.go
- handlers/asynchttp_test.go
This function handles a lot of the boiler plate
code that is needed whenever working with asynchronous
http response.
> Support for a handler function in Async API

- apps/glusterfs/app.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_cluster_test.go
- rest/asynchttp_test.go
- utils/log.go
> Cluster delete

- utils/log.go
- utils/log_test.go
> Print caller file and number correctly

- apps/glusterfs/app.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/cluster_entry.go
- apps/glusterfs/cluster_entry_test.go
- apps/glusterfs/models.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
- rest/asynchttp.go
- rest/asynchttp_test.go
- utils/log.go
> NodeAdd and NodeInfo APIs

- apps/glusterfs/app.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_node.go
- apps/glusterfs/cluster_entry.go
- apps/glusterfs/cluster_entry_test.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
Also:
* Added ClusterDelete
* Added more unit tests to cluster entry
Closes #49
> Support for NodeDelete

- rest/asynchttp.go
- rest/asynchttp_test.go
> AsyncFunc test now correctly pends

- apps/glusterfs/app.go
- apps/glusterfs/app_device.go
- apps/glusterfs/app_device_test.go
- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/models.go
- apps/glusterfs/node_entry_test.go
- utils/statusgroup.go
- utils/statusgroup_test.go
* StatusGroup API added
* Fixed up NodeDelete unit tests
Closes #50 
> DeviceAdd Support

- apps/glusterfs/models.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
> Correct node structure

- apps/glusterfs/app.go
- apps/glusterfs/app_device.go
- apps/glusterfs/app_device_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
> DeviceInfo and unit tests

- apps/glusterfs/app_cluster_test.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/cluster_entry.go
- apps/glusterfs/cluster_entry_test.go
- apps/glusterfs/models.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
> Remove storage info from cluster and node

- apps/glusterfs/app.go
- apps/glusterfs/app_device.go
- apps/glusterfs/app_device_test.go
- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
> Device delete

- apps/glusterfs/cluster_entry.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/entry.go
- apps/glusterfs/node_entry.go
> Refactor entries into one common file

- apps/glusterfs/allocationlist.go
- apps/glusterfs/app.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/brick_entry.go
- apps/glusterfs/brick_entry_test.go
- apps/glusterfs/cluster_entry.go
- apps/glusterfs/cluster_entry_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/entry.go
- apps/glusterfs/errors.go
- apps/glusterfs/models.go
- apps/glusterfs/node_entry_test.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
* Moved errors errors.go
* Brick entry and tests created
* Abstracted db functions into entry.go
> VolumeCreate and VolumeInfo APIs

- apps/glusterfs/app.go
- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/models.go
- apps/glusterfs/volume_entry.go
- utils/jsonutils.go
> Volume list

- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/brick_entry.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
* Added Brick and Volume Destroy
Closes #56
> VolumeDelete API

- Makefile
- main.go
> Simple Package

- apps/glusterfs/app.go
- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/creator.go
- apps/glusterfs/models.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
* Added creator.go so that we can mock brick creation
Closes #55 
> Support for VolumeExansion.

- GLOCKFILE
> Update go dependencies

- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
> Check that hostname is not an empty string

- apps/glusterfs/app.go
- apps/glusterfs/app_config.go
- apps/glusterfs/app_device.go
- apps/glusterfs/app_device_test.go
- apps/glusterfs/app_node.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/models.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/device.go
- executors/sshexec/sshexec.go
- rest/asynchttp.go
- tests/functional/heketi_test.go
- utils/ssh/ssh.go
* Fixed DeviceDelete to be asynchronous
Closes #120 
Closes #121 
> Device Add and Delete supported on GlusterFS

- Makefile
Config file is setup to use mock executor by default
> Added configuration file to dist

- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/brick_entry.go
- apps/glusterfs/brick_entry_test.go
- apps/glusterfs/cluster_entry.go
- apps/glusterfs/creator.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/brick.go
- executors/sshexec/peer.go
- executors/sshexec/sshexec.go
- executors/sshexec/volume.go
- tests/functional/heketi_test.go
- utils/ssh/ssh.go
Added support to create and destroy both bricks and volumes
in GlusterFS.  Still need to add code to use the Ring, but for
now it uses a dummy allocator.
Closes #122
Closes #123
Closes #124
Closes #125
> Volume and Brick GlusterFS support

- .travis-coverage
- GLOCKFILE
- apps/app.go
- apps/glusterfs/app.go
- client/examples/python/clusters.py
- etc/heketi.json
- main.go
- middleware/jwt.go
- middleware/jwt_test.go
* Added example client in Python
* Update GLOCKFILE with new dependencies
* Added option in config file for authorization
Closes #58
> Support for Authorization usig JWT

- apps/glusterfs/device_entry_test.go
- apps/glusterfs/node_entry_test.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
- utils/stringset.go
- utils/stringset_test.go
> Add support for backupvolfile-servers

- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
> Brick information saved on the db

- apps/glusterfs/volume_entry.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/brick.go
- executors/sshexec/sshexec.go
- executors/sshexec/volume.go
- tests/functional/heketi_test.go
- utils/ssh/ssh.go
* Fixed ssh maximum sessions
* Fixed large number of bricks being passed in the command line
* Added expansion testing to functional tests
* Fixed issue where the allocation of storage was not freed
when the volume was deleted.
Closes #157
> Volume Expand support

- apps/glusterfs/brick_entry.go
- apps/glusterfs/brick_entry_test.go
- apps/glusterfs/creator.go
- executors/sshexec/brick.go
- executors/sshexec/device.go
- executors/sshexec/peer.go
- executors/sshexec/volume.go
- utils/ssh/ssh.go
> SSH timeout and Brick cleanup

- executors/sshexec/peer.go
> Do not probe in the other direction

- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
> Fix maximum number of bricks per volume

- apps/glusterfs/volume_entry_test.go
> Test storage is returned to device

- client/api/go-client/client.go
- client/api/go-client/cluster.go
- client/api/go-client/device.go
- client/api/go-client/node.go
- client/api/go-client/volume.go
- tests/functional/large/tests/heketi_test.go
- tests/functional/large/vagrant/Vagrantfile
Setup only 18 nodes as part of three clusters of six nodes.
There was an issue found when 30 nodes where used where
glusterd would time out during peer probe.
> Large functional tests

- apps/glusterfs/app.go
- apps/glusterfs/app_volume.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/models.go
- apps/glusterfs/volume_durability.go
- apps/glusterfs/volume_durability_ec.go
- apps/glusterfs/volume_durability_none.go
- apps/glusterfs/volume_durability_replica.go
- apps/glusterfs/volume_durability_test.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_allocate.go
- apps/glusterfs/volume_entry_create.go
- apps/glusterfs/volume_entry_test.go
- client/api/go-client/client.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/volume.go
- tests/functional/large/tests/heketi_test.go
- tests/functional/small/tests/heketi_test.go
- tests/tempfile.go
Created new Durability interface to be able to add new styles
in the future.  Also needed to update the Volume API to support
new durability types and make it also future proof.
Closes #194
Closes #175
Closes #192
Closes #196
> Support for Disperse and Distributed Volumes

- apps/glusterfs/app_device.go
- apps/glusterfs/brick_entry.go
- apps/glusterfs/brick_entry_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/volume_entry_allocate.go
- apps/glusterfs/volume_entry_test.go
- client/cli/go/main.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/brick.go
- executors/sshexec/device.go
- executors/sshexec/sshexec.go
Closes #24
Closes #187
Closes #193
> Support recommended values for LVM

- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/models.go
- apps/glusterfs/volume_entry.go
- client/cli/go/commands/cluster_create.go
- client/cli/go/commands/cluster_list.go
- client/cli/go/commands/device_add.go
- client/cli/go/commands/load.go
- client/cli/go/commands/node_add.go
- client/cli/go/commands/tests/sample.json
- client/cli/go/commands/volume_create.go
- client/cli/go/commands/volume_expand.go
- client/cli/go/commands/volume_list.go
- client/cli/go/main.go
* Fixed issues with alignment in device_entry
> Heketi CLI can now load JSON configuration

- executors/sshexec/peer.go
- executors/sshexec/sshexec.go
Taking a page from Ansible, the connection to a node has
been simplified to a single connection.
Closes #211
> Limit access to a node to a single command

- etc/heketi.json
- heketi.service
Created a systemd service for heketi. Issue #18 
Once things are in place for #17, the service file may need to change location.
> Heketi systemd

- main.go
Although this is still not a perfect way to stop the server,
at least it captures the signals correctly from systemd to
stop the http service.
Closes #220
> Fixes exit status for systemd

- apps/glusterfs/app_test.go
- main.go
Cannot test an interface against nil.  Instead, test the object
against nil, and once it passes, then save it on the interface
variable.
Closes #217
> Check if application object was created

- docker/centos7/Dockerfile
- docker/centos7/README.md
- docker/centos7/heketi.json
- docker/centos7/post_setup.sh
- docker/fedora22/Dockerfile
- docker/fedora22/README.md
- docker/fedora22/heketi.json
This relates to https://github.com/heketi/heketi/issues/218
Added Dockerfile for Fedora 22 and Centos 7. Please review and merge.
> Dockerfiles to build containers for heketi on Centos 7 and Fedora 22

- apps/glusterfs/volume_entry_allocate.go
- apps/glusterfs/volume_entry_test.go
> Do not allow bricks on the same node

- executors/sshexec/device.go
> Delete a device from db even when node is down

- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- tests/functional/large/tests/heketi_test.go
- tests/functional/small/tests/heketi_test.go
> Do not allow the default zone value of 0

- client/cli/go/commands/node_add.go
> Print correct error message

- AUTHORS
Updating AUTHORS file with Sid's email address.
> Add Sid's name to AUTHORS file

- client/api/python/heketi/heketi.py
- client/api/python/heketi/test_client.py
With this, an application should be able to run heketi operations in python. These are wrappers for Heketi API calls. All calls provide return values as tuples, the first part containing the actual output, and the second part containing the error status code (if any). 
TODO: The volume creation part doesn't support all the options yet.
> Python API for Heketi

- Makefile
- client/cli/go/Makefile
> New linker settings

- extras/docker/unstable/Dockerfile
- extras/docker/unstable/README.md
> Add heketi-cli to docker dev container

- executors/sshexec/sshexec.go
Usage: if ssh is configured on port other than 22 in the setup,
add an extra argument called 'port' in sshexecutor section in heketi
config file as shown below.
heketi.json
...
"_sshexec_comment": "SSH username and private key file information",
"sshexec": {
"keyfile": "/etc/heketi/id_rsa",
"user": "root",
"port":"8000"
},
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> Make ssh port configurable in config file

- .travis.yml
- client/api/python/heketi/__init__.py
- client/api/python/heketi/heketi.py
- client/api/python/requirements.txt
- client/api/python/setup.py
- client/api/python/test-requirements.txt
- client/api/python/test/unit/heketi.json
- client/api/python/test/unit/test_client.py
- client/api/python/tox.ini
- client/api/python/unittests.sh
* Fixed a few bugs in the library
* Unit tests can run in Travis-ci
* setup.py has been setup to enable packaging
* Tox for unit test
* Script to create a heketi server for unit tests
> Python library package and unit tests

- etc/heketi.json
- executors/sshexec/brick.go
- executors/sshexec/brick_test.go
- executors/sshexec/sshexec.go
- executors/sshexec/sshexec_test.go
Fstab location can be customized in the configuration file.
Also finally added unit tests to sshexec.
Closes #305
Closes #169
> Support for custom fstab

- README.md
* README.md - minor typo fix
Signed-off-by: Jonathan Holloway <loadtheaccumulator@gmail.com>
> fix minor readme typo

- AUTHORS
Signed-off-by: hchiramm <hchiramm@redhat.com>
> Updating Authors file

- etc/heketi.json
> Kubernetes configuration documentation

- .gitignore
Signed-off-by: hchiramm <hchiramm@redhat.com>
> update gitignore for patches and rejects.

- extras/openshift/template/heketi.json
> Remove name selector

- .travis-coverage
- .travis.yml
- GLOCKFILE
- Makefile
- client/cli/go/Makefile
> Fix issue with speter.net

- apps/glusterfs/app.go
- main.go
> Able to use /hello w/o authentication

- client/cli/go/cmds/volume.go
> Heketi-cli can now create a PV on volume creation

- client/cli/go/cmds/volume.go
- executors/kubeexec/kubeexec.go
> Use a shortId for the PV name

- apps/glusterfs/models.go
Signed-off-by: Neha rawat <nerawat@redhat.com>
> Fixing Volume Id field in volume info

- AUTHORS
Signed-off-by: Neha rawat <nerawat@redhat.com>
> Modified AUTHORS file

- apps/glusterfs/allocator_simple.go
- apps/glusterfs/allocator_simple_test.go
> Allocator needs to online add online devices

- client/cli/go/cmds/volume.go
- pkg/utils/log_test.go
> Print volume name and cluster when listing volumes

- extras/openshift/template/glusterfs-template.json
https://github.com/heketi/heketi/issues/362
> Gluster Template updated

- client/cli/go/topology-sample.json
> heketi:heketi topology sample add

- client/cli/go/cmds/volume.go
> Typo in Error message

- client/cli/go/cmds/device.go
- client/cli/go/cmds/node.go
> Fix help screen flags

- apps/glusterfs/allocator_simple.go
- apps/glusterfs/allocator_simple_ring.go
- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
> Check for name conflict on volume creation 2

- extras/openshift/template/glusterfs-template.json
We do not need run from the host.
> Mount all of /run to allow use of yum update

- extras/docker/ci/Dockerfile
- extras/docker/ci/README.md
- extras/docker/ci/heketi.json
- tests/functional/README.md
Also update the README with the appropriate requirements
> Docker builds for automated functional tests

- extras/openshift/endpoint/gluster-endpoint.json
- extras/openshift/service/gluster-service.json
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> Adding services and endpoints sample files.

- pkg/kubernetes/pv.go
> Create PVs with Retain policy

- apps/glusterfs/limits.go
> Reduce max brick sets to 32

- extras/openshift/templates/glusterfs-template.json
- extras/openshift/templates/heketi-template.json
> Use Recreate Deployment Config policy

- apps/glusterfs/app.go
- apps/glusterfs/app_test.go
- apps/glusterfs/app_volume_test.go
There could be situations where the filesystem goes
into a read-only mode.  In these situations, Heketi
should still be able to start up, but in read-only
mode.
Closes #435 
> Support opening database in read-only mode

- executors/kubeexec/kubeexec.go
- executors/kubeexec/kubeexec_test.go
- extras/openshift/templates/heketi-template.json
> Set snapshot limit using environment variable

- client/cli/go/cmds/topology.go
Skip any nodes or devices which have errors and
continue to try to add the other ones.
It also now supports adding the same topology JSON
file, and it will skip any nodes or devices it already
has registered.
Closes #414
> Better user experience when loading topology

- executors/sshexec/brick.go
- executors/sshexec/brick_test.go
> Use /dev/mapper in fstab

- tests/functional/TestManyBricksVolume/config/heketi.json
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/config/heketi.json
- tests/functional/TestVolumeSnapshotBehavior/config/heketi.json
> Fix test config files

- doc/man/heketi-cli.8
minor typo fix in the Heketi Man page
> minor typo in man page

- tests/functional/TestManyBricksVolume/teardown.sh
- tests/functional/TestManyBricksVolume/vagrant/Vagrantfile
- tests/functional/TestManyBricksVolume/vagrant/roles/common/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/run.sh
- tests/functional/TestOpenShiftSmokeTest/teardown.sh
- tests/functional/TestOpenShiftSmokeTest/tests/deploy/roles/client/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/tests/deploy/run.sh
- tests/functional/TestOpenShiftSmokeTest/vagrant/roles/client/files/hosts.conf
- tests/functional/TestOpenShiftSmokeTest/vagrant/roles/client/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/vagrant/roles/cluster/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/vagrant/roles/common/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/vagrant/roles/master/tasks/main.yml
- tests/functional/TestOpenShiftSmokeTest/vagrant/up.sh
- tests/functional/TestSmokeTest/teardown.sh
- tests/functional/TestSmokeTest/vagrant/Vagrantfile
- tests/functional/TestSmokeTest/vagrant/roles/common/tasks/main.yml
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/Vagrantfile
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/roles/common/tasks/main.yml
- tests/functional/TestVolumeSnapshotBehavior/teardown.sh
- tests/functional/TestVolumeSnapshotBehavior/vagrant/Vagrantfile
- tests/functional/TestVolumeSnapshotBehavior/vagrant/roles/common/tasks/main.yml
- tests/functional/lib.sh
- tests/functional/run.sh
> Reliable CI system

- AUTHORS
Signed-off-by: Michael Adam <obnox@samba.org>
> AUTHORS: add my identities

- tests/functional/TestSmokeTest/README.md
> updated README.md with new pathnames and fixed typos

- apps/glusterfs/errors.go
- apps/glusterfs/volume_durability_ec.go
- apps/glusterfs/volume_durability_replica.go
- apps/glusterfs/volume_durability_test.go
- apps/glusterfs/volume_entry_test.go
> app:glusterfs: rename ErrMini[n]umBrickSize -> ErrMini[m]umBrickSize

- apps/glusterfs/volume_entry_allocate.go
Mostly cleans up misleading comments and debug statements.
This makes it much more obvious to me what is going on.
> apps:glusterfs: clarify logic in allocBricksInCluster() a bit

- .gitignore
added
1. generated files
2. cscope & ctags generated files and
3. patch files
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
> build: add more files to .gitignore

- client/cli/go/cmds/root.go
This is a variant of @MohamedAshiqrh 's patch. for issue #410 . For me, it works as expected with and without the server var set.
Closes #415
> Cli print root usage

- client/cli/go/heketi-cli.sh
How to test:
copy this file to /usr/share/bash-completion/completions/ then source it.
`# cp heketi-cli.sh /usr/share/bash-completion/completions/`
`# source  /usr/share/bash-completion/completions/heketi-cli.sh`
now you are good to go.
NOTE: this is still WIP. not working in zsh, can send the support later too.
> heketi-cli: Bash auto-completion file

- client/cli/go/cmds/topology.go
> heketi-cli: fix typo in error message

- pkg/utils/log.go
- pkg/utils/log_test.go
> Allow LogError to return an error from the supplied format string.

- apps/glusterfs/volume_entry.go
> app:glusterfs: better error propagation from brick allocation

- apps/glusterfs/app_node_test.go
- pkg/utils/bodystring.go
Incidental stuff I found while working on #355. Not required for it, but I figured I may as well see if they're worth taking anyway. :)
> Two minor patches

- tests/functional/lib.sh
Closes #496
Pair-Programmed-With: Raghavendra Talur <rtalur@redhat.com>
> tests/functional: always build the heketi server

- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_device.go
- apps/glusterfs/app_node.go
Clean up the spots where errors are logged and returned in
various glusterfs app file.
> Minor code simplication in error logging.

- pkg/utils/log.go
- pkg/utils/log_test.go
> Add logger.WarnErr() and touchup TestLogErr()

- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
Heketi uses the concept of registrations to manage conflict
resolution.  For example, a device `/dev/sda` cannot be added
twice to the same node.  In the same manner a node with the
same hostnames cannot be added twice.
To resolve conflicts, Heketi _Registers_ the conflicting string
as a _key_ in the database.  If for any reason the device or
node was unable to be added, then Heketi has methods to remove
that registration.
The issue arises when Heketi is adding a device, then crashes
for any number of reasons.  At this point, the registered key
is still in the database for conflict resolution, but the entry
does not exist.
This patch checks to make sure that a registered name has an
entry in the database, and it is not a stale key describing
and unknown device or node.
Closes #361 …
> app: Correctly handle stale registrations

- extras/systemd/heketi.service
> use a different file as systemd environmentfile

- extras/openshift/templates/deploy-heketi-template.json
- extras/openshift/templates/glusterfs-template.json
- extras/openshift/templates/heketi-template.json
Strategy and trigger are dc spec objects, Removing it from template.
> Templates: Strategy to be in spec of dc

- client/api/python/setup.py
> Update python client version

- client/api/python/setup.cfg
- client/api/python/setup.py
> modified setup.py for pypi and wheel distributions

- Makefile
> Makefile: Update to add kubernetes files in client package

- tests/functional/TestKubeSmokeTest/run.sh
Update minikube to 1.2.0, docker-machine to 0.8.2, and
kubernetes to v1.4.3
Closes #557
> tests: Update to Kubernetes to v1.4.3

- Makefile
- extras/kubernetes/README.md
- extras/kubernetes/deploy-heketi-deployment.json
- extras/kubernetes/glusterfs-deployment.json
- extras/kubernetes/heketi-deployment.json
- extras/kubernetes/heketi-service-account.yaml
This change fixes some of the issues in the Kubernetes deployment,
and adds the topology sample file to the distribution
> Kubernetes deployment fixes

- extras/docker/unstable/README.md
- extras/kubernetes/deploy-heketi-deployment.json
- extras/kubernetes/heketi-deployment.json
Master branch should make use of heketi/heketi:dev image.
> Kubernetes Deployment: Changes based on Kubernetes Integration

- extras/kubernetes/deploy-heketi-deployment.json
- extras/kubernetes/heketi-deployment.json
- extras/openshift/templates/deploy-heketi-template.json
- extras/openshift/templates/heketi-template.json
Based on images with tags listed in docker hub.
https://hub.docker.com/r/heketi/heketi/tags/
> Heketi Images: Changed to Release 3

- apps/glusterfs/app_volume_test.go
- apps/glusterfs/volume_entry_allocate.go
Earlier, the bricks were only saved to the DB in volume.Create.
Closes #382
Pair-Programmed-With: Raghavendra Talur <rtalur@redhat.com>
Pair-Programmed-With: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>
> app: save bricks in allocBricks() to keep the db consistent

- extras/openshift/templates/glusterfs-template.json
> glusterfs-template:Add bindmount for /var/lib/misc/glusterfsd

- doc/man/heketi-cli.8
> man page: Add all new heketi-cli commands and flags in man page

- tests/functional/TestKubeSmokeTest/md5sums
- tests/functional/TestKubeSmokeTest/run.sh
- tests/functional/TestKubeSmokeTest/testHeketiMock.sh
- tests/functional/TestKubeSmokeTest/testHeketiRpc.sh
Combined work of Luis and myself.
> Kube smoke test fixes

- tests/functional/run.sh
Signed-off-by: Luis Pabón <luis.pabon@coreos.com>
> tests: Fix unable to execute command in docker

- executors/kubeexec/kubeexec.go
> Clarify DaemonSet-related error message.

- apps/glusterfs/volume_entry.go
Error in the logger debug message.
> Minor typo in log message

- apps/glusterfs/app_volume.go
> Logging: Volume create error message to be logged

- extras/kubernetes/heketi-deployment.json
As the proposed way is now to use ds, this variable is missing
> Add daemonset envvar

- apps/glusterfs/app_device.go
- apps/glusterfs/app_node.go
> Logging: Node and device delete conflict message to be logged

- executors/sshexec/brick.go
- executors/sshexec/brick_test.go
- pkg/utils/ssh/ssh.go
- tests/functional/TestSmokeTest/tests/heketi_test.go
Closes #611 
This is a combination of #612 and #614 with the change requested
> Gid chmod fix

- extras/openshift/templates/glusterfs-template.json
> Glusterfs Template:Read only boolean value added as string.

- client/cli/go/cmds/heketi_storage.go
> Change heketidbvolume size to 2GB

- apps/glusterfs/app_test.go
- apps/glusterfs/app_volume_test.go
- apps/glusterfs/limits.go
- apps/glusterfs/volume_durability_test.go
Closes : #639
Supersedes PR #641
> Change BrickMinSize to 1GB enabling heketi to create 1GB volumes

- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/teardown.sh
> tests: Add missing teardown.sh to TestVolumeNotDeletedWhenNodeIsDown

- apps/glusterfs/app_volume.go
> fix some comments in volume functions

- client/api/python/unittests.sh
- extras/docker/ci/Dockerfile
- extras/docker/rpi/Dockerfile
- extras/docker/stable/Dockerfile
- extras/docker/unstable/Dockerfile
- extras/etc/init/heketi.initd
- extras/systemd/heketi.service
- main.go
- tests/functional/TestManyBricksVolume/README.md
- tests/functional/TestSmokeTest/README.md
- tests/functional/TestVolumeSnapshotBehavior/README.md
- tests/functional/lib.sh
Closes: #318 
Created a new instance of heketi server cli in cobra to avoid unknown flags importation.
> CLI instance for heketi server

- extras/docker/fromsource/heketi-start.sh
- extras/docker/rpi/heketi-start.sh
- extras/kubernetes/heketi-start.sh
Signed-off-by: Luis Pabón <luis.pabon@coreos.com>
> Update start script to use cli options

- apps/glusterfs/allocator_simple.go
- apps/glusterfs/app.go
- apps/glusterfs/app_device.go
- apps/glusterfs/brick_entry.go
- apps/glusterfs/brick_entry_test.go
- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/errors.go
- apps/glusterfs/volume_entry_allocate.go
- apps/glusterfs/volume_entry_test.go
- client/api/go-client/device.go
- client/api/python/heketi/heketi.py
- client/cli/go/cmds/device.go
- executors/executor.go
- executors/mockexec/mock.go
- executors/sshexec/volume.go
- pkg/glusterfs/api/types.go
> Revert "Remove Device: Used to distribute all the bricks from device to other devices"

- doc/design/README.md
This could become a place for design documents and design proposals.
Following the kubernetes example, we could file PRs against (new) documents in this folder as Design-PRs for discussing designs for new features.
> Add a doc/design/ directory for future purposes

- client/cli/go/cmds/heketi_storage.go
> provide flag to specify heketi image in copy job

- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/node_entry.go
- apps/glusterfs/node_entry_test.go
- client/api/go-client/node.go
- client/api/python/heketi/heketi.py
- client/cli/go/cmds/node.go
Node Remove is called to migrate all the bricks in device associated to a node.
> Node Remove: Removes all the device in the node

- apps/glusterfs/volume_entry_test.go
> Add TestNewVolumeEntryFromRequest tests for each durability type.

- apps/glusterfs/volume_entry_test.go
* fix copy'n'paste errors in comments
* add explaining comment
* make one size check explicit.
> Improve TestVolumeEntryCreateBrickDivision a bit

- .travis.yml
- Makefile
Instead ask the user to install it using their preferred method.
> make: Do not automatically install glide.

- extras/kubernetes/heketi-service-account.json
- extras/kubernetes/heketi-service-account.yaml
The included kubernetes files are missing the heketi service account, this commit contains the missing file.
> Added the missing json file from deployment process.

- extras/docker/fromsource/Dockerfile
> Fix glide in dockerfile

- apps/glusterfs/app_node.go
- apps/glusterfs/app_node_test.go
> addNode: Check if glusterd is running on the peer node.

- client/api/python/setup.py
> Update python client version.

- Makefile
- tests/functional/TestSmokeTest/tests/heketi_test.go
- tests/functional/run.sh
> Cleaning up functional tests

- apps/glusterfs/volume_entry_create.go
- apps/glusterfs/volume_entry_test.go
As any node in the TSP can give the volifile for the client.
closes: #825 
> TSP should be backup-volfile server

- executors/kubeexec/kubeexec.go
> implement timeout for kubeexec

- client/cli/go/cmds/device.go
- client/cli/go/cmds/node.go
- client/cli/go/cmds/topology.go
- client/cli/go/cmds/volume.go
Typo error for retrieve fixed inside the heketi-cli help
> Typo Error under help menu for heketi-cli

- Makefile
- client/cli/go/Makefile
As per https://ttboj.wordpress.com/2017/02/26/faster-golang-builds/
> golang: Make this fast

- Makefile
> build: remove outdated comments from Makefile

- Makefile
Create a dependencies tarball.
> Deps tarball

- Makefile
- test.sh
This will simplify future patches.
> test: Improve test infrastructure

- MAINTAINERS.md
> Add a MAINTAINERS file.

- executors/sshexec/device.go
> executor:ssh: improve log message in DeviceTeardown

- apps/glusterfs/allocator.go
- apps/glusterfs/allocator_mock.go
- apps/glusterfs/allocator_simple.go
- apps/glusterfs/allocator_simple_test.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/errors.go
- apps/glusterfs/volume_entry_test.go
This now populates the rings on load from disk. Previously it only did
this if devices existed. Run time adds still don't add to the ring yet.
> apps: glusterfs: Populate the ring on load from disk

- apps/glusterfs/app.go
> log error for failed open

- extras/docker/fromsource/heketi-start.sh
- extras/docker/rpi/heketi-start.sh
A variety of enhancements to the Docker container startup scripts.
Resolves #843
> Updates to the startup scripts for Docker containers

- Makefile
- client/cli/go/Makefile
1. Removed dead code related to APP_SUFFIX
2. Matched version in client/cli/go/Makefile to $TOPDIR makefile
3. Removed usage of sort by creatorder in git command
> Makefile enhancements

- Makefile
- client/cli/go/Makefile
- tests/020-test-makefiles.sh
* Standardize on tabs vs spaces
* consolidate multiple .PHONY lines
Inspired by a comment from @purpleidea .
> Cleanup makefiles

- middleware/jwt_test.go
Cover a previously uncovered error condition.
> middleware: increase code coverage of jwt error condition

- client/api/python/unittests.sh
- client/cli/go/heketi-cli.sh
- extras/docker/fromsource/heketi-start.sh
- extras/docker/rpi/build-rpi-dockerfile.sh
- extras/docker/rpi/heketi-start.sh
- test.sh
- tests/020-test-shellscripts.sh
- tests/030-govet.sh
- tests/100-gotest.sh
- tests/functional/TestKubeSmokeTest/run.sh
- tests/functional/TestKubeSmokeTest/teardown.sh
- tests/functional/TestKubeSmokeTest/testHeketiMock.sh
- tests/functional/TestKubeSmokeTest/testHeketiRpc.sh
- tests/functional/TestManyBricksVolume/run.sh
- tests/functional/TestManyBricksVolume/teardown.sh
- tests/functional/TestManyBricksVolume/vagrant/up.sh
- tests/functional/TestSmokeTest/run.sh
- tests/functional/TestSmokeTest/teardown.sh
- tests/functional/TestSmokeTest/vagrant/up.sh
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/run.sh
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/teardown.sh
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/up.sh
- tests/functional/TestVolumeSnapshotBehavior/run.sh
- tests/functional/TestVolumeSnapshotBehavior/teardown.sh
- tests/functional/TestVolumeSnapshotBehavior/vagrant/up.sh
- tests/functional/lib.sh
- tests/functional/run.sh
These changes:
* add a checker script
* make a bunch of largely mechanical changes suggested by shellcheck
* tag some files as not to be checked (for now)
* tag some lines to ignore a particular shellcheck rule
I decided not to try and fix some of the more complex files in this PR as there's already a lot to review here. I fully intend on removing the skip markers that are also marked fixme.
> add test for shellscript syntax and quality

- apps/glusterfs/device_entry.go
- main.go
- pkg/kubernetes/backupdb_test.go
> fix spelling errors found by goreportcard

- .travis.yml
- tests/020-gofmt.sh
Replace the last travis specific code quality check with a new script.
> tests: replace the last travis specific check

- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_test.go
Changes split out cluster filtering logic, clean up and compact the filtering logic, and add check fo bad clusters.
> apps: Split eligble clusters logic out from volume entry create

- MAINTAINERS.md
> doc: Add @phlogistonjohn as a maintainer.

- client/cli/go/cmds/cluster.go
- doc/man/heketi-cli.8
Polish the heketi-cli manpage a bit.
As preparation for further commits.
> Doc improvements

- apps/glusterfs/app_middleware_test.go
- apps/glusterfs/node_entry_test.go
- client/api/go-client/client_test.go
- pkg/utils/uuid.go
- pkg/utils/uuid_test.go
* Separate the uuid generation/formatting from its source of randomness
* Allow other code to more easily override things with a custom (predictible) source for uuid generation
* Tests!
> utils: testing and test support in uuid module

- apps/glusterfs/app.go
- apps/glusterfs/app_cluster.go
- apps/glusterfs/app_cluster_test.go
- apps/glusterfs/app_device_test.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/cluster_entry_test.go
- client/api/go-client/client_test.go
- client/api/go-client/cluster.go
- client/api/go-client/topology.go
- client/api/python/heketi/heketi.py
- client/api/python/test/unit/test_client.py
- client/cli/go/cmds/cluster.go
- doc/api/api.md
- doc/man/heketi-cli.8
- pkg/glusterfs/api/types.go
- pkg/heketitest/heketitest_test.go
- tests/functional/TestManyBricksVolume/tests/heketi_test.go
- tests/functional/TestSmokeTest/tests/heketi_test.go
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go
- tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go
It is useful/needed to be able to change the cluster File and Block flags after cluster creation.
> Add support to set clusterflags through API and cli

- client/api/go-client/backup.go
- client/api/go-client/block_volume.go
- client/api/go-client/client.go
- client/api/go-client/cluster.go
- client/api/go-client/device.go
- client/api/go-client/node.go
- client/api/go-client/volume.go
- pkg/utils/bodystring.go
As per discussion with @raghavendra-talur earlier.
> client:api: add missing r.Body.Close() calls

- tests/functional/lib.sh
- tests/functional/run.sh
> tests: small QoL tweaks for running the functional tests

- client/api/python/test/unit/test_client.py
> cli:python: use natural, idiomatic asserts in test_client.py

- apps/glusterfs/app_block_volume.go
- apps/glusterfs/app_block_volume_test.go
> don't limit blockvolume size to default blockhosting vol size

- .travis.yml
Condense the coverage vs no-coverage test runs into
one if-else statement.
> travis: try to let the travis run pass again

- apps/glusterfs/app_config.go
> allow setting loglevel through env

- apps/glusterfs/volume_entry_test.go
These tests check for error conditions that I created when I was doing preliminary untangle work.
> tests: add some unit tests

- tests/functional/run.sh
Track what functional tests pass or fail and print a summary
at the end of the test suite runner.
> tests: summarize what functional tests pass or fail

- client/cli/go/cmds/heketi_storage.go
> cli/heketi_storage: show usage only when asked

- apps/glusterfs/volume_entry.go
- apps/glusterfs/volume_entry_allocate.go
- apps/glusterfs/volume_entry_create.go
- apps/glusterfs/volume_entry_test.go
Preparations for introducing pending operations.
> First sweep of untangle patches.

- apps/glusterfs/block_volume_entry.go
- apps/glusterfs/volume_entry.go
Some further improvements around eligibleClusters()
> improve eligibleClusters

- apps/glusterfs/device_entry_test.go
Cover the cases where a device being removed has bricks,
and the case where the device has bricks but nowhere to put them.
> apps: add unit test cases to cover more device remove cases

- apps/glusterfs/listing.go
- apps/glusterfs/listing_test.go
To continue any further with listing.go we're going to have to merge in pending operations bits.
> apps: preliminary support for working with pending items in listing.go

- tests/functional/TestSmokeTest/vagrant/Vagrantfile
> vagrant: use official centos boxes for virtualbox

- apps/glusterfs/block_volume_entry.go
- apps/glusterfs/operations.go
The following changes are a set of small fixes and improvments on top of the previous untangle work.
> Untangle Pt. II -  Small Fixes and Improvements

- apps/glusterfs/block_volume_entry.go
Small improvement triggered by review of PR #1034 .
> Improve canHostBlockVolume

- apps/glusterfs/listing_test.go
- apps/glusterfs/operations_test.go
Depends on PR #1037 
Now that the bulk of the pending operations infrastructure is in place try to add a reasonable amount of (mostly success path) test coverage for the new code.
> Untangle Pt. II - Additional testcases

- executors/cmdexec/config.go
- executors/kubeexec/kubeexec.go
- executors/sshexec/sshexec.go
From next release, rebalance after add-brick won't be experimental.
> do not show warning for rebalance on expansion

- apps/glusterfs/operations.go
...was logged as failed to expand volume
> fix logging error where failed to delete volume

- apps/glusterfs/device_entry.go
- apps/glusterfs/device_entry_test.go
> allow moving device from failed to offline state

- apps/glusterfs/volume_entry_allocate.go
Some improvements to make replaceBrickInVolume more readable...
Started as prep work for the allocator change, but not quite there yet.
> Refactor replace brick in volume

- tests/functional/TestManyBricksVolume/tests/heketi_test.go
- tests/functional/TestSmokeTest/tests/heketi_test.go
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go
- tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go
> always set devices to failed before deleting

- extras/docker/fromsource/Dockerfile
> Update the Dockerfile for release 6

- apps/glusterfs/device_entry.go
Split the device function that calculated the needed size values
for a new brick and constructed the new brick into two.
Now we can get the size values independently of creating the
brick object and mutating the device. This will be used in
future allocator enhancements.
> apps: split sizes calculation out of new brick function

- apps/glusterfs/allocator_simple_test.go
- apps/glusterfs/device_entry_test.go
- apps/glusterfs/volume_entry_test.go
- middleware/jwt_test.go
> fixed govet errors in test cases

- apps/glusterfs/app.go
as suggested by @phlogistonjohn on another occasion.
> apps: more idiomatic switch statement in NewApp()

- .travis.yml
> Add Go 1.9.4 & 1.10 to Travis build

- apps/glusterfs/app_block_volume_test.go
- apps/glusterfs/operations.go
- apps/glusterfs/operations_test.go
> Prevent wasteful creation of too small block-hosting volumes

- .github/ISSUE_TEMPLATE.md
> github: add an issue template

- docs/contributing.md
This adds a number of details about commits, commit messages, running tests, and pull requests to the contributing guide.
> Expand the contributing guide.

- .github/PULL_REQUEST_TEMPLATE.md
> github: Add a pull request template

- client/cli/go/cmds/block_volume.go
- client/cli/go/cmds/node.go
- client/cli/go/cmds/volume.go
fix for the improper information in heketi_cli help commands (Node add, volume create,volume expand, blockvolume create commands).
> updated heketi cli help commands

- tests/functional/README.md
- tests/functional/TestManyBricksVolume/run.sh
- tests/functional/TestSmokeTest/run.sh
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/run.sh
- tests/functional/TestVolumeSnapshotBehavior/run.sh
- tests/functional/lib.sh
Small quality-of-life improvements around the functional tests. It's pretty much just minor stuff that was annoying me and that I was hacking into the tests when I needed it.
> A few small functional test cleanups

- docs/design/snapshot.md
This is the proposed design for volume snapshot and clone operations.
> Snapshot design

- executors/cmdexec/volume.go
A volume expand operation consists of
1. creating new bricks
2. attaching new bricks to volume using gluster cli
3. performing rebalance operation to make new and existing files to use
newly added bricks.
The possibility of a rebalance command failing is high as it fails if even one
brick belonging to the volume is down. Hence, we choose to consider
VolumeExpand operation to be successful if steps 1 and 2 succeed. A log
message is printed making admin aware of manual action required to
complete volume expansion.
> executor: don't consider expand as failed if rebalance fails

- docs/design/arbiter.md
As suggested by @raghavendra-talur we can collaborate on the design doc within this PR.
> [COLLAB] Design arbiter volume support

- apps/glusterfs/volume_entry_test.go
- pkg/db/wrap.go
fix misspelled words
fix misspelled words
> fix misspelled words

- apps/glusterfs/volume_entry_test.go
- tests/functional/TestEnabledTLS/run.sh
- tests/functional/TestEnabledTLS/ssl.conf
- tests/functional/TestEnabledTLS/test_tls.py
- tests/functional/TestSelfTest/run.sh
- tests/functional/TestSelfTest/teardown.sh
- tests/functional/TestSmokeTest/config/heketi.json
- tests/functional/TestSmokeTest/tests/heketi_test.go
- tests/functional/TestUpgrade/test_upgrade.py
- tests/functional/lib.sh
- tests/functional/run.sh
Functional test runner had a couple of issues, the biggest being
not correctly exiting non-zero on a test failure. This change
fixes that along with some other general cleanups.
> fixes and improvements for functional test runner

- apps/glusterfs/app_device_test.go
- apps/glusterfs/app_node_test.go
- apps/glusterfs/block_volume_entry_test.go
- apps/glusterfs/operations_test.go
- apps/glusterfs/volume_durability_test.go
- apps/glusterfs/volume_entry_test.go
- middleware/jwt_test.go
check error in unit test cases
> check error in unit test cases

- tests/functional/TestEnabledTLS/test_tls.py
- tests/functional/TestUpgrade/test_upgrade.py
- tests/functional/lib.sh
When starting the server prior to running the tests probe
for heketi to start using the port before continuing.
I want to make sure this all works on centos ci before continuing.
> functional tests: wait for heketi to start using port 8080

- executors/cmdexec/brick.go
This change removes the fstab entry before removing lvm devices
in case either heketi or the node it terminated while the
steps are being performed. This way the system will never attempt
to mount a partially deleted item.
It seems preferable to have a bootable system with (temporarily)
orphaned storage rather than have a non bootable system.
> executors: when deleting a brick, remove fstab entry first

- apps/glusterfs/placer_arbiter.go
- apps/glusterfs/placer_arbiter_test.go
In testing it became apparent that tagging scenarios where a user
tags some nodes or devices for arbiter:required but leaves other
items untagged seems natural to a user. However, prior to this change
it had the effect of making placement failures highly likely on a
small cluster. This was due to the arbiter brick "stealing" a node
that needed to be used by a data brick, when the arbiter brick
was placed on an (implicit) arbiter:supported device rather
than the arbiter:required device.
What this change does is to prioritize devices that are tagged for
one type of brick when placing a brick of that type. In other words,
if any devices are tagged arbiter:required the placer prefers
to use those devices before it uses arbiter:supported devices.
The same goes for preferring to place data …
> bias the arbiter placer to prefer dedicated devices before general devices

- executors/cmdexec/brick.go
Heketi has been ignoring errors from umount of bricks (and
failures to edit fstab) and assuming that a Brick destroy
always works. Now that we have the pending operations framework
we actually want to keep track of failures to delete so
that heketi (and the user) knows what was supposed to be
deleted but wasn't, allowing for targeted cleanups
and debugging.
Fixes [rhbz #1565977](https://bugzilla.redhat.com/show_bug.cgi?id=1565977)
No tests, I know. Unfortunately, we don't have good tools to test this kind of error handling stuff yet. It's coming (soon I hope).
> executors: treat failure to unmount as a real error

- extras/docker/fromsource/Dockerfile
This is a bare minimum set of fixes needed to get the container
image building on dockerhub again.
Fixes #1186
> docker: fix fromsource/Dockerfile build

- apps/glusterfs/app_volume.go
Don't fail the deletion of a block-hosting volume if
it references a block volume id, that does not
exist in the database.
> Ignore nonexistent block volumes in deletion of block-hosting volume.

- glide.lock
[INFO]	--> Fetching updates for github.com/Sirupsen/logrus.
[ERROR]	Update failed for github.com/Sirupsen/logrus: The Remote does not match the VCS endpoint
[ERROR]	Failed to install: The Remote does not match the VCS endpoint
Fixes #
> fix glide install failure

- tests/functional/TestSmokeTest/tests/throttle_test.go
- tests/functional/lib.sh
Add a test to verify that throttling works cleanly when
encountering a "busy system" returning throttle errors.
> functional tests: check device & node removes work during throttle

- apps/glusterfs/app_volume_test.go
The test for volume size too small, wasn't actually testing
the volume expand api. There was no test for number too high
to fit in the struct. This change resolves these problems.
> apps: update bounds checking unit tests for volume expand

- tests/functional/TestSmokeTest/config/heketi.json
- tests/functional/TestSmokeTest/tests/block_volume_test.go
- tests/functional/TestSmokeTest/vagrant/roles/gluster/tasks/main.yml
This added a new functional test setup to test block volume operations(create,get and delete block volumes)
added test cases to test folloowing sceneraios
* creation of block volume
* get  and deletion of block volumes
Fixes #1288
> function test: added test cases for block volumes

- extras/docker/fromsource/heketi-start.sh
- extras/docker/rpi/heketi-start.sh
The startup script for the heketi container image used a blocking flock with a timeout. Normally, this would be the best way to do it but as heketi db is frequently deployed on a gluster volume and current versions of gluster may have issues with this use pattern we switch to polling the db with a non-blocking flock.
Works around issues in rhbz#1613260
> docker: use a non-blocking flock in heketi-start.sh

- extras/docker/fromsource/heketi-start.sh
- extras/docker/rpi/heketi-start.sh
By providing the environment variable HEKETI_TOPOLOGY_FILE with a
filename that is available in the container, the database gets populated
with this topology file.
In Kubernetes environments the HEKETI_TOPOLOGY_FILE can be provided as a
ConfigMap or Secret and mounted as a volume in the pods specification.
With this change it is now possible to deploy Heketi with a .yaml file
that contains the topology.json and the Heketi Deployment.
This has been [tested within minikube](https://github.com/nixpanic/minikube/blob/addons/gluster/README.storage-provisioner-gluster.md) and a [temporary fork for the container build](https://quay.io/repository/nixpanic/minukube-heketi).
> docker: load an initial topology if HEKETI_TOPOLOGY_FILE is set

- apps/glusterfs/listing.go
> apps:glusterfs: fix a comment typo for ListCompleteVolumes

- client/cli/go/cmds/node.go
Probably a copy-and-paste leftover.
> client: remove a comment (probably copy-and-paste leftover)

- docs/man/heketi-cli.8
heketi-cli cluster setflags --file
copy-paste typo
To correct documentation
No
Fixes #
> Options description typo: cluster setflags

- apps/glusterfs/try_on_host.go
- apps/glusterfs/volume_entry.go
Various small refactoring of code in apps preparing for the volume delete behavior of auto-cleanup.
This PR builds upon PR #1400 - please review and merge that PR first.
> Smallish refactoring in prep for more volume delete work

- apps/glusterfs/app.go
- apps/glusterfs/app_config.go
- apps/glusterfs/app_operations.go
- apps/glusterfs/operations.go
- apps/glusterfs/operations_cleanup.go
- apps/glusterfs/operations_cleanup_test.go
- apps/glusterfs/operations_manage.go
- apps/glusterfs/operations_manage_test.go
- apps/glusterfs/operations_volume_test.go
- client/api/go-client/operations.go
- client/cli/go/cmds/server.go
- main.go
- pkg/glusterfs/api/types.go
This PR is part of the auto clean up work and mainly focuses on adding (running) server side support for the clean up of pending operations.
Part of issue #1401
This PR builds on top of PR #1446 please review and merge that series first.
> auto cleanup pt3

- apps/glusterfs/app.go
- apps/glusterfs/app_operations.go
- apps/glusterfs/operations_cleanup.go
- apps/glusterfs/try_on_host.go
- client/cli/go/cmds/server.go
- executors/injectexec/hooks.go
- pkg/glusterfs/api/types.go
- tests/functional/TestErrorHandling/tests/background_cleanup_test.go
- tests/functional/TestErrorHandling/tests/common_test.go
- tests/functional/TestErrorHandling/tests/offline_cleanup_test.go
- tests/functional/TestErrorHandling/tests/online_cleanup_test.go
This PR is part of the auto clean up work and mainly focuses on adding (running) server side support for the clean up of pending operations.
Part of issue #1401 
This PR builds on top of PR #1456 please review and merge that series first.
> auto cleanup pt4

- tests/functional/TestErrorHandling/vagrant/roles/common/tasks/main.yml
- tests/functional/TestManyBricksVolume/vagrant/roles/common/tasks/main.yml
- tests/functional/TestSmokeTest/vagrant/roles/common/tasks/main.yml
- tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/roles/common/tasks/main.yml
- tests/functional/TestVolumeSnapshotBehavior/vagrant/roles/common/tasks/main.yml
Test of the changes to fix tests.
Fixes #1452 
Still trying it out.
> tests: trial change to see if this fixes a centos ci issue

- apps/glusterfs/examiner.go
> app: use sorted []string when using DeepEqual

- apps/glusterfs/brick_allocate_test.go
- apps/glusterfs/operations_manage.go
- apps/glusterfs/tags.go
- apps/glusterfs/volume_entry.go
- client/cli/go/cmds/heketi_storage.go
- client/cli/go/cmds/topology.go
- executors/injectexec/hooks_test.go
- tests/functional/TestSmokeTest/tests/heketi_test.go
This PR fixes issues found in `gofmt` and correct misspelled word. 
Fixes #
> Fix lint issues

- tests/functional/TestErrorHandling/tests/timeout_test.go
- tests/functional/TestErrorHandling/vagrant/roles/gluster/files/S99timeout.sh
- tests/functional/TestErrorHandling/vagrant/roles/gluster/files/kill-pid.sh
- tests/functional/TestErrorHandling/vagrant/roles/gluster/tasks/main.yml
TODO need to update commit message
Fixes #
> timeout: add functional test for gluster timeout

- extras/tools/README.md
- extras/tools/comparison.py
- extras/tools/dbconsistency.py
- extras/tools/scrub.py
I have been sucessfully using these scripts for debugging and fixing situations. I'm submitting the scripts for inclusion in the source tree as "contrib" scripts that are "use at your own risk". 
The scripts are mainly meant for advanced users who are somewhat familiar with the structure of the heketi db. Thus, the only documentation is the built-in help for each tool.
> Add extra offline diagnostic and repair scripts

- apps/glusterfs/dbcommon.go
Signed-off-by: Vijay Bellur <vbellur@redhat.com>
Fixes a minor error in an error message!
> Minor correction in error message

- apps/glusterfs/allocator_simple_ring_test.go
- apps/glusterfs/dbentry_test.go
- pkg/sortedstrings/sortedstrings_test.go
- pkg/utils/statusgroup_test.go
- tests/030-goimports.sh
Fix issues found in when I ran the `goimport` tool
> Fix issues found during goimport

- extras/tools/comparison.py
Adds a few improvements to the comparison.py tool in extras. Including limiting the PVs checked by storage class name and adding a basic brick comparison mode (triggered via the --bricks switch).
> Enhance the comparison tool

- extras/tools/dbconsistency.py
add more block volume reference checks in dbconsistency.py
Fixes #
> dbconsistency  block fixes

- apps/glusterfs/operations_block_volume.go
- tests/functional/TestErrorHandling/tests/online_cleanup_test.go
Older versions of heketi did not deduct the size of a new block volume
from the new BHV in a compound BHV+BV create. During the implementation
of auto-cleanup the only BHV tested were "new" ones with the space
properly deducted. Running heketi with some older pending ops in the db
showed heketi was not cleaning these old ops. This change corrects the
auto-cleanup code to ignore updating the used sizes of the BVH when the
BHV is already pending (and thus to be deleted) during cleanup.
Adds a test that a current db with a BHV+BV pending create to look
similar enough to the old contents of the block hosting volumes info of
an old heketi version that didn't update the used size of the BHV in
build. With the previous fix to the cleanup code this test passes, but
without this test will fail. …
> fix issue where old BHVs could not be cleaned up

- extras/tools/scrub.py
Add an option to scrub.py to skip deducting the sizes of bricks from devices. This option can be useful if the sizes in the db are already inconsistent and subtracting them would lead to invalid values. The sizes would need be manually corrected after the scrub.py script is used.
> extra tools: allow scrubbing without changing device sizes

- extras/tools/sizing/README.md
- extras/tools/sizing/fitting_room.py
- extras/tools/sizing/results2csv.py
This tool was recently used to help examine heketi's behavior around
placing X volumes adding up to a fixed overall size in order to
determine how consistently heketi could place the all the volumes and
investigate overall device usage.
This tool is mainly being submitted for reference and possibly as a future tool to help test an improvements to the distribution of bricks across nodes & devices.
This PR is based on PR #1529 in order for the test script to control the size of the devices heketi's  mock executor is generating. Please review and merge that PR first.
> extra tools: add a simplistic device sizing measurement tool

- docs/admin/install-standalone.md
I don't find anywhere that mention installation of client and fall into problem.
> add client installation command for epel

- README.md
Add a state of the project notice indicating that major development
on heketi has wound down and the project is entering a near-maintenance
mode.
> readme: add a state-of-the-project notice

- extras/tools/dbconsistency.py
- extras/tools/test_dbconsistency.py
Fix some missing checks in dbconsistency tool as well as start a rudimentary test suite for the tool.
Fixes #
> Various dbconsistency fixes and more

- extras/container/heketi-start.sh
Recently, we added a tool to heketi that sets the heketidbstorage volume
gluster settings to something more appropriate for hosting db files.
Currently that tool must be run by hand. This change adds the ability to
run the tool automatically during the start-up of the container.
To enable the tool set the environment var HEKETI_TRY_UPDATE_DB_VOL
to "yes".
Fixes #
Manually tested.
> extras: update container start script with ability to update dbvol

- .travis.yml
- Makefile
As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same and also release binaries for s390x.
> Add support for s390x

- executors/cmdexec/brick.go
The code that checks to see if a brick is stuck from unmounting has a
bug in that it does not check the error returned by the command that
runs lsof. This was probably lazy refactoring on my part. Move the bulk
of the diagnostic section into a helper function and only try to use the
command result when there was no connection error.
Fixes #
> cmdexec: prevent a crash by checking error return in diagnostic code

- docs/admin/volume.md
* update flag grammar, `-xx` is no longer supported in the new version
* fix a typo: `durabilty` --> `durability`
* sync EXAMPLES content from code: https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/volume.go#L128-L150
Fixes #
/cc @phlogistonjohn @raghavendra-talur
> docs: update flag grammar and fix a typo

- apps/glusterfs/block_volume_expand_test.go
add tests for block volume expand feature
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
> unit-tests: add tests for block volume expand feature

- extras/tools/dbconsistency.py
The dbconsistency.py tool was not doing much checking around nodes, and let at least one error slip through the cracks when I used it recently. This adds some more checking of nodes to the tool.
n/a
> extras: add more node based checks to dbconsistency.py tool

- client/cli/go/cmds/heketi_storage.go
Fixes #1695
Signed-off-by: kadern0 <kaderno@gmail.com>
Fixes typo
Fixes #1695
> Fixed typo

- client/cli/go/cmds/device.go
- tests/functional/TestErrorHandling/tests/brick_evict_test.go
This PR achieves the golang recommended coding style.
> Remove unnecessary underscore 

- apps/glusterfs/operations_device.go
If a brick destroy calls fails during brick evict and the node is
down, do not treat it as a fatal error. If the node or device replace
is being done for a permanently down node then the destroy call will
never succeed. Use the ability of heketi to probe the node to decide
if if the error is fatal (node responsive) or not (node unresponsive).
There's one flaw with this: if the node is temporarily down. In that
case we could be orphaning bricks on said node, and when it comes up
that node would be out of sync with heketi. A future direction might
be to add a new node state to indicate "offline-and-never-coming-back"
that indicate that errors in this code path are truly safe to ignore.
Fixes #1756  (maybe, needs validation)
Untested, needs practical validation. But I'm throwing this out as …
> apps: work around issue evicting & destroying old bricks on dead nodes

- .github/workflows/ci.yml
With this change github actions will test the changes on all branches
not just master
> github Actions: Change branches master to all

- .github/workflows/ci.yml
symlink was creating problem while running pytests, resolve the same via
copy the repo in go src
> github Actions: Resolve pytest failures

- executors/cmdexec/block_volume.go
> Fix CVE-2020-10763

- extras/kubernetes/glusterfs-daemonset.json
- extras/kubernetes/heketi-bootstrap.json
- extras/kubernetes/heketi-deployment.json
Fixes deployment issues on kubernetes versions that don't support `extensions/v1beta1` (versions 1.8+)
Fixes #1764
> Update deployments for Kubernetes v1.8+

- .github/workflows/ci.yml
> workflows: use supported tag on setup-go

- docs/admin/maintenance.md
despite answering similar questions in the past I had not realized we didn't have proper documentation for node and device replacement/removal until now. This change aims to fill that gap.
Fixes #1782
> docs: add missing docs for node and device replacement

- README.md
- docs/admin/demo.md
- docs/admin/install-openshift.md
- docs/admin/readme.md
- docs/admin/topology.md
- docs/developer/testing.md
- docs/maintainer/release.md
There were a few more docs remaining in the wiki which were not imported under the docs dir. I have now imported them as-is.
There are more things to be edited because some the documentation in the wiki had gone stale. I will send a new PR with changes after this PR is merged as I want to restrict this PR to import function.
> Import remaining docs from wiki

- Makefile
> Makefile glide experiment

- .github/workflows/ci.yml
> Update Go versions for the action

- apps/glusterfs/app_middleware.go
- client/api/go-client/client.go
- docs/profiling.md
- go.mod
- go.sum
- middleware/jwt.go
- middleware/jwt_test.go
use a community maintained fork of jwt
for reference: kubernetes/kubernetes#104007
Signed-off-by: haimantika mitra <haimantikamitra@gmail.com>
Fixes #
> godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"   

- .github/ISSUE_TEMPLATE.md
- README.md
Updates to the issue template and readme folllow.
> Updates to put emphasis on heketi's "deep" maintenance status
