.travis-fork-fix, .travis.yml
The repo now uses glock (https://github.com/robfig/glock) to maintain a consistent view of its dependencies.  Travis needed to be updated to use glock.
=> Travis support for glock

apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go
NodeDelete was returning StatusOK, when in fact it should be
returning StatusAccepted so that the work is done asynchronously.
Closes #116
=> NodeDelete needs to be asynchronous

executors/sshexec/sshexec.go, executors/sshexec/volume.go
* Also do not rebalance after expansion.  Instead it has
been made an 'experimental' feature that can be enabled
on the config file.
Closes #173
Closes #180
=> GlusterFS add-brick set max

apps/glusterfs/app.go, executors/sshexec/brick.go, executors/sshexec/device.go, executors/sshexec/peer.go, executors/sshexec/sshexec.go, executors/sshexec/volume.go, utils/ssh/ssh.go
Instead of a global throttle, use a throttle per host.  This
requires the creation of a channel per host.
Closes #181
=> Optimize ssh connections

tests/functional/large/tests/heketi_test.go, tests/functional/large/vagrant/Vagrantfile, tests/functional/large/vagrant/up.sh
Allows faster creation of VMs by creating the VMs in parallel. Also
creates 5 clusters of 6 nodes each.
=> Update large functional tests

executors/sshexec/brick.go
Mount options are available for /etc/fstab, but are not
set when first mounting the filesystem.
Closes #210
=> Mount options needed

client/cli/go/commands/node_add.go
This typo exists in the code as well (but not harmful).
=> Correcting the typo in help text (managment -> management)

apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go, apps/glusterfs/device_entry.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/entry.go, apps/glusterfs/entry_test.go, apps/glusterfs/errors.go, apps/glusterfs/node_entry.go, apps/glusterfs/node_entry_test.go
Heketi now checks to make sure that nodes or devices in nodes
are not added again to the database.  If a node is added with the
same host name, it will return HTTP Status Conflict.  For devices,
device names on the same node will return HTTP Status Conflict.
=> Conflict management support

executors/sshexec/device.go
It has been found that only a 100 volumes could be created
limited by the small size of the metadata in the PV. The
solution is to increase the size of the metadata size to
128MB.  This should allow for (guessing) 12K volumes.
Closes #268
=> Increase the PV Metadata size

main.go
Environment variables can now be set, which
override any settings in the configuration file.
The following env variables are now availble:
HEKETI_USER_KEY
HEKETI_ADMIN_KEY
HEKETI_HTTP_PORT
=> Support for env variables in configuration

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/app_test.go, etc/heketi.json
Now the glusterfs.loglevel can be set in the JSON configuration.
Closes #222
=> Log configuration support

client/cli/go/cmds/root.go
Version was throwing error "Server must be provided"
Version does not require heketi server as it specific to only cli.
=> heketi-cli: version error fixed

apps/glusterfs/models.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, client/cli/go/cmds/topology.go
Just watched a heketi demo and noticed this anomaly with the backup-volfile-server mount option
=> fix:correct usage of backup-volfile-servers mount option

apps/glusterfs/app.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, client/api/go-client/backup.go, client/cli/go/cmds/heketi_storage.go, client/cli/go/cmds/volume.go, extras/docker/unstable/Dockerfile, extras/openshift/template/deploy-heketi-template.json, extras/openshift/template/glusterfs-template.json, pkg/glusterfs/api/types.go, pkg/kubernetes/pv.go
To support storage specific for Heketi, a new API call was added
to backup the database.  Creating Heketi storage uses the
following workflow:
$ heketi-cli setup-openshift-heketi-storage
This does the following:
1. Create a volume called heketidbstorage
2. Download the db and save it as a secret
3. Create endpoints and a service
4. Create a Job to copy the database from the secret
to the volume.
5. Save all into a List object called 'heketi-storage.json'
User would then copy the storage using the list object.
$ oc create -f heketi-storage.json
Closes #208 
=> Support for Heketi Storage in OpenShift

tests/functional/TestOpenShiftSmokeTest/run.sh, tests/functional/lib.sh
When running tests in the CentOS CI with the SCL for Vagrant, 'sudo'
cleans the environment to much. This prevents the run.sh scripts from
executing vagrant (not found in $PATH).
The new _sudo() function in lib.sh replaces the normal 'sudo' calls. The
function checks if the tests are run as root already, in which case it
will skip calling 'sudo'.
A few more details on using Vagrant with CentOS can be found on this
wiki page:
https://wiki.centos.org/SpecialInterestGroup/SCLo/Vagrant
Signed-off-by: Niels de Vos <ndevos@redhat.com>
=> functional-tests: skip sudo when already running as root

client/cli/go/cmds/heketi_storage.go
When using setup-openshift-heketi-storage, the secret was not
being deleted because it was missing the 'deploy-heketi'
label.
Closes #411
=> cli: Label secret

apps/glusterfs/app_volume.go, apps/glusterfs/app_volume_test.go, client/cli/go/cmds/heketi_storage.go, pkg/db/dbvolume.go
Once created, the volume holding the database with the name
in pkg/db/dbvolume.go cannot be deleted.
Closes #403
=> Do not delete the volume with the database

executors/kubeexec/config.go, executors/kubeexec/kubeexec.go, executors/sshexec/brick.go, executors/sshexec/brick_test.go, executors/sshexec/config.go, executors/sshexec/device.go, executors/sshexec/peer.go, executors/sshexec/sshexec.go, executors/sshexec/sshexec_test.go, executors/sshexec/volume.go, extras/docker/gluster/Dockerfile, pkg/utils/ssh/ssh.go, tests/functional/TestManyBricksVolume/config/heketi.json, tests/functional/TestOpenShiftSmokeTest/run.sh, tests/functional/TestOpenShiftSmokeTest/vagrant/roles/cluster/tasks/main.yml, tests/functional/TestSmokeTest/config/heketi.json, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/config/heketi.json, tests/functional/TestVolumeSnapshotBehavior/config/heketi.json
Sudo usage can now be set using the configuration
file heketi.json
There is no need to support sudo in kubeexec,
so we can remove any code that deals with it.
Also update the testing framework to create a
glusterfs container from the repo instead of
using one from Docker hub.
Closes #289
=> Make sudo configurable

executors/kubeexec/kubeexec.go, executors/kubeexec/kubeexec_test.go, executors/sshexec/sshexec.go, executors/sshexec/sshexec_test.go, executors/sshexec/volume.go
Sshexecutor was trying to access private data from
the Kubeexecutor, and so it was nil, which paniced the server.
Instead create an accessor.
Closes #426
=> Fix accessor to configuration

client/cli/go/cmds/volume.go, executors/kubeexec/kubeexec.go, executors/sshexec/config.go, executors/sshexec/peer.go, executors/sshexec/peer_test.go, executors/sshexec/sshexec.go, executors/sshexec/volume.go, pkg/glusterfs/api/types.go
This change allows the administrator to set the maximum
limit of snapshots in the configuration file.
If no limit has been specified, then Heketi will not set
a limit and GlusterFS will use its default value.
Closes #419
=> Allow configuration of snapshot limit

.travis-coverage
Now that the vendor directory is in use, it can confuse
normal utilities.  Use older model to avoide issues.
=> Use older model for coverage

extras/openshift/templates/deploy-heketi-template.json
Adding snapshot macro (default to 14) to deploy heketi template
=> Templates: Deploy heketi snapshot addition

apps/glusterfs/app_volume_test.go, apps/glusterfs/volume_durability_replica.go, apps/glusterfs/volume_durability_test.go, apps/glusterfs/volume_entry_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go
Start the BrickSizeGenerator with the full volume size.
=> [RFC] apps:glusterfs: make it possible to get 1xN volumes (N=#replica)

tests/functional/TestSmokeTest/vagrant/site.yml
=> functional/TestSmokeTest: use 'become' instead of deprecated 'sudo'

client/cli/go/cmds/node.go
Created a new node list command option, which shows all nodes on all
the clusters. It follows the same format as volume list command.
Closes: #405
=> cli: add node list command

apps/glusterfs/app_cluster.go, apps/glusterfs/app_cluster_test.go, apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go, apps/glusterfs/cluster_entry.go, apps/glusterfs/device_entry.go, apps/glusterfs/errors.go, apps/glusterfs/node_entry.go
Allow more useful error messages to be reported and logged when attempting to
delete clusters, nodes, and devices in the glusterfs app. Minor changes also
to simplify and bring consistency to error reporting within related functions.
Closes #355
=> Improve error handling and reporting when deleting items.

apps/glusterfs/app_volume_test.go
This unit test checks to make sure that a volume can be created
on a full cluster by adding more devices.  The test first creates
a cluster, then creates a volume which consumes the entire cluster.
Then it tries to create another which it knows it cannot.  The test
will then add devices to the full cluster, and create the volume
again.
This test is one of three tests needed to satisfy #461.
=> volume: Test creation of volume by adding devices

.travis.yml
Now that version 1.7.1 of Golang is out, we should update our
unit test CI framework to use it.
=> ci: Update travis to Go v1.7.1

tests/functional/TestOpenShiftSmokeTest/vagrant/roles/client/files/hosts.conf, tests/functional/TestOpenShiftSmokeTest/vagrant/roles/client/tasks/main.yml
Needed to change both the openshift-ansible release to 1.3 and the
version of Origin to 1.3.0.
Closes #502
=> ci: Update OpenShift test to use origin 1.3

Makefile, apps/glusterfs/app_volume.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/brick_entry.go, apps/glusterfs/brick_entry_test.go, apps/glusterfs/device_entry.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go, client/cli/go/cmds/volume.go, executors/executor.go, executors/sshexec/brick.go, executors/sshexec/brick_test.go, pkg/glusterfs/api/types.go, tests/functional/TestSmokeTest/tests/heketi_test.go, tests/functional/TestSmokeTest/vagrant/roles/gluster/tasks/main.yml
When a volume is created, it is necessary for the provisioner to
request that the volume has a certain group id.  This group id
would allow the owner of the volume to be able to write to the
GlusterFS volume as long as the user belongs to the requested
group id.
The problem was seen during the access of GlusterFS volumes
from OpenShift containerized applications.  When the volume
was created, it would have a default GID of 0 (root). The
non-privileged containerized application would then be denied
permission to write to the volume due to the fact that it had
a GID other than 0 (root).
With this change, the provisioner can request that the volume
be initialized to a certain GID which matches that of the
containerized application.
Closes #512
=> api: New GID support in VolumeCreate API

apps/glusterfs/volume_entry.go
Move the variable definition away to make the scope more clear.
closes #534
=> apps:glusterfs: fix debug message by using the correct variable

apps/glusterfs/app_volume.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/volume_durability.go, apps/glusterfs/volume_durability_ec.go, apps/glusterfs/volume_durability_replica.go, apps/glusterfs/volume_durability_test.go
This is a global error, not specific to the cluster asked for bricks.
Hence this should be checked globally.
The minimum volume size only depends on the durability type and the minimum configured brick size.
This patchset implements MinVolumeSize() functions in the Durability interface and checks the size of the create request centrally in the sync rest api server code.
@lpabon This is an example where I think the several patches make sense as a patchset.
I could agree to squashing the test additions into the matching code changes.
closes #505 
closes #506
=> correctly report when a requested volume is smaller than min volume size

pkg/glusterfs/api/types.go
GID cannot be reliably returned since the user could have changed the value
to something else.  Instead, omit the gid value in the JSON message
returned to a volume information request.
=> api: Do not add gid information on volume info

tests/functional/run.sh
Add a default timeout of 1hr for each of the functional
tests.  That way, they will not get stuck running forever
in the CI environment.
=> Add timeout to functional tests

apps/glusterfs/app.go, apps/glusterfs/app_test.go
When a path with an illegal id is provided by the caller (something
that does not match the regexp), the Gorilla Mux Router automatically
routed the call to http.NotFoundHandler().  This would be ok for
an API to handle, but the heketi-cli would output information which
was not very human friendly.
Instead, we now provide our own error handler which returns a nicer
error than just "404: Not found".
Closes #539
=> api: Better invalid path error handler

pkg/heketitest/heketitest.go, pkg/heketitest/heketitest_test.go
This enables external Golang projects to easily create Heketi
server for their unit tests.
=> Heketi unit test server for external projects

Makefile, client/cli/go/Makefile
Currently, the go build tool passes -z relro to the linker, which
creates a 'partial' RELRO executable.  Maybe it is a bug in the
GNU linker, but '-z relro' only creates a partial RELRO.  For
a full RELRO to be created the switch '-z now' must also be
passed.
See http://tk-blog.blogspot.com/2009/02/relro-not-so-well-known-memory.html
for more information.
=> build: Support full RELRO

tests/functional/TestKubeSmokeTest/run.sh
New minikube versions pause on errors asking
if the user would mind sending a crash analysis.
This slows down testing.  Instead the tests can
opt out and not block.
=> Opt out of crash analysis in minikube

extras/openshift/templates/glusterfs-template.json
If there are more volumes, it may take some time for the gluster containers to come up.  Increasing the probe value considering we are a storage container.
=> Increase the probe value to 100s

executors/kubeexec/config.go, executors/kubeexec/kubeexec.go, extras/kubernetes/README.md, extras/kubernetes/deploy-heketi-deployment.json, extras/kubernetes/glusterfs-daemonset.json, tests/functional/TestKubeSmokeTest/testHeketiRpc.sh
This change allows Heketi to discover and manage GlusterFS containers which
have been deployed by using a DaemonSet.  The GlusterFS deploy object
has been changed to a GlusterFS daemonset which will need to be installed
by the administrator.  When the administrator wants the DaemonSet to
deploy GlusterFS to a specific node, the administrator can then label
that node with `storagenode=glusterfs`.  This is setup in the DaemonSet
as the `nodeSelector`, which will instruct Kubernetes to deploy the
glusterfs container to the specified node.
When a node is added to Heketi to be managed, just as before, the management
host is the name of the node as displayed in `kubectl get nodes`.  When
Heketi needs to execute a command in a GlusterFS container which has been
deployed by a daemonset, it will …
=> Kubernetes DaemonSet Support

extras/openshift/templates/glusterfs-template.json
Make the /sys/fs/cgroup in template as readOnly. 
Closes : #604
=> Gluster Template: make /sys/fs/cgroup readonly

tests/functional/TestManyBricksVolume/vagrant/site.yml, tests/functional/TestVolumeSnapshotBehavior/vagrant/site.yml
=> tests: use "become" instead of deprecated "sudo: True" in ansible

extras/docker/unstable/Dockerfile
Future releases need to adjust the branch where the image is built from.
Closes #648
=> Dockerfile needs branch setting

apps/glusterfs/allocator_simple_ring.go
While studying the ring allocator code, I found Rebalance() a little
difficult to read/understand. I tried to make it more readable by
introducing a few helper variables etc.
What do others think - is this useful?
=> Make Rebalance() a little easier to read.

apps/glusterfs/app_volume.go, executors/sshexec/volume.go
Working on the code, I found a lot of redundant/superfluous comments that state exactly the obvious thing (what is done right after that). sometimes even falsely (copy and paster error?) Here are two patches to remove these from two code files I worked on...
=> Remove redundant comments

executors/sshexec/device.go
Device Delete should check if the vg directory present or not and if present then remove the directory.
Closes: #402 
=> Remove the VG directory on Device remove

apps/glusterfs/allocator_simple.go, apps/glusterfs/app.go, apps/glusterfs/app_device.go, apps/glusterfs/brick_entry.go, apps/glusterfs/brick_entry_test.go, apps/glusterfs/device_entry.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/errors.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go, client/api/go-client/device.go, client/api/python/heketi/heketi.py, client/cli/go/cmds/device.go, executors/executor.go, executors/mockexec/mock.go, executors/sshexec/volume.go, pkg/glusterfs/api/types.go
Important:
We only support this feature for Replicate and Distribute Replicate Volume.
Refer: https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Managing%20Volumes/#replace-brick
Removes all the brick from the device and start these bricks on other
devices based on allocator. Heal is triggered automatially for replicate volumes
on replace brick.
Allocate and create new brick to replace.
It stops the brick to be replaced, If it is not already down(kill the brick process).
Then gluster replace brick which will replace the brick with new one and also starts the heals.
If other nodes does not have sufficient storage then this command should fail.
Pair-Programmed-With: Mohamed Ashiq Liyazudeen mliyazud@redhat.com
Signed-off-by: Mohamed Ashiq Liyazudeen mliyazud@redhat.com …
=> Remove Device: Used to distribute all the bricks from device to other devices

etc/heketi.json, main.go
This disables the default activation of the backup-to-kube-secret
feature, because the size of a kubernetes secret is limited to
1MB which is too small at least for an uncompressed db with some
entries.
The feature can now be activated by the config variable
"backup_db_to_kube_secret" or with the corresponding environment
variable "HEKETI_BACKUP_DB_TO_KUBE_SECRET".
Resolves #697
=> Introduce switch "backup_db_to_kube_secret", defaulting to false

apps/glusterfs/volume_entry_allocate.go, tests/functional/TestSmokeTest/tests/heketi_test.go
It is possible that a device gets more bricks added to it in a parallel
volume create/expand operation when we are adding a brick to it as part
of device remove opeation. What we save to disk should be the final
state which is consequence of both the operations.
=> fix race between device remove and other ops

apps/glusterfs/node_entry.go, apps/glusterfs/node_entry_test.go, apps/glusterfs/volume_entry_allocate.go, executors/executor.go, executors/mockexec/mock.go, executors/sshexec/peer.go, executors/sshexec/peer_test.go, executors/sshexec/volume.go
GetNode will return the node's manage hostname when called for a
clusterID. This hostname is verifed for the glusterd service to be
running.
This enables device remove to verify the node is up or not and then
choose a different node for replace brick command.
=> Gluster Service check and Remove device node selection

executors/sshexec/sshexec.go, executors/sshexec/sshexec_test.go
sshexec config values to support environmental variable inputs.
We have the same for Kubeexec. This patch will enable to same for sshexec. 
=> sshexec: Environmental variable support for config

client/cli/go/cmds/cluster.go
We have "Id:" as prefix for Id in most of the cli outputs.
Adding it to cluster list output too for easy parsing.
=> have "Id:" as prefix for each cluster id

extras/docker/gluster/Dockerfile
=> Fix bad quotes around /sys/fs/cgroup

apps/glusterfs/app_middleware_test.go, extras/docker/fromsource/heketi-start.sh, extras/docker/rpi/heketi-start.sh, extras/kubernetes/heketi-start.sh, pkg/kubernetes/backupdb.go, pkg/kubernetes/backupdb_test.go
With this change, the database is compressed before storing in
a Kuberntes Secret, which currently has a maximum size of 1Mi.
Because of this limit, it has been found that the maximum number
of devices allowed is 12000. This creates a db which is around 30Mi,
but is compressed down to around 900Ki.
Closes #697
Signed-off-by: Luis Pabón <luis.pabon@coreos.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heketi/heketi/740)
=> Compress database when storing in a K8S Secret

apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go
Earlier, VolumeEntry.gidRequested wasn't being stored in db because
Marshal/UnMarshal methods rely on reflection to get members of a struct
to be stored in db. gidRequested being a unexported member, it wasn't
being stored. VolumeEntry.Info.Gid was not being set to gidRequested,
hence it was always found to be zero.
This patch deletes gidRequested from VolumeEntry(as it was never
exported, it is safe to do so) and uses VolumeEntry.Info.Gid in all the
further operations.
=> save and reuse volume gid in volume entry

extras/docker/fromsource/heketi-start.sh, extras/docker/rpi/heketi-start.sh, extras/kubernetes/heketi-start.sh
Revert cp command typos that were introduced in commit c8cb940c285f2c225d12405870587eeb61916754
The redirect symbol > in the copy command makes the script fail and breaks the dockerimage: heketi/heketi:dev
This pull request fixes this error.
=> Revert command typos 

.gitignore
We can ignore vendor directory as glide install will take care of the directory.
=> Ignore vendor directory from git status

apps/glusterfs/app_volume.go
I was getting `Error: Invalid dispersion combination: 2+1`, but after checking the gluster docs and testing it out, I found out this combination is actually valid and is the one I would like to use in my 3-node cluster.
=> Allow disperse to be 2+1

Makefile
The heketi sources are not tracked in the Makefile's
dependencies. So only by making the heketi target
phony we can ensure that heketi gets rebuilt when
any sources have changed.
=> Build: make sure heketi is always built.

apps/glusterfs/app_volume_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, client/cli/go/cmds/volume.go, executors/executor.go, executors/sshexec/volume.go, pkg/glusterfs/api/types.go, tests/functional/TestSmokeTest/tests/heketi_test.go
At present there is no method to provide volume options via
heketi commandline or via api client. With this patch we provide
an option to user for specifying various volume options.
For eg#:
'
$ heketi-cli volume create --size=100 --durability=none --options="performance.rda-cache-limit 10MB","performance.nl-cache-positive-entry no"
'
Issue ##711
Signed-off-by: Mohammed Ashiq mliyazud@redhat.com
Signed-off-by: Humble Chirammal hchiramm@redhat.com
=> Set Gluster Volume options based on user input.

client/cli/go/cmds/root.go
if `HEKETI_CLI_SERVER` is not set, make `http://localhost:8080` as the default one
=> fix/go-cli: set default HEKETI_CLI_SERVER

apps/glusterfs/app.go, apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, client/api/go-client/client_test.go, client/api/go-client/device.go, client/api/python/heketi/heketi.py, client/api/python/test/unit/test_client.py, client/cli/go/cmds/device.go, executors/executor.go, executors/mockexec/mock.go, executors/sshexec/device.go
Hi. This PR adds a new REST API method `resync` that helps to update free disk space on device after increasing the size of virtual disk. See issue #756
Usage:
```
$ heketi-cli device resync id
```
=> Device resync API to update free disk space after increasing the size of disk

doc/man/heketi-cli.8
heketi-cli volume create mentions option "--cluster", but
it must be "--clusters" (plural).
Resolves #823
=> Fix typo in manpage of heketi-cli

client/cli/go/cmds/device.go, client/cli/go/cmds/node.go
Signed-off-by: mliyazud <mliyazud@redhat.com>
=> Change failed to removed in cli

apps/glusterfs/app_volume_test.go, apps/glusterfs/volume_durability.go, apps/glusterfs/volume_durability_ec.go, apps/glusterfs/volume_durability_none.go, apps/glusterfs/volume_durability_replica.go, apps/glusterfs/volume_durability_test.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go, executors/executor.go, executors/mockexec/mock.go, executors/sshexec/volume.go
The conditions to be considered are
1. If the brick to be replaced is source for some files, don't proceed
2. We kill the brick to be replaced, if that would make the replica set
lose quorum, don't proceed.
This has a side effect that remove device won't work on volumes which
have replica count 2. Choosing data safety over migration features.
=> check for self heal before replaceBrick

executors/kubeexec/kubeexec.go
Reverts heketi/heketi#778
This option does not work as expected in all the cases and leads to kubeexec timeouts in some cases.
When heketi uses kubeexec to get the list of nodes with gluster labels it fails with timeout. I increased the value to 10000 from 10 and it failed again. Reading the comments on the PR which introduced this feature in kubernetes[1] tells that it needs a corresponding feature in container run time. I have not investigated exactly what change needs to be in container runtime and if it exists, however it is for sure that with timeout set, heketi is unable to perform a kubeexec operation at all.
[1] kubernetes/kubernetes#33366
=> Revert "implement timeout for kubeexec"

apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go
This is fix for a crash in SetState when a null node entry is passed.
=> return if unable to retrieve entry from db

tests/functional/run.sh
This is totally unsafe to run in an environment that I use. Okay, for
travis, but not here. This should fix it, since this is already in
travis.
=> tests: Make tests safe for personal machines

.gitignore
This is a useful tool to have in your project path and it is almost
certainly different per-user. Let's ignore it in git.
=> git: Add .envrc ignore

tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go
This makes it easier to debug a problem.
=> test:functional: print errors for asserts in TestVolumeSnapshotBehavior

Makefile
so as not to remove the results of the subsequent dist
runs for various architectures...
=> build: don't do deps-tarball in dist but in release

.travis.yml, Makefile, client/cli/go/Makefile
This fixes cross-compilation and thereby "make release"
by only conditionally using caching (go build -i instead of go build).
=> Fix crosscompile

doc/README.md, doc/api/api.md, doc/troubleshooting.md
Begin importing some of the Heketi documentation from the wiki
on github into the repo's doc dir. Start with the API and
troubleshooting pages since they are simple and standalone.
This also includes a doc/ dir level stub README.md.
=> doc: begin importing some docs from the github wiki

doc/README.md, doc/admin/install-kubernetes.md, doc/admin/install-openshift.md, doc/admin/install-standalone.md, doc/admin/readme.md, doc/admin/server.md, doc/admin/topology.md, doc/admin/volume.md
First commit brings the files in, mostly as-is, but with file name simplifications.
Second commit cleans up broken links that I could find.
=> Import administrative docs from wiki

.gitignore
Fixing error in #864, updating the gitignore so it can't happen again.
=> Remove erroneously committed binary, update gitignore.

Makefile, test.sh, tests/001-testtest.sh, tests/100-gotest.sh
Implements changes for issue #887 
Adds code to the "framework" script for running individual tests scripts under the tests dir. Moves go test invocation to a test script.
Starting off small with many opportunities for improvement. :-)
=> Build out support for running short tests scripts in tests dir

.gitignore, Makefile, test.sh, tests/100-gotest.sh
These changes:
* clean up some naming
* add coverage support to the test runner and gotests script which tries to mimic the behavior of .travis-coverage script in generating a coverage summary in addition to being able to generate coverage html files
* clean up generated files
* add .gitignore rules for generated files
=> add coverage tooling to test scripts

doc/admin/server.md, doc/admin/topology.md, doc/admin/volume.md, doc/api/api.md, doc/troubleshooting.md
The included changes are intended to clean up links so that they are not broken and point to the internal documentation when possible. It also includes some small wording improvements.
=> Clean-ups for recently imported doc files

doc/README.md, doc/contributing.md
Add the start of a contributing doc with the goal of laying
out the basics of what a new contributor needs to know about
the project. It is heavily based on the wiki page
"Development Guide" but modified for what I hope is clarity
and organization. Some of my opinions may have leaked in too.
Having just gone through the process of getting my first
contributions into the project I hope the value judgements
I made in editing the doc are worthwhile. :-)
Initially, I planned on having a third section with
basic recommendations (dos & donts) but I couldn't think
of more than two items and they already overlapped
with previous sections (writing clear commit messages
and adding tests).
However if we want to add a section like this to the doc
I'd be happy to hear the team's thoughts and collect …
=> doc: add an initial contributing document

Makefile, tests/functional/Makefile
This will allow us to remove the special knowledge about how to run the functional tests from the centos-ci integration at https://github.com/gluster/glusterfs-patch-acceptance-tests
=> Add make target for functional tests

.travis-coverage, .travis.yml, tests/001-testtest.sh, tests/030-govet.sh, tests/100-gotest.sh
The following changes:
* Reduce the travis coverage script to only reporting coverage to coveralls service
* take the last "special" travis task and converts it into a test script (go vet)
* Convert travis.yml to use the makefile/test suite
Two things I thought about doing but did not:
* Rename/move the travis coverage script to something more discover-able
* Handle the "go fmt" step as we are already discussing that stuff in another PR.
Let me know if we feel these are things we ought to do and if we should update this PR or just do a follow-on one.
=> switch travis toolchain to call test suite

doc/admin/maintenance.md, doc/admin/readme.md
There was a cluster wiki page that was not linked from the
top level administration pages on the original wiki so
it was not converted to a doc. This change brings it over and
cleans it up, mostly for grammar and readability but not
technical content.
=> doc: convert last admin wiki page to doc file

README.md
Now that we have documentation in the doc/ dir we should
point at it rather than the (defunct) wiki content.
The downloads link to the install page didn't make any sense either
so it now points at the github releases page.
=> doc: point the project readme at the docs & not the wiki

README.md
No active contributors to the Heketi project appear to use gitter.im
regularly and traffic there is even lower than the official IRC
channel and mailing list. Drop the badge from the README.md file
to quietly encourage people to use IRC/mailing lists (or
just the normal github issues/PR tools).
=> readme: remove gitter tag from README.md

executors/sshexec/block_volume.go
G is interpreted by gluster-block as GiB.
So be more explicit about it.
=> executor:block: explicitly use GiB in gluster-block volume create

client/cli/go/cmds/block_volume.go, client/cli/go/cmds/volume.go, doc/admin/volume.md, doc/api/api.md, doc/man/heketi-cli.8, doc/troubleshooting.md, pkg/glusterfs/api/types.go
Be more precise of what unit of storage we actually use.
GB is interpreted as (1000)^3 by many people.
Resolves: #915
=> Improve mentions of GB to state GiB

client/cli/go/cmds/topology.go
This shows the hostnames, both manage and storage as an array because
they are arrays. This changes cli format a little bit but we never
guaranteed cli output backward compatibility.
=> show all hostnames of node in topology info

doc/admin/install-kubernetes.md, extras/kubernetes/glusterfs-daemonset.json, extras/kubernetes/heketi-bootstrap.json, extras/kubernetes/heketi.json, extras/kubernetes/topology-sample.json
The install doc for kubernetes was out of date/wrong in various regards. This change improves the document so that it is more correct, more readable and has better wording.
One should now be able to run through the steps and have a working example/test environment using Heketi & Gluster under Kubrnetes.
If @jarrpa has some time to review this in addition to the usual folks, I'd appreciate it as it does overlap with gluster-kubernetes some. My aim here is to do a basic set up so people can see how heketi interacts with kubernetes and the gluster containers, not redo the stuff in g-k! :-)
=> generally improve the kubernetes install admin doc

extras/docker/fromsource/Dockerfile
It appears that in f27 make has become a dependency of dnf.
The RUN line in the dockerfile was trying to remove make causing
dnf to exit nonzero and failing the build.
I broke up some of the multi-action lines so that its clearer
what steps are being taken. I also kept the instruction to
install make but combined it with the existing dnf install
line. Finally, I removed the -q from some of the dnf calls
as it was also supressing error output making the failure
very mysterious.
=> extras: fix fromsource Dockerfile for current fedora (fix #923)

extras/docker/fromsource/Dockerfile
This is backport of Dockerfile changes made in #925 to fix #923.
Latest tag of heketi container points to images made from release 5
branch and if not fixed, next push to release 5 will fail to build
docker image.
=>  dockerfile: don't uninstall make; dnf requires it

apps/glusterfs/volume_entry.go
The bricks have been given a path in the CreateBricks
function, but this is not yet stored in the DB. Store it.
This will reduce the chance of seeing invalid brick entries
without a path.
Note this is a temporary fix, since we're about to change
the way this code works.
Pair-Programmed-With: Raghavendra Talur <rtalur@redhat.com>
=> app:glusterfs:volume_entry: save bricks to db after creation

apps/glusterfs/app_block_volume_test.go
=> app: use heketi/heketi/pkg/utils instead of heketi/utils

extras/kubernetes/README.md
Point to gluster-kubernetes for the artifacts of kubernetes and openshift which is required for deployment.
Closes: #748
=> Update README.md to point to gluster-kubernetes.

apps/glusterfs/brick_entry.go, executors/executor.go, executors/sshexec/brick.go, executors/sshexec/brick_test.go, executors/sshexec/device.go, executors/sshexec/sshexec.go, pkg/utils/paths.go, pkg/utils/paths_test.go
Traditionally, Heketi has been letting the executor decide where
in the filesystem bricks were being mounted. In an effort to remove
state from the executor we move the logic for determining where these paths are to their own file and move state out of the executor and into the BrickRequest.
=> executors: predetermine the brick paths

apps/glusterfs/app.go, apps/glusterfs/app_block_volume.go, apps/glusterfs/app_block_volume_test.go, apps/glusterfs/app_cluster.go, apps/glusterfs/app_cluster_test.go, apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go, apps/glusterfs/app_volume.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/block_volume_entry_test.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/node_entry_test.go, apps/glusterfs/volume_entry_test.go
Before this series the app constructing the allocator once and persisting it across the lifetime of the heketi process. This series transitions the app to dynamically creating the allocator on request. A few hooks are also added to support temporarily persisting a custom allocator for tests.
=> apps: change app to dynamically construct allocator

tests/functional/TestManyBricksVolume/vagrant/up.sh, tests/functional/TestSmokeTest/vagrant/up.sh, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/up.sh, tests/functional/TestVolumeSnapshotBehavior/vagrant/up.sh
Add boilerplate to the various up.sh scripts to always exit on first
failure.
=> tests: fail faster on vagrant errors

client/cli/go/cmds/cluster.go
Probably a copy-and-paste error
=> heketi-cli: remove a wrong comment

apps/glusterfs/volume_entry_test.go
The patch that introduced TestVolumeEntryNoMatchingFlags and
TestVolumeEntryMissingFlags was written before the patch that
refactored the allocator code for lazy initialization.
But they were merged almost at the same time. Since we don't
trigger CI runs after rebasing before merging, this error
got unnoticed until CI was run after merge...
=> apps:glusterfs: fix VolumeEntry Flags tests after Allocator patches

executors/cmdexec/cmdexec.go, executors/cmdexec/config.go, executors/kubeexec/config.go, executors/kubeexec/kubeexec.go, executors/kubeexec/kubeexec_test.go, executors/sshexec/config.go, executors/sshexec/sshexec_test.go
Remove some outdated references to sshexec and refactor the common config from sshexec into cmdexec.
=> Some further cleanups after introduction of CmdExec

pkg/utils/bodystring_test.go
Add some unit tests for functions in bodystring.go. This gets us up to around test 90% coverage on all of utils.
(From the basement of old commits)
=> utils: add test file for bodystring

tests/functional/TestManyBricksVolume/tests/heketi_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go
This change mechanically updates a bunch of assert statements under the
functional tests, so that the tests stop being so coy about what the
error condition was.
=> tests: mechanically update a bunch of asserts to show what the error was

apps/glusterfs/allocator_mock.go, apps/glusterfs/allocator_simple.go, apps/glusterfs/app_middleware_test.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/block_volume_entry_create.go, apps/glusterfs/brick_create.go, apps/glusterfs/brick_entry.go, apps/glusterfs/device_entry.go, apps/glusterfs/node_entry.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_create.go, pkg/db/wrap.go, pkg/db/wrap_test.go, pkg/kubernetes/backupdb.go
As part of the effort to untangle db write operations and command execution I found it difficult to incrementally refactor code that might be called in two or more code-paths. I might want to be able to call a function within an existing DB transaction or standalone. These change allow us to:
a) provide clean interface based function arguments, abstracting away the exact database object in use
b) provide wrapper objects that let us build our own hooks on top of boltdb behavior without needing changes to bolt and encapsulating existing transactions in mock db interface objects
=> support database abstraction and encapsulation

apps/glusterfs/brick_entry.go, executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, pkg/utils/paths.go, pkg/utils/paths_test.go
As a followup to PR #955, this series of changes prepares the executor to accept the brick path, rather than the brick mount-point (path). It then moves the origination of the path to when the brick entry is first created and uses that path for all subsequent operations (with an extra check left in the code intentionally since the lack of it was biting me hard during testing).
=> predetermine brick path on brick db entries

apps/glusterfs/app_device.go
We don't update the allocator on adding/removing devices anymore.
The variable was declared explicitly, hence the compiler did not
complain about unused variable.
=> remove dead code

apps/glusterfs/node_entry_test.go, client/api/go-client/client_test.go
The previous methods were either non-functional when using the fake
uuid generator or a bit more complex than needed for simple unit
test fake-data generation. Units test pass with these full-length ids.
=> tests: just use full length "uuids" instead of truncating them

tests/functional/TestManyBricksVolume/vagrant/Vagrantfile, tests/functional/TestSmokeTest/vagrant/Vagrantfile, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/Vagrantfile, tests/functional/TestVolumeSnapshotBehavior/vagrant/Vagrantfile
Functional tests sometimes error out with error "virDomainCreateWithFlags
failed: the CPU is incompatible with host CPU: Host CPU does not provide
required features: svm". Using cpu_mode='host-passthrough' solves the
problem by disabling cpu emulation and using host cpu in passthrough
mode.
=> fix functional test errors due to vagrant-libvirt

apps/glusterfs/app.go, apps/glusterfs/app_db.go, apps/glusterfs/dbcommon.go
Create a single common function for setting up the buckets in the db. This way we don't have to change multiple places in the code if we add a new bucket. This also starts a new file where we can add more common db related stuff.
=> apps: make a common bucket init function

apps/glusterfs/allocator.go, apps/glusterfs/allocator_simple.go, apps/glusterfs/allocator_simple_ring.go, apps/glusterfs/allocator_simple_ring_test.go, apps/glusterfs/allocator_simple_test.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_node_test.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/node_entry_test.go
This patchset removes the unused removeFoo and hasBar methods and makes the AddCluster and AddDevice methods private (removes them from the allocator interface). 
The result is that the GetNodes method is now the only method in the allocator interface.
=> Further cleanup simple allocator code

executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, executors/cmdexec/volume.go, pkg/utils/ssh/ssh.go
ssh executor starts bash with sudo if useSudo is set to true. Instead,
if only the command is executed with sudo permissions it will allow
admins to restrict sudo access using visudo.
Closes #958
=> sshexec: restrict sudo to required commands

apps/glusterfs/app_block_volume.go, apps/glusterfs/app_cluster.go, apps/glusterfs/app_volume.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/listing.go, apps/glusterfs/listing_test.go, apps/glusterfs/volume_entry.go
Add the initial support for hiding certain items from api requests. Specifically, it adds the ability to hide volumes from the volume list, volume info, and cluster info requests. Nothing is actually hidden yet, this is just the framework.
=> apps: add initial support for hiding certain items from apis

apps/glusterfs/app_db.go, apps/glusterfs/volume_durability_ec.go, apps/glusterfs/volume_durability_none.go, apps/glusterfs/volume_durability_replica.go, apps/glusterfs/volume_entry.go
Remove duplication in code by moving gob registration to more logical
place.
=> register types with gob during init

apps/glusterfs/app_cluster_test.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_middleware_test.go, apps/glusterfs/app_node_test.go, apps/glusterfs/app_volume_test.go
Some tests were disabling logs and some were not. Based on the
discussion in #792, changing everywhere to default logging.
As per https://github.com/golang/go/issues/21461, the logs won't
pollute the output if all tests pass.
If a test fails then all logs from the package are shown. This is
something which can be fixed later. It would be useful to limit logs of
that particular test instead of package.
=> tests: make logging in unit tests consistent

apps/glusterfs/app.go, apps/glusterfs/app_db.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/brick_entry.go, apps/glusterfs/dbcommon.go, apps/glusterfs/listing.go, apps/glusterfs/pendingop.go, apps/glusterfs/pendingop_entry.go, apps/glusterfs/volume_entry.go
Depends on pr #1026 atm.
This is a cleaned up version of what's in my untangle3a branch with regards to defining the data structures and db entries for pending operations.
I have tests for the patch "add basic support for db import/export of pending op entries" but those tests depend on implementation of volume create operation code in the other branch so I left it out for now.
=> apps: add pending operations support

apps/glusterfs/app.go, apps/glusterfs/app_block_volume.go, apps/glusterfs/app_block_volume_test.go, apps/glusterfs/app_test.go, apps/glusterfs/app_volume.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/brick_create.go, apps/glusterfs/dbexamples.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go, tests/300-db-import-export.sh, tests/functional/TestDbExportImport/dbexamples_test.go
This PR is the most current form of the work that we've been collaborating on for the past few weeks. It is, unfortunately, rather large but there are a fair number of dependencies to untangle within the changes to break it up and we've been at this long enough, I think.
In short, this series of changes prepares the volume, brick, & block volume entries by breaking up some of the monolithic functions for Create/Expand/Delete. It adds the concept of an Operation which is a type used to manage a large change, such as a Volume Create. Each Operation has functions that implement the operation's phases: Build, Exec, Finalize, and Rollback. Each function attempts to depend only on the minimal set of subsystems as possible. For example, only Build requires the allocator.
A second PR, one that …
=> Untangle / Operations Pt. I

apps/glusterfs/device_entry.go, apps/glusterfs/listing.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, apps/glusterfs/pendingop.go, apps/glusterfs/pendingop_entry.go
This series wraps the action of removing a device (aka marking it failed) in an Operation. There are a couple of points worth mentioning for when this is being reviewed:
- The Operation abstraction did not fit great around the brick replace part of device remove. Thus, for now, the operation actually needs to use the allocator in more than just the Build function and takes it in the New... function.
- If the device has no bricks and can be updated immediately, it will set everything in the Build transaction, skip creating the pending operation and Exec and Finalize act as no-ops.
- Working on nodes was deferred for now. As each device w/in a node is removed an operation will be created but there is no overall operation for nodes. Similarly, the operation is left as an implementation …
=> Untangle Pt. II - Device remove operation

apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Depends on pr #1038 
This PR adds a few final test cases and makes delete volume and delete block volume operations clean up the pending operation metadata on failure. The overall operation still fails but no lingering pending operation will be left in the DB.
=> Untangle Pt. II - Final cleanups

apps/glusterfs/operations.go
=> apps:glusterfs: use View instead of Update in DeviceRemoveOperation.Exec

apps/glusterfs/app.go, apps/glusterfs/app_db.go, apps/glusterfs/dbcommon.go, tests/300-db-import-export.sh
Add a "UUID" to track the db generation. A db generation starts when the db is first populated or upgraded. It should be reset when the db is manually modified (yet to come).
This series add the DB generation attribute to the db on create or upgrade, as well as generating a new ID on db import.
=> Add DB generation IDs

apps/glusterfs/app_db.go, apps/glusterfs/pendingop_entry.go, tests/300-db-import-export.sh
This series enables the db feature flag for pending operations and uses that to enable or disable exporting pending operations. Checks for other buckets not present in Heketi 4.x are performed to enable or disable exporting the dbattributes and block volume buckets.
=> Support exporting pre-6x heketi db

apps/glusterfs/volume_entry_allocate.go
This is a prep work for upcoming change to the allocator.
It makes allocateBricks() a little easier to digest.
And mainly it changes the code to use a single transaction around all loops.
This will later allow us to change GetNodes to dynamically load the ring from the db via the transaction.
=> Refactor allocate bricks

apps/glusterfs/allocator.go, apps/glusterfs/allocator_simple.go, apps/glusterfs/allocator_simple_test.go, apps/glusterfs/app.go, apps/glusterfs/volume_entry_allocate.go
Let the allocator only load the ring from the DB in GetNodes().
This makes sure the allocator is always up to date when using it.
=> Rework allocator initialization

tests/100-compile-functest-go.sh
Add a test to verify that the Go code used for the functional
tests can be compiled. This should help find some issues with the
functional test code before the functional tests are run.
=> tests: add a check that functional test go code compiles

Makefile, client/cli/go/Makefile
A variable for the go binary was already defined in the Makefile.
Make it available to all lines that use the go binary, and use it
consistently throughout the makefile.
=> makefile: consistently use defined GO variable

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/app_test.go, main.go
This series aims to improve the behavior of the server w.r.t. starting up and having existing pending operations entries in the db from a previous instance of the server. This means the operation was previously in progress and the db may not be consistent with what's on gluster.
First change makes it so there's no panic externally visible. The server just exits non-zero.
Then we add a way for users to force Heketi to start even when these items are in the db. This isn't clean but exists for the "I don't care, just start it, I'll deal with the problems later". Hopefully, they will try to deal with the problems later.
=> control behavior of refusing to start with stale pending operation db entries

apps/glusterfs/allocator.go, apps/glusterfs/allocator_simple.go, apps/glusterfs/allocator_simple_test.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/volume_entry_allocate.go
This change drops the use of an error channel for a regular error, as well as simplifying the defers for the device channel. See commits for details.
=> apps: clean up the Allocator interface a little

apps/glusterfs/app.go, apps/glusterfs/app_config.go
Some of the env vars were being read inside function that loads config
from file. Moved everything to one function. Also moved the function
call earlier in the stack to ensure all operations refer to updated
config from environment vars.
=> apps/glusterfs: read all env var in the same place

apps/glusterfs/app.go
Earlier, setting the env var to anything would result in true. We
should rather parse it as bool allowing one to set it to "false".
=> allow setting HEKETI_IGNORE_STALE_OPERATIONS to false

docs/troubleshooting.md
To better explain what can be done when Heketi refuses to start due to stale pending operation entries in the db.  (Until we support handing them in an automated way)
=> start a troubleshooting block for not starting on stale pending ops

apps/glusterfs/brick_allocate.go, apps/glusterfs/volume_entry_allocate.go
These changes add new brick and device types to brick_allocate.go, and tries to use them to better organize some of the code within. If it seems like a lot of change for little benefit, the expectation is this approach will become more fundamental and useful in future series.
=> apps: add brick and device sets to brick allocation functions

apps/glusterfs/allocator_simple.go, apps/glusterfs/allocator_simple_test.go
This is a continuation of the work begun in PR #1078.
It takes the patch from that PR and further simplifies and cleans up the code in simple_allocator.go.
Now the ring really only exists as stack variables below GetNodes.
=> Cleanup allocator more

apps/glusterfs/app.go
This is based on PR #1082.
It takes the changes further and removes SetAllocator and ClearAllocator and merges Allocator() with newAllocator().
=> Cleanup allocator even more

apps/glusterfs/brick_allocate.go, apps/glusterfs/volume_entry_allocate.go
This (long) series breaks up some of the code within the replaceBrickInVolume function in order to better prepare it for upcoming alternate allocation approaches. It also serves somewhat as a light disentangling of some of the db and allocation logic from the system probes and exec activity.
=> apps: heavily refactor code where the allocator and replace bricks in volume func interact

apps/glusterfs/app.go, apps/glusterfs/app_block_volume_test.go, apps/glusterfs/app_device.go, apps/glusterfs/app_node.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/block_volume_entry_test.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/dbcommon_test.go, apps/glusterfs/dbexamples.go, apps/glusterfs/device_entry.go, apps/glusterfs/device_entry_test.go, apps/glusterfs/listing_test.go, apps/glusterfs/node_entry.go, apps/glusterfs/node_entry_test.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go
This allows to remove App.Allocator() altogether.
It makes the allocator config setting useless.
based on #1086
=> instantiate simple allocator directly where needed

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations_test.go
In the move to operations, the check for the
CreateBlockHostingVolumes setting was somehow
dropped accidentially. Re-introduce it.
Fixes #1092
=> apps: deny creation of block-hosting volumes if disabled.

.travis.yml
OPTIONS="-race" has no effect any more.
This was a leftover from earlier cleanup work.
So remove it and rather do coverage on all
go versions for now.
Happy reviewing.
=> travis: Do coverage on all go versions

tests/functional/README.md, tests/functional/lib.sh
It can be inconvenient or downright wrong to always use sudo in
the functional tests, it depends on the local environment.
Add a new environment variable to allow all steps to run
as the current user.
=> tests: add an environment var to disable sudo in functional tests

docs/admin/install-openshift.md
The openshift install doc was long and out of date. This change converts
the document into pointers to other docs, primarily openshift-ansible.
=> doc: minimize content in openshift install doc

apps/glusterfs/device_entry.go, apps/glusterfs/listing.go, apps/glusterfs/operations_test.go
The existing check for pending operations on bricks was missing
any non-brick operations on the device, specifically other
existing pending device remove operations. Add a check and a
test for that condition.
=> apps: look for existing brick remove ops and fail gracefully if so

apps/glusterfs/allocator_simple.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/brick_allocate_test.go, apps/glusterfs/placer.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go
This PR defines interfaces for a common Brick Placer that sits between the volume management code and the traditional allocator to abstract out the action of finding devices for bricks. This will be needed for future arbiter work. It also makes a nice clean boundary between the placement (allocation) logic and the rest of the code.
I'm marking it RFC because I think this calls for a little discussion before merging, as this is a new "design." Also see notes below:
The functions that implement the placer logic are only slightly changed from their earlier versions. There is more room for refactoring but I figured I could wait until some of the real arbiter work lands to see what's common and what's not.
Everything is kind of crammed into brick_allocate.go. I think I want to break it up but …
=> New brick placer interface and standard implementation

apps/glusterfs/brick_allocate.go, apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go, apps/glusterfs/placer_volume.go, apps/glusterfs/volume_entry_allocate.go
The first step towards supporting arbiter volumes. It builds upon the changes in PR #1103 and that PR should be merged first.
Currently, this PR is meant as a preview of the first parts of arbiter support. It is intended to give to complain about things early. Currently, this arbiter brick placer is only unit tested and is not used anywhere else in the code. At the very least we need to be able to "know" a volume is an arbiter volume and also make executor changes. We can discuss if those should be in this PR or a later one.
=> Arbiter brick placer

apps/glusterfs/placer_volume.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, executors/cmdexec/volume.go, executors/executor.go, tests/functional/TestSmokeTest/tests/arbiter_test.go
This series builds on the changes in PR #1105 and that series should be merged first.
This series adds initial support for creating and managing arbiter volumes. The core changes are the hooks that causes Heketi to select the arbiter brick placer and to request an arbiter volume from gluster. Additionally, a new function test subdir for arbiter tests is added with some simple tests for arbiter volume create and device remove (brick replace).
The key name used for the "virtual" gluster option is intentionally ugly. We never finished discussing the api changes / naming in the design PR, so I picked something funky on purpose.
As discussed offline this change does nothing to try and dedicate devices for either data or arbiter bricks. That will be done later in a separate PR.
=> Initial support for creating and managing arbiter volumes

tests/100-compile-functest-go.sh
We recently added a script to compile the functional test go code as
a faster (and more frequently run) sanity check. However, the
go command line tool defaults to writing a <pkg>.test binary when
asked to compile test code. We tell the go tool to write the result
to /dev/null so we don't generate unwanted artifacts any more.
=> tests: don't write files when running functional test compile check

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Prior to this fix, the block hosting volume could select a pending files volume (block hosting volume) by use for a new block volume. This behavior was invalid because the pending block hosting volume may not be ready for use or still fail in it's own creation.
The system should only use fully created files volumes for hosting block volumes.
Note that there were two underlying issues:
1. The block volume create code would consider placing the new block volume on a pending files volume.
2.  When file volumes were being created as part of a new block volume, the code was incorrectly failing to update the volume's pending status in the db (it was saving the block volume twice instead).
The first change is a unit test that reveals the issue. Subsequent changes fix the above issues and allow …
=> Fix invalid selection of a pending volume to host block volume

docs/design/snapshot.md
It is possible to pass a "description" when a snapshot is created. But
this is not useful for cloning a volume from an other volume. The
temporary snapshot (that could have a description) will be removed as
part of the volume clone procedure.
The "description" argument was likely introduced by a bad copy/paste.
=> design: remove "description" argument for volume cloning

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
This fixes a panic encountered during the rollback of the block volume create operation if the another function had not already set the BlockVolumeEntry object's cluster id.
Fixes #1102
Now, Block volumes entries are always updated with the cluster id during the Build step.
=> fix panic during rollback of blockvolume create

client/cli/go/cmds/node.go
While working on the volume cloning feature, it is useful to know how
many bricks are located on a device. Extending the 'node info' command
in the heketi-cli makes it easier to find devices where the cloned
volumes (bricks get cloned on the same device) are placed.
Example:
$ hekti-cli node info 86736cdb27764fd767ae8a4f566deffa
...
Devices:
Id:29d625b5ca3c51a50c03795fabc2446f   Name:/dev/vdc            State:online    Size (GiB):499     Used (GiB):120     Free (GiB):379     Bricks:3
Id:de13a0e3322f653ae3ec69e991a5e3c2   Name:/dev/vdf            State:online    Size (GiB):499     Used (GiB):32      Free (GiB):467     Bricks:1
Id:e659c56fde5b75ce18e9815457a2558a   Name:/dev/vde            State:online    Size (GiB):499     Used (GiB):308     Free (GiB):191     Bricks:2 …
=> cli: show number of bricks in 'node info' output

apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Build a retry mechanism into RunOperation and AsyncHttpOperation,
such that if the operation fails with an error of type
OperationRetryError and the Operation provides a greater-than-zero
MaxRetries value the operation will be re-run until the
max retries are exceeded or all operation phases succeed.
The operation Rollback method _must_ set all inputs to the operation
back to a state where Build can be safely executed again.
=> apps: add a general operation retry mechanism

apps/glusterfs/app_test.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, apps/glusterfs/pendingop_entry.go
This set of changes adds an internal retry to the volume create operation, based on the previously submitted generic operations retry mechanism. It cleans up a few issues found while testing the rety and adds a specific test for the volume create retry.
This change depends on PR #1056.
I've opted to use a default value of 4 retries. This means a total of 5 tries. In the test itself I upped the retry count to ten because we want to make sure the test always passes and the mock executor doesn't really take any time.
=> Internally retry volume creation

apps/glusterfs/allocator_simple.go, apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/health_cache.go, apps/glusterfs/health_cache_test.go, etc/heketi.json
These changes add a new type that can monitor the health of nodes and cache the results in memory for use by other parts of Heketi. The glusterfs app configures and initializes the node heath monitor cache and starts the monitor (goroutine). Later, the functions used to populate the ring used during brick placement can consult the cache and omit any nodes that known to be down/unhealthy. 
The configuration file must explicitly enable the monitor. We've updated the default configuration file to include this parameter. However, we may need to consider older instances of Heketi running with preexisting configuration files. We may want to discuss enabling the monitor without needing to have it set to true in the config file. If we choose to do that, then we also need to change the behavior of …
=> Add a node health monitor & cache subsystem

apps/glusterfs/app.go, apps/glusterfs/app_config.go, etc/heketi.json, main.go
This change removes the ability to enable or disable the node health
monitor from the heketi config file. Instead, we provide a package
level variable that the glusterfs app uses to determine if the
monitor should be used or not. By default this variable is false thus
all unit tests and other non-server code will not run the monitor.
The server binary does set this variable to true by default thus
enabling the monitor for the heketi server. For debugging purposes
this can be disabled (in the server only) by setting
`HEKETI_DISABLE_HEALTH_MONITOR=true` in the environment.
=> apps: enable the node health monitor by default in server binary

apps/glusterfs/app.go
We would like to perform rebalance by default as it is very difficult to
distinguish missing parameter from set-but-false parameter in json, we
are going to ignore json config. We provide a env method to set it
to false again.
Env is HEKETI_GLUSTERAPP_REBALANCE_ON_EXPANSION
I know it makes the parameter in json config file invalid but IMO this is the only way to get rid of this problem.
=> apps: enable rebalance on expansion by default

apps/glusterfs/operations_test.go, apps/glusterfs/volume_entry.go
When the underlying gluster system is able to create a volume but not start it heketi can get into a weird state. This seems to have been made worse by the recent volume create retry code being able to "spam" many volume create commands in a shorter time period.
This change aims to make rollback more accurately reflect the state of the system and fail in the face of a condition that it can not clean up.
=> Improve create rollback behavior when cleanup fails

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/placer.go, apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go
This PR provides options to change arbiter brick size calculation in heketi. This is needed because as explained below the default in heketi might not work for all use cases. 
Calculation of arbiter brick size is dependent on
* size required for storing metadata for a each file
* maximum number of files that user may need to store on the volume.
We fix the metadata size for each file to 1KiB based on 
* https://gist.github.com/pfactum/e8265ca07f7b19f30bb3
* http://gluster.readthedocs.io/en/latest/Administrator%20Guide/arbiter-volumes-and-quorum/
Hence the only variable that remains is maximum number of files that user may need to store on the volume. This is a little difficult to estimate but can be derived from average file size and volume size. As we already know the volume size, it is …
=> Provide options to change arbiter brick size

apps/glusterfs/app.go, apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/app_node.go, apps/glusterfs/app_node_test.go, apps/glusterfs/device_entry.go, apps/glusterfs/node_entry.go, apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go, apps/glusterfs/tags.go, apps/glusterfs/tags_test.go, client/api/go-client/client_test.go, client/api/go-client/device.go, client/api/go-client/node.go, client/api/python/heketi/__init__.py, client/api/python/heketi/heketi.py, client/api/python/test/unit/test_client.py, client/cli/go/cmds/device.go, client/cli/go/cmds/node.go, client/cli/go/cmds/topology.go, client/cli/go/cmds/utils.go, docs/api/api.md, docs/man/heketi-cli.8, pkg/glusterfs/api/types.go, tests/functional/TestSmokeTest/tests/arbiter_test.go
Tags are short-ish user controlled metadata
that Heketi can choose to interpret but are otherwise free-form. We will be using our first well known tag "arbiter" to control how the system places arbiter bricks.
The following features have been implemented:
* Ability to store and retrieve tags from the node and device entries in the DB.
* Utility file for tags management
* Server API for setting tags on nodes and devices
* Go client api for setting tags on nodes and devices
* heketi-cli subcommands to set and remove tags on nodes and devices
* heketi-cli support for tags within the topology file
* Support for the arbiter tag
* Hooks for the arbiter placer to use the tag
* Functional tests for tags and arbiter tag
=> Add concept of tags to devices and nodes

docs/admin/arbiter.md
Start a overview document for administering the arbiter feature. Currently it explains how to cause heketi to create arbiter volumes and how to control where arbiter bricks are placed with node and device tags.
This doc should only be merged after PR #1129 as it documents feature added by that PR.
=> docs: start an arbiter admin doc

client/cli/go/cmds/heketi_storage.go
This is an only partially serious suggestion triggered by a
comment @jarrpa made a while back.
(see
https://github.com/gluster/gluster-kubernetes/issues/434#issuecomment-366006365
)
Using cobra's aliases feature we no longer have to be embarrassed by
an overly openshift specific command name, but can now refer to it
via much more generic names. In the future we could even swap
the "true" name for one of these fine aliases.
=> cli: support alternative names for setup-openshift-heketi-storage

client/cli/go/heketi-cli.sh, test.sh, tests/300-db-import-export.sh, tests/functional/TestKubeSmokeTest/run.sh, tests/functional/TestKubeSmokeTest/testHeketiMock.sh, tests/functional/TestKubeSmokeTest/testHeketiRpc.sh, tests/functional/run.sh
Recent versions of shellcheck (0.4.7, on fedora 27) fail on various scripts. This PR fixes those scripts, so that the `tests/020-test-shellscripts.sh` test passes again.
Fixes #1151
Only the last patch to the bash-completion script that catches an error of popd or pushd and exits in that case might be slightly controversial. But I think it's ok.
=> Fix shellcheck

apps/glusterfs/app.go
Some heketi config files lack a specific log level and thus
the configuration value is defaulted to the empty string.
If this is passed to the glusterfs app SetLogLevel it produces
an ugly message on start up. Simply treat the empty string
as a no-op.
=> apps: treat an empty string log level name as a no-op

extras/kubernetes/heketi-start.sh
You provide ability to change path of db file in the heketi server configuration file (heketi.json)
```
"glusterfs": {
"_executor_comment": "Execute plugin. Possible choices: mock, kubernetes, ssh",
"executor": "kubernetes",
"_db_comment": "Database file name",
"db": "/var/lib/heketi/heketi.db",
"kubeexec": {
"rebalance_on_expansion": true
},
```
But you don't provide this ability in heketi-start.sh
This small fix gives this ability. In pod spec I can specify environment variable with another path to db file.
For example:
```
HEKETI_DB_PATH=/my/path/to/heketi.db
```
=> Allow pass the database file name via env var to heketi-start.sh

apps/glusterfs/device_entry_test.go, apps/glusterfs/volume_entry_allocate.go
After refactoring to implement the placers the device replace code path
we failed to save the updated storage values on the affected device.
This change is bit ugly but it makes sure that the device is saved
until replace moves to a more transactional/operations based model.
The remainder of the change is a unit test for this condition.
=> apps: update space accounting on device during brick replace

apps/glusterfs/device_entry_test.go, apps/glusterfs/placer_arbiter.go
Due to the (screwy) behavior of the callers the replace code-path must not add the replacement brick to the list of bricks on the device (however it must deduct the brick size from the device and save it). The brick is added to the device later in a different db transaction (oh yeah, more opportunities for out-of-sync) and adding an existing brick to the brick list will panic.
Thus this change updates the arbiter placer such that functions called during the Replace call will not add the brick to the device's list.
=> fix device remove (brick replace) for arbiter volumes 

apps/glusterfs/app.go, apps/glusterfs/app_test.go, docs/admin/server.md, extras/kubernetes/heketi-bootstrap.json, extras/kubernetes/heketi-deployment.json, extras/openshift/templates/deploy-heketi-template.json, extras/openshift/templates/heketi-template.json
It is unfortunate that if we choose to use a different place for the DB,
and if we do the backup-to-kube-secret thing, that we then need to
specify it in two places now. This solution fixs this problem.
Related to: https://github.com/heketi/heketi/pull/1155
=> HEKETI_DB_PATH environment variable overrides the heketi.json setting for the daemon

apps/glusterfs/brick_allocate.go, apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go
Creating the arbiter bricks in reverse order (starting with the 3rd
brick in the brick set and working back to the 1st) means we create the arbiter brick first
and this prevents the data bricks from "blocking" the arbiter brick
being placed on a particular node. This makes placing the
arbiter bricks more reliable.
See [rhbz #1572561](https://bugzilla.redhat.com/show_bug.cgi?id=1572561)
This PR relies on the changes in PR #1171 so that tests can pass. Please review that PR first.
=> create arbiter bricks sets in reverse order

apps/glusterfs/volume_entry_allocate.go
In refactoring the previous replace function the logic around
selecting a node to run commands on was oversimplified in one
area. This change fixes that by plumbing the node selection
through multiple function calls.
Fixes #
This PR relies on the changes in PR #1171 so that tests can pass. Please review that PR first.
=>  apps: fix selection of node for issuing gluster replace command 

docs/admin/arbiter.md
I managed to foul up the option to set the average file size for arbiter brick sizing in three different places in the doc. This patch attempts to fix those mistakes.
=> docs: fix various mistakes spelling out the average file size option

pkg/utils/bodystring.go, pkg/utils/bodystring_test.go
On occasion the heketi-cli returned an empty `Error: ` to the caller.
This is obviously suboptimal, as there is no hint to what could have
gone wrong. The Heketi service itself provides error messages for any
issues it hits. If there are no error messages received by the
heketi-cli, the problem is somewhere else.
It seems that a misconfigured router/proxy in Kubernetes or OpenShift
can cause empty error messages. These routers/proxies will provide a
HTTP status code, so let's display that if there is no message.
Bug: https://bugzilla.redhat.com/1432340
=> utils: improve error reporting if service does not provide a message

apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go
Due to changes introduced in a previous arbiter fix the function
that returns only "real" bricks from a brick set was not
using the correct indexes for the bricks in the brick set and
thus the check in the code for protecting against re-use of a node
within a single brick set was incorrect.
This fix returns the iteration to the previous approach and
checks for "nil bricks" in the loop itself.
=> apps: fix arbiter placer so that nodes do not get reused in a brick set

apps/glusterfs/placer_arbiter.go, apps/glusterfs/placer_arbiter_test.go
The arbiter brick size for a brick set is calculated as
(dataBrickSize)/(averageFileSize). If the data brick is
rather small, and the averageFileSize is rather big, this
can get smaller than the minimum filesystem size of 16MiB
that xfs supports. Hence always use at least 16 MiB for
the arbiter brick.
Note this required to change two of the test cases
slightly: The sizes are actually in KB. The tests use
some fantasy numbers like 800 KiB brick sizes that now
contradict for some checks the new mode of having a
minimum arbiter brick size of 16 MiB.
Fixes: #1181
=> arbiter: fix volume creation with too big average file size

executors/cmdexec/brick.go, executors/cmdexec/brick_test.go
This greately enhances readability.
=> executor: use long options on lvcreate

apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, client/cli/go/cmds/device.go, client/cli/go/cmds/topology.go, client/cli/go/topology-sample.json, docs/api/api.md, docs/man/heketi-cli.8, executors/cmdexec/device.go, executors/executor.go, executors/mockexec/mock.go, extras/kubernetes/topology-sample.json, pkg/glusterfs/api/types.go
Some users are certain that the data on the disks that they add to a node can be destroyed. It can be useful to force adding a device, even if `pvcreate` detects existing data. This PR adds an option to the "device add" API and implements the functionality to provide this feature.
BUG: https://bugzilla.redhat.com/1433614
A short discussion was also held on the heketi-devel list: http://lists.gluster.org/pipermail/heketi-devel/2018-May/000267.html
=> Add an option to destroy data while adding a device to a node

docs/admin/server.md, etc/heketi.json, executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, executors/cmdexec/cmdexec.go, executors/cmdexec/device.go, executors/kubeexec/kubeexec.go, executors/sshexec/sshexec.go, pkg/utils/conv.go, pkg/utils/conv_test.go
With the automation that Heketi provides and the redundancy that Gluster
offers there is no need for the LVM-metadata backups under
/etc/lvm/archive. It is not expected that users have a need for these
archives, and they can take up a considerable amount space on the /
filesystem in active environments.
The heketi.json used by the service daemon can be configured to create
the LVM-metadata archives by setting "backup_lvm_metadata" to true. This
option defaults to false if not set.
BUG: https://bugzilla.redhat.com/1561680
=> executors: do not create backups in /etc/lvm/archive by default

apps/glusterfs/listing.go, apps/glusterfs/listing_test.go
Block volume create operations can create volumes (block hosting volumes) when
the block volume is being created. This means when scanning for
pending volumes we must also consider block volume create operations
as well as volume create operations.
Fixes #1188
=> filter pending block hosting from listings of complete volumes

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/app_test.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/testapp_mock.go, main.go, pkg/heketitest/heketitest.go, server/config/config.go, server/config/config_test.go
This creates a new package "server/config" and locates all the logic around parsing configuration files into this single location. Instead of parsing the configuration file twice we parse the file once and pass the configuration object around.
Using a new package also provides a foundation for future enhancements around configuring the heketi server process.
In order to keep this initial series small it does not tackle re-organizing the environment variables that are spread throughout the codebase. I'm happy to bikeshed the new location but I do think it should be a new package for handling the config loading.
=> consolidate server configuration

docs/man/heketi-cli.8
To avoid looking weird when the arbiter example is added the whole
example section is expanded a little bit. Then an example of
creating an arbiter volume is added.
Fixes [rhbz #1569486](https://bugzilla.redhat.com/show_bug.cgi?id=1569486)
=> manpage: expand example section and add arbiter volume create example

apps/glusterfs/brick_allocate.go, apps/glusterfs/errors.go, apps/glusterfs/operations_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go
This series improves the handling of error messages on volume create by:
1. Adding specific errors for when the cluster has no nodes or none of the nodes have usable devices
2. Adding the ability to capture and report on each cluster's error by aggregating them in a new MultiClusterError type, as opposed to coercing all errors to "No Space"
3. Adds tests for the above
Example output:
```
heketi-cli volume create --size=4
Error: Failed to allocate new volume: Unable to create volume on any cluster:
Cluster 4081998cadcd0c9093f2c2f0fc813430: No nodes in cluster
Cluster a54cc7f2711c1711b8a6aef195681893: No online storage devices in cluster
```
Fixes #712 
Type name and error text wording bike-shedding welcome.
=> Improve error handling on volume create

apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Prevent multiple delete operations on the same volume and prevent
deletes of volumes that are already being worked on by checking
the pending id of the volume and its bricks.
Prevent multiple delete operations on same block volume.
Add a test for 
* deleting the same volume twice
* deleting a volume that is currently being expanded
* deleting the same block volume twice
This fixes part of issue #1189
This is part of the fix for #1189 in that it should prevent certain issues inf the first place. However, it does not deal with the failures in the cleanup code.
=> apps: prevent delete of volumes that are pending

client/api/go-client/client.go, client/api/python/heketi/heketi.py, client/cli/go/cmds/block_volume.go, client/cli/go/cmds/cluster.go, client/cli/go/cmds/db.go, client/cli/go/cmds/device.go, client/cli/go/cmds/heketi_storage.go, client/cli/go/cmds/loglevel.go, client/cli/go/cmds/node.go, client/cli/go/cmds/root.go, client/cli/go/cmds/topology.go, client/cli/go/cmds/utils.go, client/cli/go/cmds/volume.go, tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go, tests/functional/TestEnabledTLS/client_tls_test/serverctl_test.go, tests/functional/TestEnabledTLS/run.sh, tests/functional/TestEnabledTLS/test_tls.py
With pr #1108 now merged Heketi server can now be enabled for TLS/HTTPS. However, if the client APIs need to access an HTTPS secured heketi they may run into issues if the server is using self-signed or non well known CAs. To ease this situation the following changes add the ability to enable or disable verification OR provide cert files to the python client, the go client, and the heketi cli.
Please feel free to bikeshed the cli option names and the user facing variable names if they don't seem clear.
=> Add client side tls configuration

extras/docker/fromsource/Dockerfile
The dockerfile lists Luis as the maintainer. But Luis is no longer working on heketi, so update the dockerfile.
=> Dockerfile: update the Maintainer

extras/docker/fromsource/Dockerfile
This PR improves the dockerfile to name heketi-devel as maintainer, and fix build by installing mercurial.
This is against the release/7 branch.
Since the release/7 branch had a patch to change the maintainer (to /me) but now we have a better master patch, I chose to revert the first patch in release/7 and then do clean cherry-picks from master. Alternatively, if preferred, I can squash the revert and the master-cherry-pick for the maintainer.
=> Release 7: fix dockerfile

extras/docker/centos/.gitignore, extras/docker/centos/Dockerfile, extras/docker/centos/Dockerfile.testing, extras/docker/centos/README.md, extras/docker/centos/cccp.yaml, extras/docker/centos/prepare-build.sh
Add container images for the CentOS Container Registry that is available at https://registry.centos.org/containers/ . The images are built from RPMs that are available from the CentOS Storage SIG.
Currently two flavours are provided:
1. built from the CentOS Storage SIG stable/released repository
2. built from the CentOS Storage SIG testing repository
The description to build the containers for the CentOS Container Registry is available from [the add-gluster-heketi branch](https://github.com/nixpanic/centos-container-index/commit/5476a48b72a4e192318f5301a6da155ca1b93908) in my fork of the [container-index repository](https://github.com/CentOS/container-index). Once this PR has been merged, a PR for the container-index will be created.
=> extras: add heketi containers for the CentOS Registry

apps/glusterfs/brick_entry.go
Currenly, when a cluster lists a volumeid, that does not exist in the db, and when a volume lists a brick id that does not exist in the db, heketi will refuse to start with the upgrade failing. This is unnecessary since those orphan backlinks are actually harmless.  This PR improves the upgrade code to  not fail over these.
=> Fix heketi startup with orphaned cluster->volume and volume-> brick links

apps/glusterfs/cluster_entry.go, apps/glusterfs/device_entry.go, apps/glusterfs/node_entry.go
If the DB has broken links (list of node-ids in the cluster, list of device-ids in the node, list of brick-ids in the device), DeleteBricksWithEmptyPath will fail. This PR lets DeleteBricksWithEmptyPath ignore these harmless links pointing to nowhere, but logging warning messages about them.
=> don't let DeleteBricksWithEmptyPath stumble over broken links in the DB

apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Update the free size in block info on expansion. If a volume is expanded and has a block flag set to true, then we should also update the free size attribute of the volume in blockinfo.
Fixes #1229
=> Update the free size in block info on expansion

apps/glusterfs/brick_create.go, apps/glusterfs/brick_entry.go, apps/glusterfs/volume_entry.go, executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, executors/cmdexec/volume.go, executors/executor.go, pkg/utils/paths.go, tests/functional/TestSmokeTest/tests/delete_test.go
This PR implements the ability to resume deleting partially deleted volumes. It currently involves refactoring various parts of the delete volume path. It also adds support for explicitly tracking the the LV and thinpool name for bricks. Functional tests for normal volumes are included.
Fixes #1220
I still need to add tests for deleting cloned volumes. This is already a big PR so I may do that in a followup pr depending on timing/your opinions.
=> Add support for resumable delete volume

apps/glusterfs/brick_create.go
This fixes the logging ,if brick destroy fails
Fixes: 7da13ee7a43337c8724e3429f69d4192339e5a4a
=> apps: add per-brick log, if brick destroy fails

client/cli/go/cmds/device.go
Previously, output was "Device  updated".
Now it is of the form  "Device <DEVICE-ID> updated".
Fixes #1240
=> heketi-cli: fix output of heketi-cli device resync

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations.go, apps/glusterfs/volume_entry.go
This series fixes problems with block hosting volume free size accounting when the block volume create operation fails and the rollback operation step is run.
The first patch creates a helper receiver function for modifying the free size and asserting that the resulting size is within bounds. This reveals an issue with rollback when running the unit tests. The second patch fixes the workflow in an attempt at a minimally invasive manner.
Fixes [RHBZ#1584123](https://bugzilla.redhat.com/show_bug.cgi?id=1584123)
Are we ok with using the 'godbc' method of asserting the invariants or should we switch to returning an error and adding addtional error handling to these functions?
=> Fix incorrectly updating the block hosting volume free size on rollback

Makefile
Glide needs to fetch a repository from bitbucket.org, which is a Mercurial hosting site. The `hg` executable needs to be available to download the requires pkgs.
If `hg` is not available running `make vendor` fails with the following error:
[WARN] Unable to checkout bitbucket.org/ww/goautoneg
[ERROR] Update failed for bitbucket.org/ww/goautoneg: hg is not installed
[ERROR] Failed to install: hg is not installed
make: *** [Makefile:74: vendor] Error 1
=> build: add a check for mercurial/hg

apps/glusterfs/volume_entry.go
=> Set the "group gluster-block" options when manually creating block-hosting volumes

apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/dbexamples.go, apps/glusterfs/device_entry.go, apps/glusterfs/device_entry_test.go, executors/cmdexec/device.go, executors/executor.go, executors/mockexec/mock.go
Device resync feature currently only fetches the free space and calculates the total and used based on that and data in heketi db. If the device has been resized or if heketi has gone out of sync from back end it is better to update all three attributes.
=> device resync should update total, used and free

middleware/jwt.go
From https://github.com/dgrijalva/jwt-go/pull/139 it is understood
that if the machine where jwt token is generated and/or the machine
where jwt token is verified have any clock skew then there is a
possibility of getting a "Token used before issued" error. Considering
that we also check for expiration with delta of 5 minutes, disabling
iat claim until the patch is merged in jwt.
This PR disables the issued at time claim in jwt. Doing so will stop "token used before issued" errors.
Fixes #646
=> client: disable issued at time claim in jwt

apps/glusterfs/cluster_entry.go, apps/glusterfs/db_operations.go, apps/glusterfs/device_entry.go, apps/glusterfs/node_entry.go
This makes it easier to understand from the logs what's going on, in case of troubleshooting.
=> glusterfs: improve the logging in error path of DeleteBricksWithEmptyPath

apps/glusterfs/db_operations.go
=> glusterfs: add an empty line between functions in db_operations.go

apps/glusterfs/app_block_volume_test.go, apps/glusterfs/block_volume_entry_create.go
Earlier, due to off by one error, we added one host more than ha count in list of hosts provided to gluster-block cli during blockvolume create.
This PR matches number of hosts to ha count parameter.
=> Number of hosts should be equal to ha count 

executors/cmdexec/device.go
If there is an unexpected condition on the vg or pv when
removing a device it is preferable to fail than to allow
the command to prompt for input which will block heketi
"forever" and possibly (due to lvm-level) locking other
commands as well.
Fixes #1244
This ought to have a functional test but due to time limits and the fiddly nature (having to do lvm stuff directly via the test code) I skipped this for now. It may be worthwhile to do a general technical debt issue for adding tests in this general area.
=> executors: prevent (vg|pv)remove commands from prompting

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/block_settings.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/volume_entry.go, etc/heketi.json
Earlier, block hosting volume created in heketi had only "group gluster-block" option set. This PR provides option to edit the set of options that are applied on block hosting volumes. Also, a flag is provided to disable setting of such an option for volumes if required.
As an use-case, one can edit   
block_hosting_volume_options in heketi.json  
or  
HEKETI_BLOCK_HOSTING_VOLUME_OPTIONS env var  
to have "group gluster-block,user.heketi.arbiter true" to have arbiter volumes as block hosting volumes.
Fixes #1224
=> Provide config to control options applied to Block Hosting Volume

client/api/go-client/client.go, client/api/go-client/client_test.go
We are working towards adding throttling to the heketi server. However, to better support cli (and api) users in a throttled world we add the ability for the heketi go api client for retry when throttled.
This series takes a patch from pr #1131 and adapts it so that callers of the api, and internal api functions can use the same calls. It adds the abilty to turn off the retries if desired and to control the various retry related values.
After having tested some of my hacked up server changes against a k8s cluster that does not have client patches applied I feel that having the client wait too long will give a bad behavior esp. since k8s retries again at a higher level. Instead, the retries are more beneficial to the command line client users who might reasonably want to wait a few minutes …
=> go client api: support retries when throttled by server

tests/functional/TestSmokeTest/tests/heketi_test.go, tests/functional/lib.sh
Trying to determine why functional tests are failing on centos ci
=> functional tests: add some debugging stuff

tests/functional/run.sh
Turns out there's more than one level of time out that needs to
be adjusted. Fix it here and print out a specific message if
the test script is timed out.
=> functional tests: discover and fix another level of timeout in test

apps/glusterfs/testapp_mock.go
Some of the tests make a lot of requests at once and throttling has
a huge impact on it (1min vs 4min). So we avoid doing much
throttling at all in the test code.
=> apps: avoid throttling test code much

docs/README.md
Typo on documentation.
"Administration" instead of "Adminstration" on topics menu points
=> typo: Administration instead of Adminstration

apps/glusterfs/app_block_volume_test.go, apps/glusterfs/block_volume_entry_create.go, main.go
When the number of nodes available is greater than the HA count
we want to select a subset of these nodes for use with gluster
block ha support. Previous changes to the code try to select
the ha-count number of healthy nodes from this set but if the
healthy node set was unchanging it would always pick the exact
same nodes.
This change shuffles the list of nodes that is tested for
liveness so different block volumes are distributed across
different nodes, and adds a test for this behavior.
Also in introduces proper seeding for the PRNG.
Fixes (latter half of) rhbz#1595531
Supersedes PR #1281
=> apps: shuffle block-volume ha nodes to avoid relying on same nodes

apps/glusterfs/app_block_volume_test.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, apps/glusterfs/testapp_mock.go, apps/glusterfs/volume_entry.go, pkg/glusterfs/api/types.go
A block-hosting volume created with raw size X can not host block files of accumulated size X because the file system uses a certain small amount of the raw size. But the FreeSpace tracking does currently not take this into account. Hence trying to create a block volume of size X with FreeSize X available on the block hosting volume will fail. 
This PR fixes heketi to always track only 99% of the raw space of a newly created (or expanded) block hosting volume as the available FreeSize.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596018
=> apps:glusterfs: reserve 1% of raw capacity in FreeSpace tracking

apps/glusterfs/app_node.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/volume_entry_create.go
during the node delete in heketi, we remove the node from
heketi management, volume info such as Hosts (which may
contain the deleting node hostname). and we need to
update the backup-volfile-servers and volume mountpoint
(this also may contain the deleting node hostname)
if it's a block hosting volume, we need to
fetch all the block volumes belongs to it,
and update the hosts in those volumes, so that
next block volume creation fetches the new
hosts from the heketi cluster.
Fixes #1274
Fixes #1273
=> apps:glusterfs update volume hosts info during node deletion

apps/glusterfs/app_middleware.go, middleware/jwt.go, middleware/jwt_test.go
This PR implements new claims type and validation function. We need it due to inability of jwt library to handle clock skew.
1. required_claims is embedded in validation function and missing claims error is replaced with unauthorized
2. As claims type has changed from map to struct, claims are now accessed as members and not indexed.
=> middleware: ignore iat claim in jwt

apps/glusterfs/block_volume_entry.go, apps/glusterfs/dbcommon.go, apps/glusterfs/dbcommon_test.go, apps/glusterfs/operations.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go
Change the VolumeEntry's ModifyFreeSize and ModifyReservedSize
functions to return errors instead of panicking. Also plumb
the error handling up to the callers of these functions.
This will prevent wrong values from being saved to the db
without killing the server. The admin of the server can then
stop the server at a later time and repair the db as needed.
=> apps: return errors rather than panic when checking FreeSize bounds

main.go
In case initialization of the app fails, the message
ERROR: Unable to start application
is not very helpful. There might be an actual error that can be displayed. If there is one, it should be logged.
Just a minor improvement while debugging deploying within `minikube`.
=> main: print the error in case starting the app failed

main.go
Seed values that have the same remainder when divided by 2^31-1
generate the same pseudo-random sequence. So there is no need waste
entropy to generate a 64 bit random number.
Also this change removes an unnecessary UTC() call, since UnixNano() ignores the timezone info.
=> apps: don't waste entropy for seeding

client/cli/go/cmds/server.go
This change adds the command `heketi-cli server operations info` that will list a brief summary that counts the operations in various states.
Example:
```
$ ./heketi-cli server operations info
Operation Counts:
Total: 3
In-Flight: 0
New: 0
Stale: 3
```
This command makes introspecting some of the server state easier w/o requiring the user dump the db to figure out if the server is still processing operations.
This change requires the changes provided by PR #1299 because it adds additional states for the operations that we summarize. Please merge that pr first.
=> heketi cli: add "server operations info" command 

pkg/utils/ssh/ssh.go
Within the ssh utils package some error paths were simply printing to stdout.
Instead of just blatting some errors out to stdout (not stderr) we instead we use the nice logger that was already in the package.
=> utils: use logger to capture ssh key setup errors

client/api/go-client/client_test.go, pkg/glusterfs/api/types.go
Adjust regex to allow device paths with colons. Colons may appear
in paths such as "/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0"
and thus are valid use cases.
Fixes #1246
=>  api: support colon chars in device paths

client/api/go-client/admin.go, client/api/go-client/client_test.go, client/cli/go/cmds/server.go, main.go, pkg/glusterfs/api/types.go, server/admin/http.go, server/admin/reset.go, server/admin/state.go, tests/functional/TestSmokeTest/tests/admin_modes_test.go, tests/functional/lib.sh
This series creates apis, middleware and utilities to track and control a heketi
server's administrative state. Currently all the state does
is control what clients are allowed to made modifying requests (POSTS, DELETES, etc):
* normal: all clients
* read-only: no clients
* local-only: only localhost may make changes
The idea is to allow an admin to put heketi into read-only mode in order for it to finish outstanding requests but accept no more. The local-only state is a hybrid state where only changes from localhost will be accepted so as to drain any outstanding external client requests but to allow for local administrative actions like a node replacement.
As a special case a local process can send SIGUSR2 to the server to reset the administrative state to normal. This is done to …
=> Add adminstrative modes to Heketi server

apps/glusterfs/device_entry.go
DeviceInfo.Id is actually a string, which makes the %d formatter an error with upcoming go 1.11.
Use %v for consistency.
Fixes #
=> apps:glusterfs fix logger format for go 1.11

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations_test.go
By failing to pass on the error conditions when trying to remove a failed
block volume creation we hide the error from the operations framework
which causes it to remove the pending operation entry and we lose
valuable debugging information and the ability to possibly automatically
revert the operation later.
Fixes #1324
=> Fix handling failures during block volume create rollback

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations.go, apps/glusterfs/operations_test.go, tests/functional/TestSmokeTest/tests/block_volume_test.go
Previously, block volumes were only reducing the free space from the
Block Hosting volumes in the Finalize step of the operation. This was
incorrect behavior because it meant that Heketi could allow two
concurrent block volume creations to essentially occupy the same free
space. Then one of the operations would fail during the Exec phase,
with a no-space error in gluster-block.
Patches in this series, change the operation so that block volumes are
esablished in the Build phase of the operation along with updating the free space 
n the hosting volume. A unit test is added to verify the low level behavior of the operation
as well as a functional test to check the interaction with gluster-block.
Both tests fail without the initial patch in the series.
Fixes …
=> apps: prevent overuse of block hosting volumes

executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, executors/cmdexec/device.go
In certain circumstances LVM commands can prompt the user for a
confirmation. Users will not be able to answer the prompt in case Heketi
executes the commands. By passing the `-qq` parameter to the LVM
commands, the default answer for the prompt will be no and the command
exits with a failure.
Fixes: gluster/gluster-kubernetes#497
This is very similar to commit 9c40a0e5 that fixed #1244.
=> executors: prevent pvcreate/vgcreate/lvcreate from displaying an interactive prompt

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations_test.go, executors/cmdexec/block_volume.go
When block volume create fails due to an insufficient number of nodes due to the request specifying an HA count Heketi was not cleaning up the operation even though no gluster-block level volume ever got created.
The HA count triggers an internal error condition within heketi, but originating in the Exec phase of the operation. This triggers a rollback but the rollback was failing due to gluster block not being able to delete an non-existing volume. This change makes it so that deleting a non-existing volume is handled and treated as a success within the Heketi delete function. A test is added to check for this condition.
Fixes [rhbz#1624738](https://bugzilla.redhat.com/show_bug.cgi?id=1624738)
=> apps: make block rollback more robust

apps/glusterfs/app_volume.go, apps/glusterfs/listing.go, apps/glusterfs/listing_test.go
Fix the result of VolumInfo for block hosting volumes to spare pending block volumes.
Fixes #1342
=> Fix  volume info to list only completed (not pending) block volumes

executors/cmdexec/block_volume.go, tests/functional/TestSmokeTest/tests/block_volume_test.go
PR #1340 was incomplete and did not correctly handle the various error reporting modes of gluster-block. It turns out gluster block always prints its status on stdout but does not always exit with a non-zero code when an error is encountered. This PR aims to fix those oversights and add functional tests for these situations.
=> Fix error checking when deleting a deleted block volume

executors/kubeexec/kubeexec.go
Kubeexec was adding extra text to stderr before sending it back to caller. In cases where the stderr text has to be parsed it was leading to parse errors.
It is sufficient to log the details of pod where the commands were hosted and such. Let the error string be passed as-is to the caller.
This is continuation of fixes to rhbz#1624738 along with PR #1340 and #1346
=> kubeexec: match the stderr output of kubeexec to that of sshexec

apps/glusterfs/db_operations.go
The created error message in https://github.com/heketi/heketi/blob/master/apps/glusterfs/db_operations.go#L302 incorporates `err`, which refers to an `err` variable that is always `nil` by https://github.com/heketi/heketi/blob/master/apps/glusterfs/db_operations.go#L272-L275 .
I assume this is a copy and paste mistake and replaced it with the value of the `durability` variable, which this switch is about and hence makes more sense to report.
=> Fix error message in glusterfs.DbCreate()

executors/cmdexec/device.go, tests/functional/TestSmokeTest/tests/heketi_test.go
When deleting a device do not ignore failures to remove vg/pv.
Fixes #1359
Functional test case added.
=> Fail device remove if vgremove hits an error

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go, etc/heketi.json
Volume create requests have provision to provide volume options.
However, a heketi admin does not have any means to set volume options
by default. This feature allows admin to set default volume options.
It is possible that heketi admin and heketi volume creator want to
set different values for the same volume option. To address such use
cases, admin is provided with two default option lists, as below:
1. HEKETI_PRE_REQUEST_VOLUME_OPTIONS env variable
pre_request_volume_options key in config's glusterfs section
Volume options that will be applied for all volumes created. Can be
overridden by volume options in volume create request.
2. HEKETI_POST_REQUEST_VOLUME_OPTIONS env variable
post_request_volume_options key in config's glusterfs section
Volume options that will be applied for all …
=> Default volume options 

extras/openshift-ci/README.md, extras/openshift-ci/build-image/Dockerfile
Add a dockerfile and a readme file that will be used to
help bootstrap testing heketi in openshift-ci.
=> extras: add a subdir to support integration with openshift ci

Makefile, client/cli/go/Makefile
After reading up a bit on go modules (vgo) it appears
that -i is no longer needed or recommended for Go [1].
It may have improved performance on some versions prior to
1.10 but is not needed for correctness and may not
have been much use for containerized builds anyway.
1: golang/go#27285 (comment)
Merging this will help enable more experimentation with go module support.
=> makefile: stop using -i in go build options

executors/cmdexec/block_volume.go, executors/cmdexec/brick_test.go, executors/cmdexec/cmdexec.go, executors/cmdexec/fakeexec_test.go, executors/cmdexec/peer_test.go, executors/kubeexec/kubeexec.go, executors/sshexec/sshexec.go, executors/sshexec/sshexec_test.go, pkg/remoteexec/result.go, pkg/remoteexec/ssh/ssh.go
When working on block volume delete it was discovered (or at least brought to the forefront) that Heketi's remote command execution functions were discarding stdout on command error and discarding stderr on command success. This isn't very unixy and quite unhelpful for handling the outputs of gluster-block. This PR reworks adds new types, "Result" and "Results" such that the code can return Results that have a lot more information about each command's result.
These new command running functions are plumbed through the various layers and used to clean up the block volume delete executor function (and demonstrate how they should be used).
I originally tried to refactor the functions more but it turned into a lot of churn for little benefit. This PR is much more targeted so that it more …
=> Add more comprehensive results for command execution

Makefile, client/api/python/tox.ini, executors/kubeexec/kubeexec_test.go
When the tests are run within a container in openshift-ci certain less typical (compared to desktop/server linux) environmental conditions are present. In the case of our tests what caused problems for our tests was the lack of a normal home directory and a UID that was generated and not present in /etc/passwd. These two conditions are worked around in order to prevent poor behaviors from glide and tox.
In addition, one of the kubeexec unit tests was failing because it assumed that it was never running inside a pod. This is no longer true. The test was disabled, rather than removed, in order to make me revisit it when I next rebase the patches in PR #1373.
One this change is commited to heketi, matching changes need to be commited to the openshift-ci release repo. Once that is done we …
=> makefile: make adjustments to openshift-ci behavior

apps/glusterfs/operations.go, apps/glusterfs/operations_test.go
Unlike volume creates, volume deletes require the system to check
the state of the pre-existing objects in the db. Thus the Build
step of the delete operations must update the state of the volume
in the db and not trust the state of the block volume entries
initially passed to the operation are up-to-date.
This probably should have been caught when I worked
on PR #1398, but unfortunately it must have slipped my mind. :-(
Fixes [rhbz#1647223](https://bugzilla.redhat.com/show_bug.cgi?id=1647223)
=> apps: protect against old state in volume delete ops

pkg/utils/bodystring.go, pkg/utils/bodystring_test.go, pkg/utils/jsonutils.go, pkg/utils/jsonutils_test.go, pkg/utils/statusgroup.go, pkg/utils/statusgroup_test.go
In a sequence of commits
fc8e4c5fa19d11afb4d9ebed8a94082b7d9459ae
31b83a82a22956349d0df178d5a0d212af237871
7c3cd4c1e0be107195558059c604ebf1dc765d53
Heketi was relicensed from Apache to the following model:
- the rest api client code is under dual Apache2 or LGPLv3+
- all other parts (server, cli, tests, ...) are under dual LGPLv3+ or GPLv2
Now an oversight/mistake was made in that parts of the pkg/utils are
used in the client and hence apache-licensed projects that compile
in heketi client, like kubernetes, have a license problem since they
pull GPL code in. See:
https://github.com/heketi/heketi/issues/1279
https://github.com/kubernetes/kubernetes/issues/35557
https://github.com/kubernetes/kubernetes/issues/70802
This patch fixes the oversight by relicensing the remaining
pieces of …
=> pkg/utils: relicense to dual Apache2 and LGPLv3+

pkg/testutils/cluster.go, pkg/testutils/nodes.go, pkg/testutils/serverctl.go, tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go, tests/functional/TestSmokeTest/tests/arbiter_test.go, tests/functional/TestSmokeTest/tests/block_volume_test.go, tests/functional/TestSmokeTest/tests/delete_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go, tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go
To avoid future copy and paste of test code this PR moves and refactors code that should be reusable across golang functional test packages.
Right now the packages provides two features, one per file:
* Heketi server management for tests that need to stop and start heketi themselves
* Cluster setup and teardown based on the "smoke test" directory
For now I've let the some of the commits demonstrate what was changed from when the code was copied from the uniqe source file. This may need to be squashed.
=> tests: create a testutils package

.travis.yml, tests/020-test-shellscripts.sh, tests/200-py-unittest.sh
On December 1st, [BitBucket disabled TLS 1.0 support](https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01) which is causing problems for the old version of mercurial/python provided by the travis ci we are using.
This change bumps the distro version we request from travis to "xenial" where TLS > 1.0 does work. This also includes fixes for fallout from the version bump.
All other PRs will continue to fail unless this PR is merged.
=> travis: try building on xenial image, to resolve hg tls issues

etc/heketi.json, executors/cmdexec/cmdexec.go, executors/cmdexec/config.go, executors/cmdexec/fakeexec_test.go, executors/cmdexec/peer.go, executors/cmdexec/peer_test.go, executors/cmdexec/snapshot.go, executors/cmdexec/volume.go, executors/kubeexec/kubeexec.go, executors/sshexec/sshexec.go
This PR adds a configurable timeout to invocations of the Gluster CLI, set to 10 minutes by default. The reason for this is that in a very busy system, with many volumes, some gluster cli commands can take longer than the default timeout of 2 minutes.
This adds a config setting of `gluster_cli_timeout` that can be overridden by the env variable `HEKETI_GLUSTER_CLI_TIMEOUT` and defaults to 10 minutes. This seemed to have been a good default value from the observations. This value is passed to the gluster cli commandline with the `--timeout` parameter.
Fixes #1426 
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1651041
In order to not run into the `ExecCommands` timeout which is currently set to 10 minutes in the invocations, the timeout for the ExecCommands invocations is also made …
=> Add a configurable timeout to gluster cli, defaulting to 10 minutes

docs/profiling.md, etc/heketi.json, main.go, server/config/config.go, server/profiling/profiling.go
Add support for profiling like "net/http/pprof" does, but through the
"gorilla/mux" router. Profiling is disabled by default, set the
`HEKETI_PROFILING` environment variable to a non-empty string or add
`"profiling": true` to the --config file.
Several endpoints will get registered, and are writter to stderr:
$ HEKETI_PROFILING=1 ./heketi --config=heketi.json
...
DEBUG: registered profiling handler on /debug/pprof/block
DEBUG: registered profiling handler on /debug/pprof/goroutine
DEBUG: registered profiling handler on /debug/pprof/heap
DEBUG: registered profiling handler on /debug/pprof/mutex
DEBUG: registered profiling handler on /debug/pprof/threadcreate
DEBUG: registered profiling handler on /debug/pprof/cmdline
DEBUG: registered profiling handler on /debug/pprof/profile
DEBUG: …
=> heketi: add support for profiling with pprof

extras/systemd/heketi.env
The environment variables that can be set to influence the behaviour of
Heketi are not well documented. This is an attempt to capture the
variables that can be changed for the benefit of the heketi.service
systemd unit.
The systemd unit already tries to read variables from
/etc/heketi/heketi.env, but this file is not provided anywhere. If users
have a need to change the environment, they will need to create the file
and not mistype the name of the variable. Providing a file with the
defaults makes it less error prone.
Some of the variables have been left out intentionally:
- admin and user keys: these should be set in the heketi.json config file. Passing them as an environment variable to non-containerized processes seems insecure (thanks @raghavendra-talur)
- heketi as a service started …
=> systemd: provide a heketi.env file with possible variables

pkg/remoteexec/result.go, pkg/remoteexec/result_test.go
Historically, heketi used to convert the stderr of commands to go error
type and discard the originating error. The remoteexec library however
goes to lengths to retain all the information about a command including
the error output (stderr) and originating error. But most of the
preexisting heketi code wants to check the error output not the
originating error.
This change allows treating a Result type as an error, looking for error
output if it exists and then falling back to the content of the
originating error. When the adapter functions FirstErrorIndexed,
FirstError, and AnyError were added the important ErrorOutput was
forgotten and the originating error was used. Now it returns the
result-as-error. This change fixes at least one regression where the
error response of "gluster volume …
=> remoteexec: use error output for error contents

pkg/testutils/cluster.go, pkg/testutils/serverctl.go, tests/functional/TestErrorHandling/tests/error_inject_test.go
These changes make some small but impactful changes to the recently added testutils package.
The serverctl file has been expanded in scope and reliablity.
The cluster management has been expanded for more reliable and flexible teardown.
Does not directly fix issues.
Is a prerequisite of issue #1401
This PR is built upon the changes in pr #1196 as this module is primarily consumed by the test suite added in that PR. Please review & merge that PR first.
=> General improvements for testutils

apps/glusterfs/app.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/brick_create.go, apps/glusterfs/brick_entry.go, apps/glusterfs/cluster_entry.go, apps/glusterfs/operations.go, apps/glusterfs/operations_block_volume.go, apps/glusterfs/operations_cleanup.go, apps/glusterfs/operations_cleanup_test.go, apps/glusterfs/operations_load.go, apps/glusterfs/operations_load_test.go, apps/glusterfs/operations_manage.go, apps/glusterfs/operations_volume.go, apps/glusterfs/try_on_host.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, main.go
This PR implements a good chunk of the code needed to actually make operations cleanable. This is where the bulk of the refactorings to app/glusterfs lie as far as operations are concerned. The general gist is that you'll see:
* Various refactorings to make clean up code reasonable: including splitting out db access from executor stuff
* Making various operations loadable
* Making various operations cleanable
* Unit tests for the above
* An offline mode for cleaning: `heketi offline cleanup-operations ...` which can be run when heketi server is not running.
The latter is mainly included in this PR (as opposed to a latter PR) as a demonstration of things end-to-end.
Does this seem like a lot? There's more to come!
Part of issue #1401
This looks like a lot of commits but hopefully these are …
=> auto cleanup pt2

tests/functional/run.sh
I found that the error handling tests were not run at all in the functional test runs... Fix this!
=> funtional tests: run TestErrorHandling by default

apps/glusterfs/app_test.go
Go 1.11 (on fedora 29) found this formatting error.
=> apps: fix gofmt error found by go 1.11

apps/glusterfs/app.go, apps/glusterfs/app_db.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/brick_entry.go, apps/glusterfs/cluster_entry.go, apps/glusterfs/db_operations.go, apps/glusterfs/dbcommon.go, apps/glusterfs/device_entry.go, apps/glusterfs/node_entry.go, apps/glusterfs/pendingop_entry.go, apps/glusterfs/volume_entry.go, client/api/go-client/db.go, client/cli/go/cmds/db.go, main.go
This PR implements consistency check for heketi db. The check can be performed in both offline and online mode. In online mode, a cli command or a REST call can be made to a heketi server. In offline version, `db check` subcommand is to be invoked for heketi binary with path to heketi.db. 
Consistency check only validates the information provided in the database and does not validate it against *real* state on the Gluster nodes and/or Kubernetes/Openshift.
I did not find any value in making a version of this which takes a JSON file representing heketi database as input. Such scenarios can be handled by using the `db import` command first and then invoking a `db check` command later.
=> Perform consistency checks on db

docs/design/blockvolume.md
The design for the blockvolume feature of heketi was originally contained in the [end-to-end design](https://github.com/gluster/gluster-kubernetes/blob/master/docs/design/gluster-block-provisioning.md)
in [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes). Now this is finally extracted here into a proper heketi specific design doc (after the fact).
=> docs: Add a blockvolume design doc

apps/glusterfs/app.go, apps/glusterfs/app_db.go, apps/glusterfs/app_examiner.go, apps/glusterfs/db_operations.go, apps/glusterfs/examiner.go, client/api/go-client/state.go, client/cli/go/cmds/server.go, executors/cmdexec/volume.go, executors/executor.go, executors/injectexec/mock_base.go, executors/mockexec/mock.go, executors/stack/stack.go, main.go
This PR introduces diagnostics ability to heketi. 
Primarily, heketi provides a single command to fetch all the necessary information from Gluster to compare its database with the Gluster backend.
Further, it also performs some comparison between the two data sets to report problems and suggest fixes.
Fixes #
=> Diagnostics: examine gluster

apps/glusterfs/brick_entry.go, apps/glusterfs/operations_block_volume.go, apps/glusterfs/operations_volume.go, apps/glusterfs/operations_volume_test.go
The volume create operation would incorrectly leave multiple extra un-referencable brick IDs in the list if the create operation was internally retired. This set of changes fixes this situation.
This is a counter proposal for PR #1472
=> Fix incorrect extra brick IDs on volume after retry

pkg/metrics/metrics.go
All the device information are stored in KiB format
updated the code to convert KiB to byte format.
sample output:
```
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdb",hostname="192.168.10.100"} 5.24288e+08
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdb",hostname="192.168.10.101"} 5.24288e+08
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdb",hostname="192.168.10.102"} 5.24288e+08
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdb",hostname="192.168.10.103"} 5.24288e+08
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdc",hostname="192.168.10.100"} 5.24288e+08
heketi_device_free{cluster="af7d9528db4f4ac00992dfaa0d05cbd9",device="/dev/sdc",hostna …
```
=> Metrics: convert device info from KiB to bytes

apps/glusterfs/listing.go, apps/glusterfs/operations_block_volume_test.go, apps/glusterfs/operations_volume_test.go
The functions used to filter out pending volumes and block volumes were not correctly checking for all cases where a pending operation was indicating that a volume or block volume was pending & incomplete.
Fixes [rhbz#1662141](https://bugzilla.redhat.com/show_bug.cgi?id=1662141)
It is now possible for a volume to go pending for delete and then be unmarked pending if the delete fails. This implies that it is possible for a volume to vanish from the listing and then reappear some time later. This is a bit odd but I don't think this behavior is worse than failing the listing commands because a pending delete operation is in the db.
=> Ensure pending volumes filter works on delete operations

extras/kubernetes/README.md
The template files in the heketi repo are only really useful
if you are getting into the low-level details of how
heketi integrates into openshift. If you don't plan
on hacking on heketi we want you to use gluster-kubernetes.
Fixes #1485 by discouraging use of these templates.
=> extras: once again, point to g-k for for deployments

tests/200-py-unittest.sh
Travis runs have been breaking lately and it appears to be due
to a change in the version of python (3.6 -> 3.7). This change
tries to make it simple to enable and use at least one version
of python 3.
=> tests: try to select best python version for use in travis

tests/functional/TestErrorHandling/tests/background_cleanup_test.go
It is observed that sometimes, the cleanup tests, e.g. `TestCleanupAfterRestart` fail after stale operations being cleaned up with the failure that there's an `InFlight` operation. This is because cleanup creates InFlight operations, and we don't wait for *those* to be done.
This PR tries to reduce the flakiness of `TestCleanupAfterRestart` and `TestCleanupPeriodic` by waiting for InFlight operations to vanish in addition to Stale/Failed operations.
*  We might also need to increase the additional wait time of 5 sec in `TestCleanupAfterRestart` some more. We'll see.
* Additional patches in this PR just improve some comments around the changed code path
=> Try to reduce flakiness of cleanup functional tests

.travis.yml
This change bumps the versions of golang we're using in travis, dropping 1.8 and adding 1.11.
It also stops running "make release" on older versions and does that as a separate task.
=> Tweak travis config to use newer golang versions, don't do extra work on older versions

etc/heketi.json, executors/cmdexec/brick.go, executors/cmdexec/cmdexec.go, executors/cmdexec/config.go, executors/cmdexec/device.go, executors/cmdexec/fakeexec_test.go, executors/injectexec/transport.go, executors/injectexec/transport_test.go
IO alignment should be configurable for RAID based architectures as stated by GlusterFS docs. This PR is intended to add a set of configurable flags relative to the LVM stack and XFS which allow to configure IO alignment properly. 
All of these flags are not required so current deployments would not be affected.
=> IO Alignment improvements

apps/glusterfs/db_operations.go
The pending ops check was not updating the "Total" counter
when looping over the pending operations in the db. This
change makes the loop update that counter.
Fixes [rhbz#1667797](https://bugzilla.redhat.com/show_bug.cgi?id=1667797)
=> apps: update total counter when checking pending ops in db

apps/glusterfs/operations_manage.go, apps/glusterfs/operations_test.go
This small series of patches rewrites the run-operation/retry operation code to a more simple and streamlined manner. It removes code duplication and leaves the (re)try logic in one more easily understandable loop with only one call to Exec and only one call to Rollback with consistent return values and making failed from rollback.
Fixes #1493 
overall diffstat:
```
apps/glusterfs/operations_manage.go | 128 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------------
apps/glusterfs/operations_test.go   |   4 ++--
2 files changed, 56 insertions(+), 76 deletions(-)
```
=> Streamline retry operation code

executors/cmdexec/block_volume.go, tests/functional/TestErrorHandling/tests/rollback_test.go
In the case that we request a delete of a block volume but the
block hosting volume never existed the error response from gluster
block is a little different than the usual. In this case we
get "Volume X does not exist" which heketi was not treating as
a does-not-exist type error when processing gluster-block delete
response.
This includes a fix and two tests for gluster-block volume rollback behavior (using the error handling suite).
=> handle block volume "does not exist" errors if BHV never was created

executors/cmdexec/block_volume.go, executors/injectexec/hooks.go, executors/injectexec/hooks_test.go, tests/functional/TestErrorHandling/tests/error_inject_test.go
This PR updates the output handling in the code that calls gluster-block create so that the way that command reports errors is more correctly handled with the new command results model.
Fixes #1479
=> Fix issue 1479 - gluster-block error handling

client/cli/go/cmds/topology.go
These changes switch topology info from using a bunch of printf-style calls to a "text/template" based templated output. The template ought to be easier to maintain that the printfs. After converting to a template, lines for tags on nodes and devices are added.
Enhances output of topology info, fixing [rhbz#1572579](https://bugzilla.redhat.com/show_bug.cgi?id=1572579)
=> Convert topology info to a template and add tags to template

docs/admin/server.md, etc/heketi.json, executors/cmdexec/brick.go, executors/cmdexec/cmdexec.go, executors/cmdexec/config.go
There are regular problems reported where Heketi fails to remove the bricks from a Gluster volume. This is most often caused by an open filedescriptor in one of the brick processes. Debugging this needs to be done in a timely fashion, as processes may get restarted and any trace
of the kept open file is removed.
By logging the output of 'lsof /path/to/brick' when unmounting fails, we should be able to find the filenames that the brick processes did not close when the Gluster volume got stopped and deleted.
=> logging: grab output of 'lsof /path/to/brick' in case unmounting fails

apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go, apps/glusterfs/device_entry.go
This PR moves checks in DeviceEntry.Delete to a new function called CheckDelete and calls the  new function from both App.DeviceDelete and DeviceEntry.Delete 
Fixes: #1478
=> check device state before deleting the device

client/api/go-client/operations.go
The client api for server operations (used by heketi cli) was
not properly handling errors at the http level and was trying
to parse error bodies as JSON, which was not correct.
This change adds the correct error handling functions for
server operations functions.
=> client: add error handling to server operations client funcs

client/cli/go/cmds/server.go
Fix CLI examples for heketi-cli server mode get and
heketi-cli server mode set which appear to have simply been
copy and pasted from a previous command and not updated.
=> cli: fix incorrect examples for server mode set & get

client/cli/go/cmds/volume.go, pkg/glusterfs/api/types.go
* Minor cleanups
* Convert 'volume info' to display via template
* Print an 'NxM' string for distribue + replica line
Example:
```
$ ./heketi-cli volume info fc66a36f8c368e6803859c02efe95ca6
Name: vol_fc66a36f8c368e6803859c02efe95ca6
Size: 105
Volume Id: fc66a36f8c368e6803859c02efe95ca6
Cluster Id: 9f295b5ab4a965e22f6d24cf73970f01
Mount: 10.70.47.92:vol_fc66a36f8c368e6803859c02efe95ca6
Mount Options: backup-volfile-servers=10.70.47.196,10.70.46.72
Block: true
Free Size: 70
Reserved Size: 0
Block Hosting Restriction: (none)
Block Volumes: [0c25795f72d359b4325b47f96c906b3c 0dae4bd21cdf4fd7d86b8f1884d7d0bf 128837a348d834c9182a814cd15930b0 138b48fcf42edbcee294d5457ce44a4c 166629ff21aac44c4c860664de06090b 1d49f75a38a837accabc036e2d883511 276d636cc9c885013b614ad823466010 …
```
=> Display distribute and replica counts in 'heketi-cli volume info'

apps/glusterfs/app_topology.go, apps/glusterfs/app_topology_test.go, pkg/glusterfs/api/types.go, pkg/metrics/metrics.go
Add block volume count to metrics
This PR adds the block volume count to the metrics
Fixes: [rhbz#1589012](https://bugzilla.redhat.com/show_bug.cgi?id=1589012)
logs:
```
#HELP heketi_block_volumes_count Number of block volumes on cluster
heketi_block_volumes_count{cluster="812506b5c3063c72b3cfc467951100c6"} 3
heketi_volumes_count{cluster="812506b5c3063c72b3cfc467951100c6"} 4
```
=>  Add block volume count to metrics

glide.lock, glide.yaml
Negroni is still locked to version 0.2.0 which doesn't include timestamps in logs. This PR upgrades negroni to version 1.0.0.
Fixes #694
=> Upgrade negroni version to 1.0.0 and update glide.lock

apps/glusterfs/volume_entry_test.go
Zones are not (yet) being really used in the tests,
but just using two zones rarely makes sense, and for
the strict zone checking, we will need more zones.
This PR changes `setupSampleDbWithTopology` to always configure one zone per node.
This has been split out of PR #1518.
=> tests: always use the number of nodes as number of zones (for now)

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/brick_allocate.go, apps/glusterfs/placer_settings.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go, apps/glusterfs/zone_filter.go, apps/glusterfs/zone_filter_test.go, client/api/go-client/client_test.go
Zones are currently a best-effort concept. While the expectation is that e.g. a replica-3 brick set will span 3 zones, this is not always the case. This PR introduces strict zone checking. The behavior can be controlled with the new config option `zone_checking` (and the corresponding environment variable `HEKETI_ZONE_CHECKING`) which can be set to `strict`, which only lets volume creates succeed if each brick set is spread across sufficiently many zones,  or to `none` (the default) which lets heketi behave like before.
Filed this as a WIP PR to see what the CI thinks and to start the discussion. Will need to squash a few patches before merging if we agree about this approach.
=> implement strict zone checking

apps/glusterfs/app.go, apps/glusterfs/placer_settings.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, apps/glusterfs/volume_entry_test.go
PR #1518 added the core support for strict zone checking. This PR adds the ability to request strict zone checking on a per-volume basis by setting the 'user.heketi.zone-checking' volume option to 'strict'.
This PR also adds tests for the volume option, for volume expand, and device replace (set state failure).
This PR depends on PR #1518 and should only be merged after that one.
=> Strict zone checking followup

pkg/testutils/cluster.go, tests/functional/TestSmokeTest/tests/heketi_test.go
Add a function to copy the ClusterEnv so customization can be applied to
a copy of the global cluster env. Add callback functions
CustomizeNodeRequest and CustomizeDeviceRequest so individual tests can
make tweaks to the cluster config without having to do the same as the
setup functions manually.
This functionality can serve as a building block for future tests that need to check the behavior of the system and the stock cluster setup functions are too limiting.
=> add functions for customizing cluster setup

apps/glusterfs/zone_filter.go, tests/functional/TestErrorHandling/tests/heketi_zone_check_test.go
device info is stored with prefix DEVICE, we need to ignore these keys when we are listing the devices to add bricks.
Fixes: #1531 
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
This PR filter out the device ID which starts with "DEVICE"
=> apps: ignore device id with prefix DEVICE

apps/glusterfs/dbentry.go, apps/glusterfs/device_entry_test.go
This change provides an improved error message that points to the bucket and key of the failing entry if the unmarshal function of an entry fetched from the db fails.
=> Better error when unmarshaling a db entry fails

executors/cmdexec/device.go
Device setup can fail, for example if the partition is not wiped or is already initialized. This PR adds a hint about these possible issues to the error returned by the failed command, which can be cryptic.
Fixes #595
After considering a smarter solution with individual parsing of the errors of the commands, which is error prone in itself, because there are many possible errors and the error text can also change by newer versions of the tools, this PR follows a very simplistic approach of just adding a general hint.
=> executors: add a hint of possible issues to device setup error

pkg/remoteexec/ssh/ssh.go, tests/functional/TestSmokeTest/tests/heketi_test.go
PR #836 was meant to re-enable the HeketiCreateVolumeWithGid test, but since it didn't add the _Test_ prefix, it wasn't.
This PR fixes the test (almost rewritten) and enables the test for real this time.
=> tests: fix and enable TestHeketiCreateVolumeWithGid

tests/functional/TestErrorHandling/vagrant/roles/common/tasks/main.yml, tests/functional/TestManyBricksVolume/vagrant/roles/common/tasks/main.yml, tests/functional/TestSmokeTest/vagrant/roles/common/tasks/main.yml, tests/functional/TestVolumeNotDeletedWhenNodeIsDown/vagrant/roles/common/tasks/main.yml, tests/functional/TestVolumeSnapshotBehavior/vagrant/roles/common/tasks/main.yml
The current approach of using "dd if=/dev/zeros ..." occupies over
3GB disk space already during provisioning and is pretty slow.
wipefs achieves the same almost without allocating disk space and is
a lot quicker.
Signed-off-by: Sven Anderson <sven@redhat.com>
=> tests: use wipefs for cleaning disks in functional tests

extras/tools/scrub.py
Prevent the scrub script from creating device storage size values that
are out of bounds (OOB), either below zero or larger than the total size
of the device itself. If this condition is hit when running the scrub
script it means that db is already out of sync and the size values
should be pre-adjusted prior to running scrub.py.
=> extra tools: make scrub safer by blocking oob size values

apps/glusterfs/app.go, apps/glusterfs/app_test.go, apps/glusterfs/app_volume_test.go, apps/glusterfs/testapp_mock.go, main.go, pkg/heketitest/heketitest.go
Previously, the NewApp function was only able to return the App or a
nil. This caused the error handling in functions that called NewApp to
be rather awkward and partly led to lack of good error reporting in
the main.go file.
=> apps: refactor app creation and setup

executors/mockexec/mock.go
Add a new override-able function to the mock executor that
returns the size of a mock device in GiB. By default this
function returns 500 or the integer value of the environment variable
HEKETI_MOCK_DEVICE_SIZE_GB if it is set.
The intent is that both internal heketi tests, and more importantly, tests that work externally on the heketi binary can use the mock executor for testing different properties of the system without recompiling the code.
=> executors: make mock executor's device size more controllable

tests/functional/TestErrorHandling/tests/heketi_zone_check_test.go
Add a simple check to verify that setting a zone-checking option of "none" will override the global option of strict zone checking.
=> functional tests: add check to verify volume option has precedence

apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go
In order to be easily able to back-reference the gluster volumes to
heketi volumes, the heketi volume id is stored under user.heketi.id
in the gluster volume options.
Closes #1322
Signed-off-by: Sven Anderson <sven@redhat.com>
=> apps: add the heketi volume id to the gluster volume meta data

client/api/python/heketi/heketi.py, client/api/python/test/unit/test_client.py
Previously, the delay within the code that polls for results was hard
coded to one second. This change retains the existing default but makes
it possible to pass a different value in to the heketi client object.
Aside from one test to ensure that the default functions, make all of
the other python "unit" tests use 0.2 seconds of delay. This greatly
speeds up running the test suite from around 3m to 32s on my machine. A
very short delay is ok for these tests because they are always using the
mock executor.
This only touches the python client at the moment but something similar is going on in the go client api. We should look into improving that as well.
=> Make delay in API results polling an argument in the python client library 

extras/tools/scrub.py
The scrub.py script was not properly cleaning up block volumes in the 
case where the BHV was not also pending. It now correctly removes the 
reference to the block volume from it's BHV.
Fixes #1522
=> extra tools: properly remove block vol refs from BHVs

main.go, server/admin/state.go, server/config/config.go, tests/functional/TestErrorHandling/tests/options_test.go
Add the ability to set a config param or environment variable
(HEKETI_DEFAULT_STATE) that will be applied on server start up.  This is
useful in the case that you want heketi to start up but do not want the
server to immediately start serving new requests.
Note: this does not change the behavior of internally driven changes
like the background operations cleanup. That would need to be disabled
independently.
=> Add a default admin mode option

apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_test.go
When extracting a volume option meant for heketi from the volume options
of a volume, use the more common "last item takes precedence" rule. This
will cause heketi to match what the options meant for gluster do and
matches with common expectations.
This change also creates a volume options to map function such that the
functions that extract/parse a value do not have to handle the common
aspects of searching through the options list to find keys and handle
the precedence individually.
Fixes #1551
This issue was found when testing the recently added zone checking feature but also turned out to impact the options we added for the arbiter feature.
=> Clean up the "parsing" and precedence for volume options

docs/design/arbiter.md
Fixes a mistake in the design doc. If people read the design doc it will still be a little out of date but not wrong.
Fixes #1301
=> docs: change arbiter doc to note that "supported" is default

extras/container/heketi-start.sh
If the heketi.db does not exist already stat will print to
stderr. These are not errors in the case the db has not yet
been created, so this stderr is now redirected to /dev/null.
Fixes #1352
=> container: suppress stat errors in heketi-start.sh

apps/glusterfs/app.go, apps/glusterfs/dbattribute_entry.go, apps/glusterfs/dbattribute_entry_test.go, tests/functional/TestErrorHandling/tests/db_contents_test.go
Check that all the dbattributes in the db are known and if there is an
unknown attribute, which is probably from a too-new version of heketi,
refuse to start.
* Adds unit tests
* Adds functional test
Fixes #1361
I have made this unconditional, but I'm open to making this test conditional. I didn't think we hit too many cases where we'd need to turn the check off though so I left it out. Any opinions?
=> Have the server refuse to start if db has unknown dbattributes

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/cluster_entry.go, apps/glusterfs/limits.go, apps/glusterfs/operations_volume_test.go, apps/glusterfs/volume_entry.go
With this change, we can limit volumes that Heketi allows to create in a Gluster cluster.
This change is a departure from the previous behavior of heketi. Earlier, heketi did not limit the volumes per Gluster trusted storage pool but we have seen cases where the glusterd startup times out if the volumes in the trusted storage pool cross 1000. Hence, the default limit is set to 1000.
To override the default value admins should set the `max_volumes_per_cluster option` in `glusterfs` section of heketi.json.
Negative value means no limit.
Value set to 0 means use the default.
Positive and valid int value set the limit to that integer.
When env var HEKETI_GLUSTER_MAX_VOLUMES_PER_CLUSTER is set, it overrides the default value and the value provided in heketi config.
Signed-off-by: Raghavendra …
=> Limit volumes per Gluster cluster

tests/functional/TestErrorHandling/tests/limits_test.go
Add a test case for limiting the maximum number of volumes.
This PR is based on PR #1558 and that PR should be reviewed and merged first. This PR currently fails running the test due to an issue in the original PR, regarding the handling of negative limits. Once this issue is resolved and this PR rebased, the test should start passing.
=>  functional tests: add test for max volume limits 

docs/admin/maintenance.md
The topology file is not a reliable way to add nodes & devices to an existing cluster, remove mention of that method from the maintenance doc.
Fixes #1553
=> docs: remove mention of topology file to grow a cluster

docs/design/tag-matching.md
This is a design doc for a proposed enhancement to heketi for a tag-matching mechanism allows user specified filtering of devices to implement tiering, etc.
=> docs: add a tag-matching design document

extras/container/heketi-start.sh
This PR fix issue with start the heketi in kubernetes environment when uses backup db to kube secret and sum of sizes packed db and unpacked db is more than 1MiB.
[Kubernetes secrets are limited to 1MiB in size.](https://kubernetes.io/docs/concepts/configuration/secret/#restrictions)
Fixes #1574
Line 80 was here only for compatibility with versions prior to 5.0 when db compression was introduced during backup.
=> Use temporary directory for db extraction

pkg/remoteexec/ssh/ssh.go
The ssh executor wraps the to-be-executed command into single quotes
in order to pass it to bash as a command line argument.  However, the
quotes that might be contained by the command string are not handles.
This has several implications.  First, the single quotes get lost in
the intermediate shell, so they can't have any effect in last
executing shell.  Secondly, quotes allow to "escape" the quoting,
having unexpected effects, possibly even security implications.  Many
places in the code use single quotes however, resulting in incorrect
execution lines like `[/bin/bash -c 'mycmd 'foo bar'']`, which would
only execute `mycmd foo` and drop `bar`.
This change escapes the single quotes to the sequence `'\''` resulting
in the correctly interpreted line
`[/bin/bash -c 'mycmd '\''foo …
=> remoteexec: escape single quotes in quoted shell command

extras/container/heketi-start.sh
Add code to the container start-up script that uses the new
HEKETI_DB_ARCHIVE_PATH and HEKETI_DB_ARCHIVE_COUNT environment variables
to keep a limited set of archival copies of the heketi db as it was
before the server process started. If HEKETI_DB_ARCHIVE_PATH is unset
the code block is skipped. Otherwise, a compressed copy of the db will
be made, keeping up to HEKETI_DB_ARCHIVE_COUNT copies of the db.
Fixes [rhbz#1686894](https://bugzilla.redhat.com/show_bug.cgi?id=1686894)
=> container: add ability to archive db at container start up

apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations_volume_test.go, apps/glusterfs/volume_entry.go
When requesting a new block volume the maximum volume limit should
only apply to BHVs. However, the code was previously treating every
new blockvolume request as if it was going to also create a BHV.
This change alters the code such that the check is only applied
to file volume creates and block volume creates that do not find
a previous BHV.
Fixes [rhbz#1476223](https://bugzilla.redhat.com/show_bug.cgi?id=1476223)
=> limit for volumes only applies to block volumes with BVH

apps/glusterfs/app_device.go, apps/glusterfs/app_device_test.go
If the device being resync'ed is part of any pending operations,
deny the resync. This will prevent getting wrong values for the
system and db as changes are being made.
Fixes #1539
Note that the issue contemplated adding a --force flag. I opted not to add the flag because this would need additional plumbing in the api and cli and thus additional complexity, where the preferable approach would be to clear all pending operations first (using heketi-cli server operations clean for example). Additionally, only devices that have pending ops on them are blocked so if a device had no pending ops, even though there were pending ops on other devices, it would still be resyncable. But I'm willing to reconsider the force flag if reviewers want to.
=> prevent running 'device resync' with pending operations present

client/cli/go/cmds/topology.go
It can frequently be useful to scrape output from topology info but the
output format, while generally useful as a human readable format is not
simple to parse. Allow the use of a go template [1] to be supplied on
the command line to custom format the api response within the topology
info command. This is similar in spirit to the kubectl -o go-template=xxx option.
1: https://golang.org/pkg/text/template/
Fixes #1593
=> allow user supplied templates for topology info

apps/glusterfs/app.go, server/rest/README.md, server/rest/asynchttp.go, server/rest/asynchttp_test.go, server/rest/routes.go
This change takes the source files for the formerly external
"heketi/rest" package and makes it a server utility library
(under "heketi/heketi/server/rest") with a license updated
to match the other server components.
The imports of the source files are adjusted to match the
internal "pkg/" utility packages, rather than the external
"heketi/utils" package.
This change is part of the effort to standardize and unify
licensing of the heketi packages as noted in issue #1279.
With this change the heketi server always uses the updated
in-tree utility functions.
Quasi-prerequisite / part of issue #1279
This makes no functional change only code movement.
=> reintroduce rest framework into source tree

client/api/go-client/block_volume.go, client/api/go-client/client.go, client/api/go-client/client_test.go, client/api/go-client/device.go, client/api/go-client/node.go, client/api/go-client/operations.go, client/api/go-client/volume.go, pkg/testutils/cluster.go, tests/functional/TestErrorHandling/tests/common_test.go, tests/functional/TestSmokeTest/tests/heketi_test.go
These changes remove hard coded delays in the api functions and centralizes that logic. It makes the poll delay configurable when the client type is being created and uses this configurable delay to help speed up the unit and functional tests.
This has been sitting on my laptop for too long and I wanted to get it out there even in this unfinished state. Note that this PR is based on #1544 so please review and merge that first.
=> Make request poll delay configurable, and speed up tests

main.go, pkg/testutils/serverctl.go, server/config/config.go, tests/300-db-import-export.sh, tests/functional/TestEnabledTLS/test_tls.py, tests/functional/TestErrorHandling/tests/options_test.go, tests/functional/TestUpgrade/test_upgrade.py, tests/functional/lib.sh
The heketi server will fail to start if authentication parameters
are not supplied in the configuration. The only way to disable
authentication is to pass the --disable-auth option as a server
command line argument.
Note: This is a significant behavior change.
This is being done to ensure more secure deployments by default. Instead of having to opt-in to authentication, Heketi now requires one to opt out of authentication. Generally, there is not much need to even opt out of authentication (just use auth with a well-known "secret") except for testing and backwards compatibility for older clients where auth has not been configured.
If this PR is accepted I plan on mailing the list as well as making a change to the README so visitors to the github page see a highlighted note.
Last changes …
=> Default to authenticated access [behavior change]

client/cli/go/cmds/device.go, client/cli/go/cmds/node.go, client/cli/go/cmds/topology.go, client/cli/go/cmds/utils.go
PR #831 made an attempt to rename output of state "failed" to "removed" but it was not consistent throughout the CLI. This change attempts to make the printing of "removed" more consistent.
Fixes #
=> Make entry state naming consistent in heketi cli

glide.lock
No we really shouldn't be manually editing glide.lock but this fixes
the use of a removed bitbucket api by the apparently unmaintained
glide.
Fixes #
Its probably time to start thinking about moving away from glide. Seriously that is.
=> work around broken api use in glide

Makefile
We have been seeing issues with glide. It is not clear why glide fails to build cache for some of the packages. The error "Cannot detect VCS" does not tell what exactly failed. This patch adds debug flag to glide calls in makefile. We would like to run the glide commands in debug mode until we figure out the issue.
=> glide debug

executors/cmdexec/block_volume.go, executors/cmdexec/brick.go, executors/cmdexec/cmdexec.go, executors/cmdexec/device.go, executors/cmdexec/fakeexec_test.go, executors/cmdexec/peer.go, executors/cmdexec/snapshot.go, executors/cmdexec/volume.go, executors/injectexec/transport.go, executors/injectexec/transport_test.go, executors/kubeexec/config.go, executors/kubeexec/kubeexec.go, executors/sshexec/sshexec.go, executors/sshexec/sshexec_test.go, pkg/remoteexec/cmd.go, pkg/remoteexec/kube/conn.go, pkg/remoteexec/kube/counter.go, pkg/remoteexec/kube/exec.go, pkg/remoteexec/kube/exec_test.go, pkg/remoteexec/log/commandlog.go, pkg/remoteexec/ssh/ssh.go, tests/functional/TestErrorHandling/tests/device_test.go, tests/functional/TestErrorHandling/tests/timeout_test.go
Various refactorings in and around the remote execution subsystem.
Highlights include:
* Adding a richer `Cmd` type for commands and their options
* Making logging in the remote exec backends more uniform
* Suppressing the output of noisy commands when they succeed
* Adding a form of timeout to the kube exec backend
Fixes #1555
=> Refactor remote command handling and timeout behaviors

etc/heketi.json
Heketi requires authentication by default now. However, the sample
confin json that is in etc dir has default secrets. To discourage
packagers from using the same as-is, we are removing the default
secrets.
Just realized, I don't know how to solve this in container world if the users expect it to run with no config.
=> etc: remove the default secrets from heketi.json

apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_create.go, apps/glusterfs/volume_entry_test.go, client/cli/go/cmds/heketi_storage.go, client/cli/go/cmds/volume.go
In Kubernetes and OpenShift, the gluster volume provisioner parses the volume information provided by heketi during volume creation to create the endpoint that is used for mounting the volume.
Some heketi operations, like node or device replace can change the cluster information such that the IPs listed in the endpoints become outdated. In this patch, we provide a command that outputs the current mount information for the volume and can be used to patch an existing endpoint resource.
=> provide an endpoint patch for volumes

extras/tools/scrub.py
Previously, the scrub.py script was not adjusting the freesize of
the block hosting volume in accordance with the block volume being
deleted. This patch fixes that oversight.
Fixes #
=> extra tools: when deleting a single block volume, adjust bhv freesize

client/cli/go/cmds/block_volume.go, middleware/jwt.go, pkg/glusterfs/api/types.go, pkg/kubernetes/backupdb.go, pkg/kubernetes/backupdb_test.go, pkg/kubernetes/namespace.go, pkg/remoteexec/kube/target.go, server/rest/asynchttp_test.go
There are 3 types of errors fixed:
a. one empty line is required before where third-party pkgs imports
b. packages can have dashes in import path but won't have in name[1],
explicitly name them on import.
c. packages that are just version numbers like "v1" need explicit naming
too[2].
[1] https://github.com/golang/go/issues/17546
[2] https://github.com/golang/go/issues/29041
=> all: fix goimports errors

.travis.yml
Build using go 1.13. Does not drop any versions currently being tested.
Fixes #
=> travis: build on go 1.13

apps/glusterfs/app.go, apps/glusterfs/app_config.go, apps/glusterfs/update_db_vol.go, client/cli/go/cmds/heketi_storage.go, executors/cmdexec/volume.go, executors/executor.go, executors/injectexec/mock_base.go, executors/mockexec/mock.go, executors/stack/stack.go, main.go, pkg/db/dbvolume.go, tests/functional/TestErrorHandling/tests/update_dbvol_test.go
This PR starts off by incorporating changes from PR #1640 
New instances of heketidbstorage volume will be created with options to turn of so called perf xlators.
A new "offline" subcommand "update-dbvol" is provided to conveniently update existing heketidbstorage volumes to the new set of options. Note that this *intentionally* doesn't update the options in the db. Currently this is the only tool that changes the volume options, normally heketi only sets volume options at create time. Syncing the volume options from gluster to the db is a topic reserved for future work.
A set of "error handling tests" to check the behavior of the new command.
Fixes #
=> Use "safer" volume options on heketidbstorage

apps/glusterfs/app.go
During some previous refactoring a log line printing that the db open
in read-write mode failed was moved such that the line always gets
printed even if the err is nil. Fix this mistake and only print
the log line when the previous function actually returns an error.
Fixes #
=> apps: do not emit error log line when db open is successful

.travis.yml, client/cli/go/cmds/heketi_storage.go, extras/docker/fromsource/Dockerfile, glide.lock, glide.yaml, pkg/kubernetes/backupdb.go, pkg/kubernetes/backupdb_test.go, pkg/kubernetes/namespace.go, pkg/kubernetes/pv.go, pkg/remoteexec/kube/conn.go, pkg/remoteexec/kube/exec.go, pkg/remoteexec/kube/target.go, pkg/remoteexec/ssh/ssh.go
* Drops go1.9 support (current versions of client-go use strings.Builder, which is go1.10+... only go1.12 and go1.13 are still in support)
* Updates kubernetes client libraries from Kubernetes v1.6 levels (!) to current versions (v1.15.3)
* Removes dependency on k8s.io/kubernetes (greatly reducing vendor size from 197MB on master to 109MB with this PR)
* Needed to unblock Kubernetes moving to go1.13 (https://github.com/kubernetes/kubernetes/issues/82531)
* Added ability to specify known_hosts files for ssh exec with $SSH_KNOWN_HOSTS (previously host verification was just skipped)
Fixes #1648
Fixes #1110
Updated version of https://github.com/heketi/heketi/pull/1542
cc @munnerz
=> Bump k8s libraries to 1.15.3 levels

extras/tools/comparison.py
Earlier, the error log was referring to gluster volume name from path in
all cases.
=> tools: print glusterblock volume name for blockvolumes

apps/glusterfs/tag_matching_rule.go, apps/glusterfs/tag_matching_rule_test.go, apps/glusterfs/volume_entry.go, apps/glusterfs/volume_entry_allocate.go, tests/functional/TestErrorHandling/tests/tag_matching_test.go
As outlined in the [tag matching design doc](/heketi/heketi/blob/master/docs/design/tag-matching.md) an administrator can set up tags on nodes and devices and then when volumes are being created a tag matching rule can be specified such that the bricks that make up the volume are placed only on matching devices.
A simple use case would be devices managed by heketi with heterogeneous performance characteristics. An admin might tag some disks with "perf:fast" and others with "perf:slow". Then depending on the needs of the volume (eg. small/fast vs. large/slow) the volume can be requested with volume options like so "user.heketi.device-tag-match perf=fast" or  "user.heketi.device-tag-match perf=slow". Note that inverse matches are also supported, example "user.heketi.device-tag-match …
=> Implement core "Tag Matching" feature for placing bricks on devices

extras/docker/fromsource/Dockerfile
The 'find' utility is required for some features of the heketi start
script. This change requires it be part of the fromsource image.
Fixes #
=> extras: include 'find' tool in fromsource container image

apps/glusterfs/volume_durability_replica.go, apps/glusterfs/volume_durability_test.go
Fixed logic for enabling brick migration for volumes with replica < 3, at least 1 brick must be online as source for migration
Migrating bricks of replica 2 volumes failed because at least 2 bricks needed to be online. The PR fixes this issue ensuring that for replica < 3 volumes at least 1 brick must be online.
Fixes #1628
=> Fixed migration logic for replica < 3 volumes

apps/glusterfs/operations_volume.go, apps/glusterfs/pendingop_entry.go, tests/functional/TestErrorHandling/tests/offline_cleanup_test.go
It was found that a volume expand operation that fails due to errors in the exec phase would leave a trivial setup inconsistent with regards to the sizes of devices. This PR fixes that issue as well as some ancillary items found while working on this problem.
Fixes rhbz#1653567
=> fix inconsistent db after (failing) volume expand operation

docs/admin/server.md, etc/heketi.json, executors/cmdexec/brick.go, executors/cmdexec/brick_test.go, executors/cmdexec/cmdexec.go, executors/cmdexec/config.go, executors/cmdexec/device.go, tests/functional/TestErrorHandling/tests/error_inject_test.go, tests/functional/TestErrorHandling/tests/options_test.go
There are a few potential issues when running LVM commands inside a Gluster container. This can be solved by running the commands on the container host, instead of in the container. The `nsenter` command can be used to 'break out' of the container, and execute the command on the host.
* difficulties with udev synchonisation (file locking under `/run` and IPC semaphores)
* differences/incompatibilities between LVM versions on the host and in the container
This PR currently is a RFC to get feedback on the approach taken. Tests have been done, and the needed functionality seems to be present.
=> execute LVM commands on the host instead of in a Gluster container

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
This commit adds several information elements to device metrics:
* Node Manage Hostname    `manage` (as a replacement of `hostname`)
* Node Storage Hostname    `storage`
* Device Id                            `id`
* Device PV UUID                 `pv_uuid`
Metrics tests have been also altered to reflect this change.
Signed-off-by: Justin Ferrieu <jferrieu@objectif-libre.com>
This PR adds more information to existing heketi device metrics. We could need these so we can make easier join queries with i.e. the gluster exporter metrics that could be useful for later use, dashboard making, etc.
Also these changes reflect more what we can see on the `topology info` of the heketi cli.
=> Add information to device metrics

apps/glusterfs/app.go, apps/glusterfs/app_device.go, apps/glusterfs/operations_device.go, apps/glusterfs/operations_device_test.go, apps/glusterfs/operations_load.go, apps/glusterfs/pendingop.go, apps/glusterfs/volume_entry_allocate.go, client/api/go-client/brick.go, client/cli/go/cmds/brick.go, pkg/glusterfs/api/types.go, tests/functional/TestErrorHandling/tests/brick_evict_test.go
The ability to evict (aka remove but that word is overused in heketi) a single brick. Since all other conditions must be met, evicting an existing brick always means that a new brick is created to take the old brick's place. This means its effecitvely brick add + gluster brick replace + brick remove.
Command line example: `heketi-cli brick evict f37409fe4ab83a150307a1b622b3da4f`
Fixes #1596
PR Includes:
* Core operation code
* Server Side API Support
* Go API
* CLI Interface
* Module tests
* Functional tests
=> Evict a Brick

.travis.yml
While setting up the test environment on Travis CI, pip is run as root.
This seems to create a .cache/pip directory in the travis users home
directory. Subsequently running pip as user travis fails:
WARNING: Building wheel for d2to1 failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/4d'
Issue was noticed in #1649. All recent builds failed the same way.
=> Fix s390x builds in Travis CI

apps/glusterfs/operations_device.go, tests/functional/TestErrorHandling/tests/brick_evict_test.go
Fixes some issues in the brick eviction operation, primary around the operation clean up path.
The three issues are a bad device ID reference when clean+clean-done is run outside of the rollback code; an invalid nested db transaction; and the inability to tell the difference between never checking the status of brick replace from gluster vs. the brick was not replaced. It also adds some debug logging and a test for the first error condition.
=> Assorted brick eviction fixes

client/cli/go/cmds/device.go, docs/admin/maintenance.md
The example given in `heketi-cli device add -h` is missing a trailing backslash. 
This PR corrects that example, and updates the corresponding part in `maintenance.md` file as well.
Fixes #  N/A
=> Fix(cli): correct example given in add device cmd help

apps/glusterfs/device_entry.go, apps/glusterfs/operations_cleanup.go, apps/glusterfs/operations_cleanup_test.go, apps/glusterfs/operations_device.go, apps/glusterfs/operations_device_test.go, apps/glusterfs/operations_load.go, apps/glusterfs/pendingop.go, apps/glusterfs/pendingop_entry.go, tests/functional/TestErrorHandling/tests/device_remove_test.go
Replace the old ad-hoc sequence of exec calls and db modifications made
by the device remove operation with iteration of calls into the newer
brick evict operation.
Modulo bugs this should be more reliable than the old approach because
brick evict's clean is smarter and properly handles failures or stale
operations. All the parent has to do it let the child handle the clean
up of the child operation that failed and then clean its own db state
up. Note that this means the operation is cleaned, but the operation is
not _resumed_. Any operation that is failed or incomplete will only
clean the current child and the device will remain in the offline state
and may still have one ore more bricks on it. But at this point it
should be safe to request removal of the device once again.
Probably, but …
=> Remove devices by nested brick evict operations

.travis.yml
It is consistently failing due to an error running go get early in the
build. Not going to debug it myself.
=> travis: disable go 1.13 s390 build in travis

apps/glusterfs/app.go, apps/glusterfs/app_block_volume.go, apps/glusterfs/block_volume_entry.go, apps/glusterfs/operations_block_volume.go, apps/glusterfs/operations_load.go, apps/glusterfs/pendingop.go, apps/glusterfs/pendingop_entry.go, client/api/go-client/block_volume.go, client/cli/go/cmds/block_volume.go, executors/cmdexec/block_volume.go, executors/cmdexec/block_volume_test.go, executors/executor.go, executors/mockexec/mock.go, executors/stack/stack.go, pkg/glusterfs/api/types.go, tests/functional/TestSmokeTest/tests/block_volume_test.go
Implement block volume expand interface in heketi
Pushing it live with the intention that I will have my code side review comments ready by that time I finish on the TODO list.
The RFE just works fine now but also check for TODO list at the end of this comment which I got from John and Talur in a demo meeting.
```
Before Expand:
-------------
[root@server1 ~]# heketi-cli blockvolume create --size 1
Name: blockvol_365f428f2bf4b5a37f644c239f148058
Size: 1
Volume Id: 365f428f2bf4b5a37f644c239f148058
Cluster Id: 0b5740b0e3c34e935c1cd73e8bbf3c71
Hosts: [192.168.121.42 192.168.121.68 192.168.121.155]
IQN: iqn.2016-12.org.gluster-block:afcc41a3-1c46-4102-812b-5a0767cfb16a
LUN: 0
Hacount: 3
Username:
Password:
Block Hosting Volume: 7b3e7fceae17a57e0fc9ddedcce75912
[root@server1 ~]# heketi-cli …
```
=> gluster-block: implement expand feature interface

docs/maintainers/docker-hub.md
Document how the docker hub is integrated with GitHub for container builds.
=> docs: docker hub integration

client/cli/go/cmds/block_volume.go, client/cli/go/cmds/volume.go
Currently:
------------
$ heketi-cli volume expand --volume=60d46d518074b13a04ce1022c8c7193c --expand-size=10 
$ heketi-cli blockvolume expand --block-volume=60d46d518074b13a04ce1022c8c7193c --new-size=10
Fix:
----
I see info and delete commands doesn't use any flag or extra option name specific to collecting volume id, instead, they simply read the arg(0) as volumeId.
Just to keep the semantics in alignment with other commands like info and delete, adding support for below syntax too:
$ heketi-cli volume expand 60d46d518074b13a04ce1022c8c7193c --expand-size=10 
$ heketi-cli blockvolume expand 60d46d518074b13a04ce1022c8c7193c --new-size=10
But we still maintain the old syntax of using `--volume` or `--blockvolume` in expand commands of both `file` and `block` volumes for compatibility. …
=> blockvolume: tuning the semantics of expand command

.travis.yml
Add build for latest go v1.14 in travis for s390x and remove for go v1.13 due to panic memory runtime error for s390x observed only on lxd travis.
Raised PR for fixing issue "https://github.com/heketi/heketi/issues/1711"
=> Add latest go v1.14 in travis for s390x

tests/functional/vagrant/roles/common/tasks/main.yml
Recently, the setup of the vagrant vms in the functional tests has
begun to fail due to gluster version conflicts. Use gluster 6 instead of
4.1 in the test vms. The use of 4.1 was a workaround for an issue in
5 and should hopefully have been fixed. We'll see....
=> functional tests: use a recent-ish version of gluster

apps/glusterfs/block_volume_expand_test.go, executors/injectexec/mock_base.go, executors/mockexec/mock.go
* rename inner mock exec functions to match proper names in the executor interface
* fix missing default functions for inject exec mock functions
The latter change is the important one as it allows the use of the new executor functions for block volume expand and block volume info to function as designed.
I see an opportunity here for making the mock executor and thus the error injection executor less boilerplate-y in the future and avoid issues like this down the road. I'll try to file a PR for that soonish. This one should just fix the immediate issue.
=> Fix using newer block volume related executor functions with the error injection executor

apps/glusterfs/block_volume_entry.go, apps/glusterfs/block_volume_expand_test.go, apps/glusterfs/operations_block_volume.go, executors/cmdexec/block_volume.go, executors/executor.go, pkg/glusterfs/api/types.go, tests/functional/TestSmokeTest/tests/block_volume_test.go
We should use newly expanded size on the block volume by growing filesystem on
the block device only when block volume is successfully expanded.
On partial failures (few nodes configured to size X and few nodes with size Y)
we should never proceed further for using the newly expanded size. This
might get us into block storage level inconsistencies.
To indicate the real usable size of a block volume, we have come up with
adding a new field to the block volume info.
$ heketi-cli blockvolume expand 95aaa622f466bc4ae9e5d460ac55505b --new-size=5
Name: blockvol_95aaa622f466bc4ae9e5d460ac55505b
Size: 5
UsableSize: 5
Volume Id: 95aaa622f466bc4ae9e5d460ac55505b
Cluster Id: 71d6c0a8f6e88c1ddc84b78b464aafd9
Hosts: [192.168.121.55 192.168.121.206 192.168.121.253]
IQN: …
=>  db: introduce UsableSize flag in block volume Info

tests/functional/run.sh
Add mising argument '-d|--tests-dir' in --help option of script
in the functional tests run.sh script.
https://github.com/heketi/heketi/issues/1721
Fixes #
=> func tests: Add missing arg '-d|--tests-dir' in help

tests/functional/TestErrorHandling/tests/block_expand_test.go
Test Summary:
*** PASS: TestBlockExpandInject (157.68s)
*** PASS: TestBlockExpandInject/TryExpandSuccess (24.41s)
*** PASS: TestBlockExpandInject/TryExpandFailAtVeryBeginning (24.01s)
*** PASS: TestBlockExpandInject/TryExpandFail (25.31s)
*** PASS: TestBlockExpandInject/RetryExpandFail (25.26s)
*** PASS: TestBlockExpandInject/RetryExpandSuccessWithSameSize (24.83s)
*** PASS: TestBlockExpandInject/RetryExpandSuccessWithDifferentSize (24.40s)
Depends on: https://github.com/heketi/heketi/pull/1718, https://github.com/heketi/heketi/pull/1725
Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>
=> errInj: add error Injection tests for block expand

apps/glusterfs/app_device.go
This will achieve correct logging. The older logging can lead us to be in false impression that we have deleted a node, which is not true.
=> apps: Correct the logging of 'DeviceDelete'

apps/glusterfs/operations_device.go
Device remove fails while running gluster commands on the same node where
device/brick is present if the node is down.
Fix the same via passing the working node from the same cluster.
The Pr fix the regression which is introduced recently with brick evict patches.
Fixes #1744
=> apps: Fix regression in brickEvict/"execGetReplacmentInfo"

client/cli/go/cmds/db.go
Previously, the cli code for printing a db dump gathered from the server
was passing the string as the first string argument to a print function.
This print will then use any characters in the text from the server,
like %-signs, as format strings and potentially mangle the output. My
lazy fix is to just use a single "%s" format string and move the json
data from the server to a secondary argument.
Fixes #
It's not trivial to put '%' chars into the db dump, but can be done by setting volume options with these chars. AFAIK, this isn't valid for gluster but since heketi doesn't validate the values it happily stores thems and then running `heketi-cli db dump` will give you mangled-by-Printf non-json.
=> cli: avoid treating characters in db dump as format strings

README.md
Removes the "badges" from the README.md file. These badges are a
combination of uninteresting, misleading, and distracting, in some
proportion depending on wether you are a newcomer to the project or an
old timer. They add so little value it is better to remove them.
=> readme: remove unhelpful/uninteresting badges

client/api/go-client/client.go, client/api/go-client/client_test.go
Allows consumers of heketi client libs to make deep, general customization to the http.Client used by the heketi client package.
The changes should be fully backwards compatible and if the customization function is not supplied the system will continue to behave as before. If the customization function is supplied the code importing and using the heketi client can provide http clients setup any way desired, or even a non-http-client that provides the same Do method as an http client.
The HeketiHttpClient is public so any code that wants to set up the client the way heketi does but intercept that and customize that (make a code sandwich ;-)) can do so.
=> General support for http client customization

pkg/utils/bodystring.go
We found that very long error messages, in one case generated by pvcreate, caused the heketi support code used in the client to incorrectly treat it as a case of no-error-message. This appears to be due to the long error messages causing the golang http libs to emit an HTTP repsonse without a content-length, where a short error message produces a response with a content-length.
Fixes rhbz#1882701
=> utils: support reading data even if content-length is unset

executors/cmdexec/volume.go, tests/functional/TestErrorHandling/tests/brick_evict_test.go
There's a panic that can occur in heketi when brick evict is run. If there's  an eviction to be done, including if part of a device remove, and the volume exists in heketi but not gluster heketi will panic.   This happens because gluster command fails to set a non-zero exit code. Heketi treats this as a success and tries to index into the "list of volumes" for the requested volume but there's a zero-length list, and that triggers a go panic.
Fixes rhbz#1888760
At first I didn't like the idea of actually removing the volume from gluster in the test and wanted to just use error injection. However, I concluded that doing it with an actual command is more "real world" and could possibly help find other quirks in this workflow in the future rather than the "mocking" approach of error injection …
=> Fix brick eviction when a volume is not present in gluster

tests/functional/lib.sh, tests/functional/vagrant/dump.sh
Lately, the tests are failing due to mysterious error within
gluster-block in the CI environment. This is my 2nd, slightly cleaner,
attempt at diagnosing gluster block errors when the tests fail in the
CI.
Fixes #
=> functional tests: add a way to debug g-block test failures

apps/glusterfs/app_middleware.go, middleware/jwt.go, middleware/jwt_test.go
Using gorilla/context leads to memory leaks on go version more than 1.7. https://github.com/gorilla/context.
fixes #1777 
Fixes #
In this MR I changed gorilla context to http.Request.Context()
=> Gorilla Context Memory leak

apps/glusterfs/pendingop.go
In PR #1702 we added a new OperationType and ChangeType. However, it
renumbered the consts. In cases where heketi is upgraded when the
db has pending ops, this can lead to undefined behavior.
=> apps: revert the renumbering of enum in pendingop

README.md
That's right. It's time to make it known that the heketi project is in maintenance-only status.
It should be clear from the text that it's not quite dead, we're not making the repo read-only/archived or anything, and that important [1] fixes will be considered, but it is entering it's twilight years.
[1] - To be decided at our discretion.
=> readme: announce hard maintenance status

.github/workflows/ci.yml, .travis.yml, tests/functional/run.sh
glide.sh is down. I don't know if its coming back because glide is kinda "dead" anyway. Even if it does we don't really need to rely on the (distasteful IMO) technique of curl-pipe-bash.
Fixes the CI not working.
=> fix glide "install" in tests

apps/glusterfs/app_middleware.go, client/api/go-client/client.go, docs/profiling.md, glide.lock, glide.yaml, middleware/jwt.go, middleware/jwt_test.go
The old library is abaondoned and has some severe CVEs in it. The form3-tech
fork has fixed those CVEs and is the most popular fork. CVE is here:
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515
Fixes #
I understand this is going toward maintenance mode. Hoping to get this update in to help unblock other libraries that import heketi from updating.
=> Switch to form3-tech/jwt-go.

README.md, extras/docker/centos/README.md
Due to the recent changes at freenode and also due to the current
maintenance status of heketi, we are removing the references to freenode
from our documentation. Github should be the best place to contact the
developers for anything related to heketi.
Fixes #
=> Docs: remove reference to freenode

.github/workflows/ci.yml
We're only testing "old" go versions currently. We should test old versions as needed, but also test versions actually supported by Go.
=> workflows: add go versions 1.15 & 1.16 to actions runs

tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go, tests/functional/test.env
This file should be read by the centos ci integration tests script and
used to select a minimum go version.
=> functional: add a minimum recommended go version to our test config

extras/docker/oldgo-fromsource/Dockerfile, extras/docker/oldgo-fromsource/README.md
This isn't meant for production, just dev & test when needing to ensure
that heketi can be built using older go versions.
You can use the GO_VERSION build arg to specify other go versions w/o having to edit the dockerfile too.
=> extras: add dockerfile for building with old versions of go
